import { sanitizeZemaxName } from './names.js';
import { fmt } from './format.js';

/**
 * Produce a collision-free Zemax name for `orig` against the names already in
 * `used`, appending _2, _3, … and truncating the 32-char base to make room for
 * the suffix. The chosen name is added to `used`.
 */
function dedupeZemaxName(orig, used) {
    const base = sanitizeZemaxName(orig);
    let s = base, k = 2;
    while (used.has(s)) {
        const sfx = '_' + (k++);
        s = (base.length + sfx.length > 32 ? base.slice(0, 32 - sfx.length) : base) + sfx;
    }
    used.add(s);
    return s;
}

/**
 * Generate COATING.DAT text from materials + coatings.
 * @param {object} doc
 *   @param {Array<{name:string, points:Array<[number,number,number]>}>} doc.materials
 *   @param {Array<{name:string, layers:Array<{material,thickness,isAbsolute}>}>} doc.coatings
 *   @param {string[]} [doc.headerComments]
 * @returns {string}
 */
export function generateZemaxCoating(doc) {
    const lines = [];
    const header = doc.headerComments || [
        'Generated by TFStudio — Zemax OpticStudio COATING.DAT export',
        'Wavelengths in micrometres; imaginary index stored as -k (Zemax convention).',
        'Coating layer order: incident-medium side -> substrate side.',
    ];
    for (const h of header) lines.push('! ' + h);
    lines.push('');

    // Build a collision-free Zemax name per ORIGINAL material name. Two distinct
    // materials whose names sanitize/truncate to the same 32-char string (e.g.
    // "SiO2-A"/"SiO2.A", or two long names sharing a prefix) would otherwise emit
    // duplicate MATE blocks AND make their coating-layer references ambiguous.
    // Keying by original name means the MATE block and every layer reference
    // resolve to the SAME unique name.
    const matNames = new Map();      // original material name → unique Zemax name
    const usedMat  = new Set();
    const uniqueMatName = (orig) => {
        if (matNames.has(orig)) return matNames.get(orig);
        const s = dedupeZemaxName(orig, usedMat);
        matNames.set(orig, s);
        return s;
    };

    // Materials first — Zemax verifies every coating material is defined.
    for (const m of (doc.materials || [])) {
        lines.push(`MATE ${uniqueMatName(m.name)}`);
        const pts = (m.points || []).slice().sort((a, b) => a[0] - b[0]);
        for (const [lamUm, n, imag] of pts)
            lines.push(`${fmt(lamUm)} ${fmt(n)} ${fmt(imag)}`);
        lines.push('');
    }

    // Coatings (their names live in a separate namespace; dedupe those too).
    const usedCoat = new Set();
    const uniqueCoatName = (orig) => dedupeZemaxName(orig, usedCoat);
    for (const c of (doc.coatings || [])) {
        lines.push(`COAT ${uniqueCoatName(c.name)}`);
        for (const L of (c.layers || []))
            lines.push(`${uniqueMatName(L.material)} ${fmt(L.thickness)} ${L.isAbsolute ? 1 : 0}`);
        lines.push('');
    }

    return lines.join('\r\n');
}
