/**
 * Full TFStudio Design object assembly from WDM wizard parameters. See
 * ../wdmDesigner.js for the full geometry model and references.
 */

import { buildWDMStack } from './stack.js';
import { buildWDMOperands } from './operands.js';
import { makeBaseDesign } from './baseDesign.js';

/**
 * Build a complete TFStudio Design object from WDM wizard parameters.
 *
 * Combines `buildWDMStack` + `buildWDMOperands` and packages them in a fresh
 * design with sensible substrate / media defaults. Returns a design object
 * that can be handed straight to the project explorer's `addItem`-style flow.
 */
export function buildWDMDesign(params) {
    const {
        name = 'WDM Filter',
        matH, matL,
        substrateMaterial = 'BK7',
        substrateThicknessMm = 1.0,
        incidentMedium = 'Air',
        exitMedium = 'Air',
        lambda0_nm,
        cavities, mirrorPairs, spacerOrder, spacerKind, includeAR,
        passbandFWHM_nm, stopbandWidth_nm, transitionNm,
        aoi = 0, pol = 'avg',
        minThicknessNm, maxThicknessNm,
    } = params;

    const stack = buildWDMStack({
        matH, matL, lambda0_nm,
        cavities, mirrorPairs, spacerOrder, spacerKind, includeAR,
    });
    const operands = buildWDMOperands({
        lambda0_nm, passbandFWHM_nm, stopbandWidth_nm, transitionNm,
        aoi, pol, minThicknessNm, maxThicknessNm,
        filterLabel: `WDM ${cavities}-cavity (k=${mirrorPairs}, m=${spacerOrder})`,
    });

    const base = makeBaseDesign(name);
    return {
        ...base,
        name,
        referenceWavelength: lambda0_nm,
        incidentMedium,
        substrate: { material: substrateMaterial, thickness: substrateThicknessMm },
        exitMedium,
        surfaceMode: 'front_only',
        frontLayers: stack.layers,
        backLayers: [],
        meritOperands: operands,
        notes: `Generated by WDM wizard\n` +
               `λ₀ = ${lambda0_nm} nm,  H = ${matH},  L = ${matL}\n` +
               `${stack.N}-cavity, k=${stack.k} QW pairs per mirror, ` +
               `spacer order m=${stack.m} (${spacerKind})\n` +
               `Total physical thickness ≈ ${stack.totalNm.toFixed(1)} nm,  ` +
               `${stack.layers.length} layers`,
        // Carry the wizard recipe so a future "edit wizard params" command can
        // re-open it preloaded; not used by anything else right now.
        wdmRecipe: {
            lambda0_nm, cavities, mirrorPairs, spacerOrder, spacerKind, includeAR,
            matH, matL, substrateMaterial, incidentMedium, exitMedium,
            passbandFWHM_nm, stopbandWidth_nm, transitionNm, aoi, pol,
            minThicknessNm, maxThicknessNm,
        },
        _wdmStackInfo: stack,
    };
}
