// Antireflection coatings: broadband, single-wavelength V-coats and
// multi-band laser ARs. Field reference: ../entryModel.js.
import { embedded } from './materials.js';

export const ANTIREFLECTION = [
    {
        id: 'ar-bbar-420-680-tio2-mgf2-4l',
        name: 'Broadband AR 420-680 nm, TiO2/MgF2, 4 layers',
        type: 'ar',
        tags: ['visible', 'broadband', 'imaging', 'all-dielectric', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this when a visible camera, eyepiece or display window on crown glass needs a first AR to refine from. Four layers of two common materials, so it is cheap to run and easy to monitor.',
        limitations: 'Reflectance climbs past 700 nm, so it is not a NIR coating. MgF2 needs a hot substrate to be durable. The built-in TiO2 data covers 370-827 nm, which sets how far the preview can be trusted.',
        source: 'Macleod, Thin-Film Optical Filters, 5th ed., section 4.3 Multilayer Antireflection Coatings, Table 4.2: the four-layer MgF2/TiO2 design of Reichert, UK Patent 991,635 (1962), quoted there as optical thicknesses 54, 56.5, 78.5 and 161 nm at indices 2.28 and 1.37. Those optical thicknesses were converted with the built-in TiO2 and MgF2 dispersion and then re-optimized over 420-680 nm with TFStudio against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        band: [420, 680],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 800],
        layers: [
            { material: 'builtin:TiO2', thickness: 11.92 },
            { material: 'builtin:MgF2', thickness: 51.81 },
            { material: 'builtin:TiO2', thickness: 16.68 },
            { material: 'builtin:MgF2', thickness: 118.58 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.005, label: 'R avg ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.01, label: 'R max ≤ 1%' },
        ],
    },
    {
        id: 'ar-bbar-420-680-nb2o5-sio2-silica-4l',
        name: 'Broadband AR 420-680 nm on fused silica, Nb2O5/SiO2, 4 layers',
        type: 'ar',
        tags: ['visible', 'broadband', 'imaging', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'fused-silica', 'synthesized'],
        use: 'Use this when a fused silica window or lens needs a hard-oxide AR across the visible. Both materials sputter and e-beam well and survive cleaning, so this is the one to start from for a production visible AR.',
        limitations: 'Reflectance climbs past 700 nm. The built-in Nb2O5 data stops at 1000 nm and carries a small extinction below 450 nm, which is what the residual absorption in the headline numbers comes from.',
        source: 'The four-layer broadband AR of Macleod, Thin-Film Optical Filters, 5th ed., section 4.3 (thin high index, thin low index, half-wave high index, quarter-wave low index). Layer thicknesses were designed in TFStudio for fused silica with the built-in Nb2O5 and SiO2 data, by damped least squares against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 550,
        band: [420, 680],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 800],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 11.75 },
            { material: 'builtin:SiO2', thickness: 37.35 },
            { material: 'builtin:Nb2O5', thickness: 112.74 },
            { material: 'builtin:SiO2', thickness: 88.32 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.0025, label: 'R avg ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.005, label: 'R max ≤ 0.5%' },
        ],
    },
    {
        id: 'ar-bbar-1000-1600-hfo2-mgf2-4l',
        name: 'Broadband AR 1000-1600 nm on fused silica, HfO2/MgF2, 4 layers',
        type: 'ar',
        tags: ['nir', 'broadband', 'laser', 'all-dielectric', 'normal-incidence', 'fused-silica', 'low-loss', 'synthesized'],
        use: 'Use this when a fused silica window has to pass a near-infrared band rather than one laser line, for example a 1064 nm laser and its 1310 or 1550 nm alignment and telecom wavelengths on the same part.',
        limitations: 'MgF2 is soft and needs a hot substrate. HfO2 was chosen for its laser damage threshold, not for the lowest possible absorption; the residual absorption in the headline numbers is that of the built-in HfO2 data.',
        source: 'The four-layer broadband AR of Macleod, Thin-Film Optical Filters, 5th ed., section 4.3. Layer thicknesses were designed in TFStudio for fused silica with the built-in HfO2 and MgF2 data, by damped least squares against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1300,
        band: [1000, 1600],
        aoi: 0,
        polarization: 'avg',
        preview: [800, 1900],
        layers: [
            { material: 'builtin:HfO2', thickness: 34.94 },
            { material: 'builtin:MgF2', thickness: 76.56 },
            { material: 'builtin:HfO2', thickness: 319.28 },
            { material: 'builtin:MgF2', thickness: 219.73 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.0025, label: 'R avg ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.005, label: 'R max ≤ 0.5%' },
        ],
    },
    {
        id: 'ar-vcoat-532-ta2o5-mgf2',
        name: 'V-coat AR at 532 nm, Ta2O5/MgF2, 2 layers',
        type: 'ar',
        tags: ['visible', 'single-wavelength', 'laser', 'v-coat', 'all-dielectric', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this when a doubled Nd:YAG beam has to cross a glass surface with as little loss and back reflection as possible. Two layers, one deposition run, nothing to tune but the two thicknesses.',
        limitations: 'The reflectance minimum is narrow: it is already above 0.1% roughly 20 nm either side of 532 nm, so this is a single-line coating and not a green bandpass AR. The residual absorption comes from the built-in Ta2O5 data.',
        source: 'Macleod, Thin-Film Optical Filters, 5th ed., section 4.2 Two-Layer Antireflection Coatings, the MgF2 and Ta2O5 V-coat of Figure 4.13: optical thicknesses 0.319 and 0.063 of a wavelength on glass of index 1.52. The same two materials and the same structure were re-optimized at 532 nm with TFStudio on the built-in BK7, Ta2O5 and MgF2 data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 532,
        band: [527, 537],
        aoi: 0,
        polarization: 'avg',
        preview: [480, 590],
        layers: [
            { material: 'builtin:Ta2O5', thickness: 15.51 },
            { material: 'builtin:MgF2', thickness: 123.09 },
        ],
        spec: [
            { kind: 'R_AT', channel: 'R', lambda: 532, cmp: 'le', target: 0.0025, label: 'R at 532 nm ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.005, label: 'R max ≤ 0.5%' },
        ],
    },
    {
        id: 'ar-vcoat-633-tio2-mgf2',
        name: 'V-coat AR at 633 nm, TiO2/MgF2, 2 layers',
        type: 'ar',
        tags: ['visible', 'single-wavelength', 'laser', 'v-coat', 'all-dielectric', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this when a HeNe beam or a 633 nm alignment line has to pass a glass window or lens without a ghost. The built-in TiO2 data carries no absorption in the visible, so the residual loss here is reflection only.',
        limitations: 'A single-line coating: reflectance rises quickly either side of 633 nm. TiO2 needs oxygen backfill or ion assist to reach the index used here, and the built-in data covers 370-827 nm.',
        source: 'The two-layer V-coat of Macleod, Thin-Film Optical Filters, 5th ed., section 4.2 (thin high-index layer on the substrate, thicker low-index layer outermost), built here from the built-in TiO2 and MgF2 data and optimized at 633 nm with TFStudio.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 633,
        band: [628, 638],
        aoi: 0,
        polarization: 'avg',
        preview: [570, 700],
        layers: [
            { material: 'builtin:TiO2', thickness: 11.30 },
            { material: 'builtin:MgF2', thickness: 150.24 },
        ],
        spec: [
            { kind: 'R_AT', channel: 'R', lambda: 633, cmp: 'le', target: 0.0025, label: 'R at 633 nm ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.005, label: 'R max ≤ 0.5%' },
        ],
    },
    {
        id: 'ar-vcoat-1064-hfo2-sio2',
        name: 'V-coat AR at 1064 nm, HfO2/SiO2, 2 layers',
        type: 'ar',
        tags: ['nir', 'single-wavelength', 'laser', 'v-coat', 'hfo2-sio2', 'normal-incidence', 'fused-silica', 'laser-damage'],
        use: 'Use this when a 1064 nm Nd:YAG beam passes a fused silica window, lens or Q-switch. HfO2 over SiO2 is the pair most laser shops reach for at this wavelength because of its damage threshold.',
        limitations: 'A single-line coating. Both layers are thicker than a quarter wave, so the coating is about 290 nm of material and the deposition takes longer than a visible V-coat.',
        source: 'The two-layer V-coat of Macleod, Thin-Film Optical Filters, 5th ed., section 4.2, built from the built-in HfO2 and SiO2 data on a fused silica substrate and optimized at 1064 nm with TFStudio.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1064,
        band: [1054, 1074],
        aoi: 0,
        polarization: 'avg',
        preview: [950, 1200],
        layers: [
            { material: 'builtin:HfO2', thickness: 55.53 },
            { material: 'builtin:SiO2', thickness: 236.25 },
        ],
        spec: [
            { kind: 'R_AT', channel: 'R', lambda: 1064, cmp: 'le', target: 0.0025, label: 'R at 1064 nm ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.005, label: 'R max ≤ 0.5%' },
        ],
    },
    {
        id: 'ar-dual-532-1064-hfo2-sio2-4l',
        name: 'Dual-line AR 532 and 1064 nm, HfO2/SiO2, 4 layers',
        type: 'ar',
        tags: ['visible', 'nir', 'dual-band', 'laser', 'hfo2-sio2', 'all-dielectric', 'normal-incidence', 'fused-silica'],
        use: 'Use this when one fused silica part has to pass both the fundamental and the second harmonic of a Nd:YAG laser, for example the window of a doubling stage or a harmonic separator that must not lose either line.',
        limitations: 'Only the two lines are antireflected. Between them the reflectance rises to about 11%, higher than the uncoated surface, so this coating must not be used as a broadband AR. Nothing is claimed outside the two design bands.',
        source: 'Designed in TFStudio: a four-layer HfO2/SiO2 stack refined by damped least squares against zero reflectance at 532 and 1064 nm on the built-in material data. Not from a publication.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1064,
        bands: [[527, 537], [1054, 1074]],
        aoi: 0,
        polarization: 'avg',
        preview: [450, 1200],
        layers: [
            { material: 'builtin:HfO2', thickness: 143.71 },
            { material: 'builtin:SiO2', thickness: 38.18 },
            { material: 'builtin:HfO2', thickness: 38.53 },
            { material: 'builtin:SiO2', thickness: 101.74 },
        ],
        spec: [
            { kind: 'R_AT', channel: 'R', lambda: 532, cmp: 'le', target: 0.0025, label: 'R at 532 nm ≤ 0.25%' },
            { kind: 'R_AT', channel: 'R', lambda: 1064, cmp: 'le', target: 0.0025, label: 'R at 1064 nm ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', band: 0, target: 0.005, label: 'R max at 532 nm band ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', band: 1, target: 0.005, label: 'R max at 1064 nm band ≤ 0.5%' },
        ],
    },
    {
        id: 'ar-bbar-650-1050-hfo2-mgf2-4l',
        name: 'Broadband AR 650-1050 nm, HfO2/MgF2, 4 layers',
        type: 'ar',
        tags: ['visible', 'nir', 'broadband', 'imaging', 'all-dielectric', 'normal-incidence', 'glass', 'synthesized'],
        use: 'Use this on the windows and lenses of instruments that work across the red and the near infrared at once: silicon-detector optics, 785 and 808 nm diode paths, and the illumination side of near-infrared machine vision.',
        limitations: 'MgF2 is soft and needs a hot substrate. The band stops at 1050 nm because that is where the design was optimized, not because of a material limit; reflectance rises quickly below 620 nm.',
        source: 'The four-layer broadband AR of Macleod, Thin-Film Optical Filters, 5th ed., section 4.3, laid out for 650-1050 nm on BK7. HfO2 is the high index because the built-in data shows it as the lower-loss choice over this band; every thickness was optimized in TFStudio against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 850,
        band: [650, 1050],
        aoi: 0,
        polarization: 'avg',
        preview: [560, 1200],
        layers: [
            { material: 'builtin:HfO2', thickness: 24.92 },
            { material: 'builtin:MgF2', thickness: 48.05 },
            { material: 'builtin:HfO2', thickness: 217.67 },
            { material: 'builtin:MgF2', thickness: 147.06 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.0025, label: 'R avg ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.005, label: 'R max ≤ 0.5%' },
        ],
    },
    {
        id: 'ar-telecom-1310-1550-hfo2-mgf2-4l',
        name: 'Telecom AR at 1310 and 1550 nm, HfO2/MgF2, 4 layers',
        type: 'ar',
        tags: ['nir', 'dual-band', 'telecom', 'all-dielectric', 'normal-incidence', 'fused-silica', 'low-loss', 'synthesized'],
        use: 'Use this on the windows, collimator lenses and isolator parts of a fibre link that carries both the O band around 1310 nm and the C band around 1550 nm. Reflectance stays under a hundredth of a percent in both bands, so back reflection into the fibre stays low.',
        limitations: 'Nothing is claimed between the two bands, where reflectance is higher, or beyond them. MgF2 is soft and needs a hot substrate; a part that will be cleaned often is better served by a hard-oxide design with a wider band.',
        source: 'A four-layer AR designed in TFStudio for the two telecom windows on fused silica. HfO2/MgF2 is the pair because the built-in data shows it as both lower loss and higher contrast on fused silica than Ta2O5/SiO2; every thickness was optimized against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1430,
        bands: [[1280, 1340], [1520, 1580]],
        aoi: 0,
        polarization: 'avg',
        preview: [1150, 1750],
        layers: [
            { material: 'builtin:HfO2', thickness: 81.87 },
            { material: 'builtin:MgF2', thickness: 56.53 },
            { material: 'builtin:HfO2', thickness: 207.18 },
            { material: 'builtin:MgF2', thickness: 262.55 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', band: 0, target: 0.001, label: 'R avg O band ≤ 0.1%' },
            { kind: 'R_AVG', channel: 'R', cmp: 'le', band: 1, target: 0.001, label: 'R avg C band ≤ 0.1%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', band: 0, target: 0.002, label: 'R max O band ≤ 0.2%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', band: 1, target: 0.002, label: 'R max C band ≤ 0.2%' },
        ],
    },
    {
        id: 'ar-uv-245-400-al2o3-mgf2-4l',
        name: 'Broadband AR 245-400 nm on fused silica, Al2O3/MgF2, 4 layers',
        type: 'ar',
        tags: ['uv', 'broadband', 'uv-grade', 'laser', 'all-dielectric', 'normal-incidence', 'fused-silica', 'synthesized'],
        use: 'Use this on fused silica windows and lenses working in the ultraviolet: 248 and 266 nm laser paths, 365 nm curing optics, and the front end of a UV spectrometer. Both materials are transparent well below the band, so the coating does not become the absorbing part of the assembly.',
        limitations: 'Aluminium oxide is the highest index the built-in library carries this far into the ultraviolet, and at about 1.8 it gives little contrast against magnesium fluoride, so the residual reflectance is higher than a visible AR of the same layer count. The second layer is under 10 nm and needs a machine that can control that. Fused silica has to be the UV grade if the assembly is to work at 245 nm.',
        source: 'A four-layer Al2O3/MgF2 broadband AR for the ultraviolet on fused silica, the two built-in materials that stay transparent down to 245 nm; every thickness was optimized in TFStudio on the built-in material data against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 320,
        band: [245, 400],
        aoi: 0,
        polarization: 'avg',
        preview: [220, 500],
        layers: [
            { material: 'builtin:Al2O3', thickness: 20.19 },
            { material: 'builtin:MgF2', thickness: 9.57 },
            { material: 'builtin:Al2O3', thickness: 48.67 },
            { material: 'builtin:MgF2', thickness: 55.19 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.005, label: 'R avg ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.01, label: 'R max ≤ 1%' },
        ],
    },
    {
        id: 'ar-bbar-400-700-ta2o5-mgf2-4l',
        name: 'Broadband AR 400-700 nm, Ta2O5/MgF2, 4 layers',
        type: 'ar',
        tags: ['visible', 'broadband', 'imaging', 'all-dielectric', 'normal-incidence', 'glass', 'synthesized'],
        use: 'Use this when the whole visible band has to be covered on crown glass, not just its middle. It reaches the blue end that a TiO2 design cannot, because the tantalum pentoxide data used here runs down to 360 nm.',
        limitations: 'Reflectance reaches about 1.2% at 400 nm, the blue edge of the band, and rises quickly beyond 700 nm. MgF2 is soft and needs a hot substrate. The film data is carried with the entry because the built-in Ta2O5 starts at 500 nm.',
        source: 'The four-layer broadband AR of Macleod, Thin-Film Optical Filters, 5th ed., section 4.3, laid out for 400-700 nm on BK7 with a Ta2O5/MgF2 pair. The built-in Ta2O5 data starts at 500 nm and cannot cover this band, so the entry carries the sputtered Ta2O5 of Gao, Lemarchand and Lequime from refractiveindex.info instead; every thickness was optimized in TFStudio against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        bands: [[400,700]],
        aoi: 0,
        polarization: 'avg',
        preview: [370,800],
        layers: [
            { material: 'rii:Ta2O5-Gao', thickness: 16.38 },
            { material: 'builtin:MgF2', thickness: 29.90 },
            { material: 'rii:Ta2O5-Gao', thickness: 125.18 },
            { material: 'builtin:MgF2', thickness: 93.38 },
        ],
        materials: embedded('rii:Ta2O5-Gao'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.005, label: 'R avg ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.015, label: 'R max ≤ 1.5%' },
        ],
    },
    {
        id: 'ar-bbar-1050-1700-ta2o5-mgf2-4l',
        name: 'Broadband AR 1050-1700 nm, Ta2O5/MgF2, 4 layers',
        type: 'ar',
        tags: ['nir', 'broadband', 'telecom', 'laser', 'all-dielectric', 'normal-incidence', 'fused-silica', 'low-loss'],
        use: 'Use this on fused silica optics that have to pass the whole band from a 1064 nm laser through the telecom O and C bands, for example a shared window or a fibre collimator that sees several sources.',
        limitations: 'MgF2 is soft and needs a hot substrate. The film data is carried with the entry because the built-in Ta2O5 data has enough extinction in this band to cost about half a percent of transmittance in a stack this deep.',
        source: 'The four-layer broadband AR of Macleod, Thin-Film Optical Filters, 5th ed., section 4.3, laid out for 1050-1700 nm on fused silica with a Ta2O5/MgF2 pair. The entry carries the sputtered Ta2O5 of Gao, Lemarchand and Lequime from refractiveindex.info, which shows no measurable extinction over this band; every thickness was optimized in TFStudio against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1350,
        bands: [[1050,1700]],
        aoi: 0,
        polarization: 'avg',
        preview: [900,1800],
        layers: [
            { material: 'rii:Ta2O5-Gao', thickness: 34.92 },
            { material: 'builtin:MgF2', thickness: 92.61 },
            { material: 'rii:Ta2O5-Gao', thickness: 331.61 },
            { material: 'builtin:MgF2', thickness: 239.06 },
        ],
        materials: embedded('rii:Ta2O5-Gao'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.0025, label: 'R avg ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.005, label: 'R max ≤ 0.5%' },
        ],
    },
    {
        id: 'ar-mwir-3-5um-si3n4-silicon-1l',
        name: 'MWIR AR 3-5 um on silicon, single Si3N4 layer',
        type: 'ar',
        tags: ['mwir', 'broadband', 'thermal-imaging', 'single-layer', 'quarter-wave', 'all-dielectric', 'normal-incidence', 'silicon'],
        use: 'Use this as the hard single-layer coating on a silicon window or dome for a mid-wave thermal camera. One layer of silicon nitride cuts the reflectance of a bare silicon surface from about 30% to under 10% and survives rain and sand better than a soft fluoride.',
        limitations: 'Silicon nitride sits at about 2.4, well above the 1.85 a single-layer AR on silicon would want, so the best a single layer can do here is a few percent at the design wavelength and about 8% averaged across the band. Use the four-layer Ge/MgF2 design when the loss matters more than the hardness.',
        source: 'A single exact quarter wave of silicon nitride at 4 um on silicon, the single-layer AR of Macleod, Thin-Film Optical Filters, 5th ed., section 4.1; refinement moves the average by less than a tenth of a percent because a single layer has only one degree of freedom. The crystalline silicon substrate and the silicon nitride film both travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:Si-Franta',
        referenceWavelength: 4000,
        bands: [[3000,5000]],
        aoi: 0,
        polarization: 'avg',
        preview: [2500,5500],
        layers: [
            { material: 'rii:Si3N4-Kischkat', thickness: 417.80 },
        ],
        materials: embedded('rii:Si-Franta', 'rii:Si3N4-Kischkat'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.10, label: 'R avg ≤ 10%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.16, label: 'R max ≤ 16%' },
        ],
    },
    {
        id: 'ar-mwir-3-5um-ge-mgf2-silicon-4l',
        name: 'MWIR AR 3-5 um on silicon, Ge/MgF2, 4 layers',
        type: 'ar',
        tags: ['mwir', 'broadband', 'thermal-imaging', 'all-dielectric', 'normal-incidence', 'silicon', 'synthesized'],
        use: 'Use this on a silicon window, lens or filter substrate that has to pass the whole 3 to 5 um band with as little loss as possible: a cooled mid-wave camera, a gas sensor, or the front element of a mid-wave objective.',
        limitations: 'Magnesium fluoride is the low index here and is soft; a window that will be wiped in the field wants the harder single-layer silicon nitride design instead. MgF2 also starts to absorb past about 6 um, so nothing is claimed there. Germanium is opaque below about 1.9 um, so this coating says nothing about the visible or the near infrared.',
        source: 'A four-layer Ge/MgF2 AR for 3-5 um on silicon designed in TFStudio. MgF2 is the low index because its index of about 1.35 in this band is far closer to the ideal outermost index for silicon than the 2.26 of ZnS; every thickness was optimized against the specification below. The crystalline silicon substrate and the germanium film travel with the entry as measured data from refractiveindex.info; MgF2 is built in.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:Si-Franta',
        referenceWavelength: 4000,
        bands: [[3000,5000]],
        aoi: 0,
        polarization: 'avg',
        preview: [2500,5500],
        layers: [
            { material: 'rii:Ge-Li', thickness: 498.40 },
            { material: 'builtin:MgF2', thickness: 165.25 },
            { material: 'rii:Ge-Li', thickness: 76.14 },
            { material: 'builtin:MgF2', thickness: 770.97 },
        ],
        materials: embedded('rii:Si-Franta', 'rii:Ge-Li'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.005, label: 'R avg ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.01, label: 'R max ≤ 1%' },
        ],
    },
    {
        id: 'ar-lwir-8-12um-zns-germanium-1l',
        name: 'LWIR AR 8-12 um on germanium, single ZnS layer',
        type: 'ar',
        tags: ['lwir', 'broadband', 'thermal-imaging', 'single-layer', 'quarter-wave', 'all-dielectric', 'normal-incidence', 'germanium'],
        use: 'Use this as the classic one-layer AR on a germanium window or lens for an uncooled thermal camera. Zinc sulphide at about 2.21 is close to the square root of the germanium index, so a single quarter wave takes a bare germanium surface from 36% reflectance to about 1% at the design wavelength.',
        limitations: 'A single layer only meets the quarter-wave condition at 10 um, so reflectance climbs to about 7% at the edges of the 8 to 12 um band. Use the six-layer Ge/ZnS design when the whole band has to be flat. Zinc sulphide is soft and a field window needs a harder overcoat.',
        source: 'An exact quarter wave of ZnS at 10 um on germanium, the textbook single-layer AR of Macleod, Thin-Film Optical Filters, 5th ed., section 4.1. The germanium substrate and the ZnS film travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:Ge-Li',
        referenceWavelength: 10000,
        bands: [[8000,12000]],
        aoi: 0,
        polarization: 'avg',
        preview: [7000,13000],
        layers: [
            { material: 'rii:ZnS-Amotchkina', thickness: 1126.26 },
        ],
        materials: embedded('rii:Ge-Li', 'rii:ZnS-Amotchkina'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.04, label: 'R avg ≤ 4%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.10, label: 'R max ≤ 10%' },
        ],
    },
    {
        id: 'ar-lwir-8-12um-ge-zns-germanium-6l',
        name: 'LWIR AR 8-12 um on germanium, Ge/ZnS, 6 layers',
        type: 'ar',
        tags: ['lwir', 'broadband', 'thermal-imaging', 'ge-zns', 'all-dielectric', 'normal-incidence', 'germanium', 'synthesized'],
        use: 'Use this on the window or the front lens of an uncooled thermal camera when the whole 8 to 12 um band has to come through evenly, not just the middle of it. Six layers of the two standard long-wave materials.',
        limitations: 'Zinc sulphide is the only low index the long-wave band leaves available here and it is still 2.2, well above the ideal outermost index for germanium, so a two-material design cannot go much below one percent average. Reflectance rises to about 4% at the band edges. Both materials are soft; a field window needs a hard overcoat that this design does not include.',
        source: 'A six-layer Ge/ZnS AR for 8-12 um on germanium, designed in TFStudio by differential evolution followed by damped least squares against the specification below. The germanium substrate and film and the ZnS film travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:Ge-Li',
        referenceWavelength: 10000,
        bands: [[8000,12000]],
        aoi: 0,
        polarization: 'avg',
        preview: [7000,13000],
        layers: [
            { material: 'rii:Ge-Li', thickness: 1584.13 },
            { material: 'rii:ZnS-Amotchkina', thickness: 149.84 },
            { material: 'rii:Ge-Li', thickness: 1464.69 },
            { material: 'rii:ZnS-Amotchkina', thickness: 2336.79 },
            { material: 'rii:Ge-Li', thickness: 362.04 },
            { material: 'rii:ZnS-Amotchkina', thickness: 1254.24 },
        ],
        materials: embedded('rii:Ge-Li', 'rii:ZnS-Amotchkina'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.02, label: 'R avg ≤ 2%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.05, label: 'R max ≤ 5%' },
        ],
    },
    {
        id: 'ar-co2-10600-ge-znse-4l',
        name: 'CO2 laser AR at 10.6 um on ZnSe, Ge/ZnSe, 4 layers',
        type: 'ar',
        tags: ['lwir', 'single-wavelength', 'laser', 'all-dielectric', 'normal-incidence', 'znse', 'synthesized'],
        use: 'Use this on the output window, lens or beam-delivery optic of a CO2 laser. Zinc selenide is the standard substrate at 10.6 um and the coating is built from the same material plus germanium, so both layers deposit from familiar sources.',
        limitations: 'The coating is specified at one line. Reflectance rises away from 10.6 um, so this is not a broadband long-wave AR. The stack is 4.4 um of material and each layer has to be monitored on thickness, not on a turning point. Bulk absorption in the ZnSe substrate is not part of a single-surface coating claim and matters at high average power.',
        source: 'A four-layer Ge/ZnSe AR for the 10.6 um CO2 laser line on zinc selenide, every thickness optimized in TFStudio against the specification below. The ZnSe substrate and film and the germanium film travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:ZnSe-Querry',
        referenceWavelength: 10600,
        bands: [[10500,10700]],
        aoi: 0,
        polarization: 'avg',
        preview: [9000,12000],
        layers: [
            { material: 'rii:Ge-Li', thickness: 1230.84 },
            { material: 'rii:ZnSe-Querry', thickness: 1513.42 },
            { material: 'rii:Ge-Li', thickness: 614.36 },
            { material: 'rii:ZnSe-Querry', thickness: 1082.35 },
        ],
        materials: embedded('rii:ZnSe-Querry', 'rii:Ge-Li'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.002, label: 'R avg ≤ 0.2%' },
            { kind: 'R_AT', channel: 'R', lambda: 10600, cmp: 'le', target: 0.002, label: 'R at 10.6 um ≤ 0.2%' },
        ],
    },
    {
        id: 'ar-mwir-3-5um-mgf2-sapphire-1l',
        name: 'MWIR AR 3-5 um on sapphire, single MgF2 layer',
        type: 'ar',
        tags: ['mwir', 'broadband', 'thermal-imaging', 'single-layer', 'quarter-wave', 'all-dielectric', 'normal-incidence', 'sapphire'],
        use: 'Use this on a sapphire window that has to survive rain, sand and pressure and still pass the mid-wave band: a missile dome, an aircraft sensor window, or a high-pressure sight glass. Sapphire has a low enough index that one quarter wave of magnesium fluoride nearly matches it into air.',
        limitations: 'Magnesium fluoride is much softer than the sapphire under it, so the coating, not the window, sets the erosion life. Sapphire itself stops transmitting past about 5 um, which is why the band ends there. Written for normal incidence.',
        source: 'An exact quarter wave of MgF2 at 4 um on the built-in sapphire and magnesium fluoride data, the single-layer AR of Macleod, Thin-Film Optical Filters, 5th ed., section 4.1; it meets the specification below as designed.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:Al2O3',
        referenceWavelength: 4000,
        bands: [[3000,5000]],
        aoi: 0,
        polarization: 'avg',
        preview: [2500,5400],
        layers: [
            { material: 'builtin:MgF2', thickness: 741.38 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.01, label: 'R avg ≤ 1%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.03, label: 'R max ≤ 3%' },
        ],
    },
    {
        id: 'ar-bbar-400-780-nb2o5-sio2-polycarbonate-6l',
        name: 'Broadband AR 400-780 nm on polycarbonate, 0 to 45 degrees, Nb2O5/SiO2, 6 layers',
        type: 'ar',
        tags: ['visible', 'broadband', 'display', 'imaging', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'wide-angle', 'textbook'],
        use: 'Use this on a moulded plastic part that has to stay clear at every viewing angle: a display cover, an instrument window, a camera dome or a lens moulded from polycarbonate. Polycarbonate has a higher index than crown glass, so the bare surface reflects more, and these six layers hold the reflectance down from straight on out to 45 degrees.',
        limitations: 'Written for polycarbonate. On glass or acrylic the same stack leaves a visible colour and has to be redesigned. The fourth layer is 8 nm, thin enough that a small error there shifts the colour of the residual reflection, so the coater has to hold a few tenths of a nanometre. Polycarbonate also softens well below the temperature most oxide processes run at, which is the real constraint on making this part. Reflectance is claimed from 400 nm because the substrate measurement starts there.',
        source: 'OptiLayer sample design "6-layer AR" from the LEC25D15 example (OptiLayer GmbH): six Nb2O5 and SiO2 layers on polycarbonate, designed against a zero-reflectance target over 380-780 nm at 0, 20, 30, 40 and 45 degrees for both polarizations. Re-optimized in TFStudio against the built-in Nb2O5 and SiO2 data and the embedded polycarbonate data, at the same five angles over 400-780 nm, against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:PC-Zhang',
        referenceWavelength: 550,
        bands: [[400, 780]],
        aoi: 0,
        polarization: 'avg',
        layers: [
            { material: 'builtin:Nb2O5', thickness: 18.90 },
            { material: 'builtin:SiO2', thickness: 23.19 },
            { material: 'builtin:Nb2O5', thickness: 79.19 },
            { material: 'builtin:SiO2', thickness: 8.34 },
            { material: 'builtin:Nb2O5', thickness: 29.98 },
            { material: 'builtin:SiO2', thickness: 97.55 },
        ],
        materials: embedded('rii:PC-Zhang'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.005, label: 'R avg at 0 degrees ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.02, label: 'R max at 0 degrees ≤ 2%' },
            { kind: 'R_AVG', channel: 'R', aoi: 45, cmp: 'le', target: 0.015, label: 'R avg at 45 degrees ≤ 1.5%' },
            { kind: 'T_AVG', channel: 'T', cmp: 'ge', target: 0.99, label: 'T avg at 0 degrees ≥ 99%' },
        ],
    },
    {
        id: 'ar-absorbing-400-700-tin-sio2-2l',
        name: 'Absorbing AR 400-700 nm on glass, TiN/SiO2, 2 layers',
        type: 'ar',
        tags: ['visible', 'broadband', 'display', 'metal-dielectric', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this on the front glass of a display, an instrument panel or a shop window where the reflection has to go and some of the transmitted light can be given up to get rid of it. Two layers, a thin metallic titanium nitride film with a silicon dioxide layer over it, take a glass surface under half a percent reflectance right across the visible.',
        limitations: 'The metal layer absorbs: about a sixth of the light is lost in a single pass, so this is not a coating for a lens, a laser window or anything that has to keep its throughput. The metal layer is under 10 nm and its optical constants depend heavily on how it is deposited, so a real run has to be measured before these thicknesses mean anything.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Two Layer Broadband AR": the two-layer light-absorptive antireflector of T. Oyama and Y. Katayama, Asahi Glass Company, Light absorptive antireflector, US Patent 5,691,044 (1997), an outer silicon dioxide layer around 80 nm thick over an inner absorbing layer around 8 nm thick based on titanium nitride, usually doped with tungsten so that it is metallic. Public data for the tungsten-doped film does not exist, so the entry carries the pulsed-DC sputtered titanium nitride of Beliaev and co-workers from refractiveindex.info in its place and both thicknesses were re-optimized in TFStudio over 400-700 nm against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        bands: [[400, 700]],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 800],
        layers: [
            { material: 'rii:TiN-Beliaev', thickness: 6.82 },
            { material: 'builtin:SiO2', thickness: 73.53 },
        ],
        materials: embedded('rii:TiN-Beliaev'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.005, label: 'R avg ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.01, label: 'R max ≤ 1%' },
            { kind: 'T_AVG', channel: 'T', cmp: 'ge', target: 0.8, label: 'T avg ≥ 80%' },
        ],
    },
    {
        id: 'ar-bbar-400-1000-tio2-mgf2-8l',
        name: 'Broadband AR 400-1000 nm, TiO2/MgF2, 8 layers',
        type: 'ar',
        tags: ['visible', 'nir', 'broadband', 'imaging', 'all-dielectric', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this when one part has to work across the visible and the near infrared at once: a camera that also sees an 850 nm illuminator, a spectrometer window, or the optics of an instrument that shares a visible and a diode path. Reflectance stays around a third of a percent over the whole 600 nm span.',
        limitations: 'Magnesium fluoride throughout means high film stress and a soft outer surface; the version of this design with SiO2 in the inner layers is the more rugged part for the same performance. Five of the eight layers are under 30 nm and the one next to the substrate is about 10 nm, so the machine has to hold a few nanometres reliably. The band ends at 1000 nm because that is where the design was optimized, not because of a material limit.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Wideband AR 400-1000nm": an eight-layer MgF2/TiO2 stack from the starting design L .25H .1L 1.5H .1L .25H .25L .25H at a reference wavelength of 510 nm, in which the thick high-index layer near the middle acts as a buffer. Re-optimized in TFStudio over 400-1000 nm against the specification below. The built-in TiO2 data stops at 827 nm and cannot cover this band, so the entry carries the atomic-layer-deposited TiO2 of Siefke and co-workers from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 700,
        bands: [[400, 1000]],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 1060],
        layers: [
            { material: 'rii:TiO2-Siefke', thickness: 9.99 },
            { material: 'builtin:MgF2', thickness: 43.13 },
            { material: 'rii:TiO2-Siefke', thickness: 26.21 },
            { material: 'builtin:MgF2', thickness: 21.12 },
            { material: 'rii:TiO2-Siefke', thickness: 128.12 },
            { material: 'builtin:MgF2', thickness: 23.11 },
            { material: 'rii:TiO2-Siefke', thickness: 20.40 },
            { material: 'builtin:MgF2', thickness: 108.91 },
        ],
        materials: embedded('rii:TiO2-Siefke'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.005, label: 'R avg ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.0075, label: 'R max ≤ 0.75%' },
        ],
    },
    {
        id: 'ar-bbar-400-1000-tio2-sio2-mgf2-8l',
        name: 'Broadband AR 400-1000 nm, TiO2/SiO2 under an MgF2 top layer, 8 layers',
        type: 'ar',
        tags: ['visible', 'nir', 'broadband', 'imaging', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this instead of the all-MgF2 wideband AR when the part will be handled and cleaned. Every layer but the outermost is silicon dioxide, which is hard and low in stress, and only the top layer keeps the low index of magnesium fluoride that the coating needs to finish into air.',
        limitations: 'The outermost layer is still magnesium fluoride and still soft, so this is a more rugged coating than the all-MgF2 version but not a hard one. Five of the eight layers are under 30 nm and the one next to the substrate is under 10 nm, so the machine has to hold a few nanometres reliably. The band ends at 1000 nm because that is where the design was optimized.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Wideband AR 400-1000nm with SiO2": the eight-layer wideband AR with every magnesium fluoride layer except the outermost changed to silicon dioxide and the stack re-refined, which the collection recommends because MgF2 has high stress and limited durability while SiO2 is the more rugged material. Re-optimized in TFStudio over 400-1000 nm against the specification below. The built-in TiO2 data stops at 827 nm and cannot cover this band, so the entry carries the atomic-layer-deposited TiO2 of Siefke and co-workers from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 700,
        bands: [[400, 1000]],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 1060],
        layers: [
            { material: 'rii:TiO2-Siefke', thickness: 8.49 },
            { material: 'builtin:SiO2', thickness: 46.54 },
            { material: 'rii:TiO2-Siefke', thickness: 24.07 },
            { material: 'builtin:SiO2', thickness: 21.91 },
            { material: 'rii:TiO2-Siefke', thickness: 125.35 },
            { material: 'builtin:SiO2', thickness: 24.58 },
            { material: 'rii:TiO2-Siefke', thickness: 19.56 },
            { material: 'builtin:MgF2', thickness: 108.96 },
        ],
        materials: embedded('rii:TiO2-Siefke'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.005, label: 'R avg ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.0075, label: 'R max ≤ 0.75%' },
        ],
    },
    {
        id: 'ar-bbar-400-700-zro2-mgf2-4l',
        name: 'Broadband AR 400-700 nm, ZrO2/MgF2, 4 layers',
        type: 'ar',
        tags: ['visible', 'broadband', 'imaging', 'all-dielectric', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this as a visible AR on crown glass when two materials are all the machine has and the whole 400 to 700 nm band has to stay under one percent. It is the two-material replacement for the quarter-half-quarter coating, so it needs no intermediate-index material.',
        limitations: 'The two layers next to the substrate are 16 and 30 nm, thin enough that the machine has to hold a few nanometres reliably. Magnesium fluoride is soft and needs a hot substrate. Reflectance climbs steeply below 400 nm and past 720 nm, so this is a visible coating and not a red or near-infrared one.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Four Layer AR" (the collection also ships it as "Quarter Half Quarter", the same four layers): the two-material replacement of the quarter-half-quarter coating, in which the intermediate-index layer is rebuilt from the same high and low index materials as the rest of the stack. The collection dates the design to Geffcken in the 1940s and cites A. Thelen, The pioneering contributions of W. Geffcken, in Thin Films on Glass, H. Bach and D. Krause eds., Springer 1997, pp. 227-239. Original optical thicknesses at 510 nm are 0.2517, 0.5335, 0.0823 and 0.0670 of a wave in MgF2 and ZrO2. Re-optimized in TFStudio over 400-700 nm against the specification below, on the built-in MgF2 and BK7 data and the zirconia film data that travels with the entry.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 510,
        bands: [[400, 700]],
        aoi: 0,
        polarization: 'avg',
        preview: [370, 800],
        layers: [
            { material: 'rii:ZrO2-Synowicki', thickness: 16.14 },
            { material: 'builtin:MgF2', thickness: 30.21 },
            { material: 'rii:ZrO2-Synowicki', thickness: 125.62 },
            { material: 'builtin:MgF2', thickness: 93.20 },
        ],
        materials: embedded('rii:ZrO2-Synowicki'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.0025, label: 'R avg ≤ 0.25%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.01, label: 'R max ≤ 1%' },
        ],
    },
    {
        id: 'ar-single-mgf2-glass-1l',
        name: 'Visible AR 400-700 nm on glass, single MgF2 layer',
        type: 'ar',
        tags: ['visible', 'broadband', 'imaging', 'single-layer', 'quarter-wave', 'all-dielectric', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this when a crown glass lens or window needs the cheapest antireflection coating there is. One quarter wave of magnesium fluoride takes a bare glass surface from about 4% reflectance to under 2% right across the visible, from one material and one deposition run.',
        limitations: 'Magnesium fluoride sits at about 1.38, well above the 1.23 a single layer on crown glass would want, so the minimum never reaches zero and the coating cannot do better than about 1.2% at its best wavelength. The film is soft and needs a hot substrate. Reflectance rises either side of the band, and the leftover green minimum is what gives the coating its magenta reflected colour.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "One Layer AR": a single quarter wave of MgF2 at a reference wavelength of 510 nm on crown glass, which the collection calls the coating that represents the greatest volume of production, with reflectance under 2% across the visible and the well-known magenta reflected colour. Re-optimized in TFStudio against the built-in MgF2 and BK7 data over 400-700 nm against the specification below; with one layer there is a single degree of freedom, so refinement barely moves the thickness.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 510,
        bands: [[400, 700]],
        aoi: 0,
        polarization: 'avg',
        preview: [370, 800],
        layers: [
            { material: 'builtin:MgF2', thickness: 91.67 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.015, label: 'R avg ≤ 1.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.02, label: 'R max ≤ 2%' },
        ],
    },
    {
        id: 'ar-wcoat-420-680-zro2-mgf2-2l',
        name: 'W-coat AR 420-680 nm, ZrO2/MgF2, 2 layers',
        type: 'ar',
        tags: ['visible', 'broadband', 'imaging', 'all-dielectric', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this when one extra layer is affordable and the single quarter wave dips too sharply in the green. A half wave of zirconia under the magnesium fluoride quarter wave spreads the minimum across the visible instead of concentrating it at one wavelength.',
        limitations: 'The half-wave broadener only works while the high index stays moderate, and the zirconia film data carried here sits at about 2.16, higher than this design wants, so reflectance climbs quickly outside the band and reaches about 4.5% at 400 nm. Magnesium fluoride is soft and needs a hot substrate. The four-layer version of the same idea is better across the whole visible for two more layers.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "W Coat": Air | MgF2 quarter wave | ZrO2 half wave | Glass at a reference wavelength of 510 nm, described there as the simple modification to the single quarter wave that broadens the antireflection zone and lowers the reflectance in the wings, with the note that a slightly lower index than zirconia would be better still. Re-optimized in TFStudio over 420-680 nm against the specification below, on the built-in MgF2 and BK7 data and the zirconia film data that travels with the entry.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 510,
        bands: [[420, 680]],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 780],
        layers: [
            { material: 'rii:ZrO2-Synowicki', thickness: 118.62 },
            { material: 'builtin:MgF2', thickness: 93.18 },
        ],
        materials: embedded('rii:ZrO2-Synowicki'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'le', target: 0.01, label: 'R avg ≤ 1%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.02, label: 'R max ≤ 2%' },
        ],
    },
];
