// Band-pass filters: single-cavity and multi-cavity narrow band, and
// telecom channel filters. Field reference: ../entryModel.js.
import { embedded } from './materials.js';

export const BANDPASS = [
    {
        id: 'bp-550-tio2-sio2-13l',
        name: 'Narrowband filter at 550 nm, 5 nm wide, TiO2/SiO2, 13 layers',
        type: 'bandpass',
        tags: ['visible', 'narrowband', 'fabry-perot', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'fused-silica', 'imaging'],
        use: 'Use this to pick a narrow slice out of the middle of the visible band, for example to isolate one line of a lamp or to set the wavelength of a simple photometer.',
        limitations: 'Blocking holds only over the reflectance zone of the two mirror stacks, roughly 470-660 nm; outside that the filter opens again, so a real part needs a separate blocker or a coloured glass behind it. The passband moves to shorter wavelengths as the filter is tilted.',
        source: 'The all-dielectric single-cavity filter of Macleod, Thin-Film Optical Filters, 5th ed., section 8.2.2, in the form (HL)^3 2H (LH)^3: two quarter-wave mirror stacks either side of a half-wave high-index cavity. Exact quarter waves at 550 nm on the built-in TiO2 and SiO2 data; the design meets the specification below without refinement.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 550,
        bands: [[547, 553]],
        aoi: 0,
        polarization: 'avg',
        preview: [450, 650],
        layers: [
            { material: 'builtin:TiO2', thickness: 54.64 },
            { material: 'builtin:SiO2', thickness: 94.18 },
            { material: 'builtin:TiO2', thickness: 54.64 },
            { material: 'builtin:SiO2', thickness: 94.18 },
            { material: 'builtin:TiO2', thickness: 54.64 },
            { material: 'builtin:SiO2', thickness: 94.18 },
            { material: 'builtin:TiO2', thickness: 109.28 },
            { material: 'builtin:SiO2', thickness: 94.18 },
            { material: 'builtin:TiO2', thickness: 54.64 },
            { material: 'builtin:SiO2', thickness: 94.18 },
            { material: 'builtin:TiO2', thickness: 54.64 },
            { material: 'builtin:SiO2', thickness: 94.18 },
            { material: 'builtin:TiO2', thickness: 54.64 },
        ],
        spec: [
            { kind: 'T_AT', channel: 'T', lambda: 550, cmp: 'ge', target: 0.90, label: 'T at 550 nm ≥ 90%' },
            { kind: 'CENTRAL_LAMBDA', channel: 'T', direction: 'max', lambdaStart: 530, lambdaEnd: 570, cmp: 'eq', target: 550, tol: 1, label: 'peak at 550 nm ± 1 nm' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 520, lambdaEnd: 580, cmp: 'between', lo: 4, hi: 7, label: 'FWHM 4-7 nm' },
        ],
    },
    {
        id: 'bp-halpha-656-tio2-sio2-21l',
        name: 'H-alpha filter at 656.3 nm, 0.9 nm wide, TiO2/SiO2, 21 layers',
        type: 'bandpass',
        tags: ['visible', 'narrowband', 'astronomy', 'fabry-perot', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'fused-silica'],
        use: 'Use this to isolate the hydrogen-alpha line, in a solar or nebula filter, or as the starting point wherever a sub-nanometre passband is needed in the red.',
        limitations: 'Under a nanometre wide, so it needs a collimated beam and a steady temperature: a few degrees of tilt or a warm oven moves the passband by more than its own width. Blocking holds only inside the reflectance zone of the mirror stacks, about 570-770 nm, and a working solar filter needs a much wider blocker in front of it.',
        source: 'The all-dielectric single-cavity filter of Macleod, Thin-Film Optical Filters, 5th ed., section 8.2.2, in the form (HL)^5 2H (LH)^5. Five quarter-wave pairs each side of a half-wave high-index cavity, exact quarter waves at 656.3 nm on the built-in TiO2 and SiO2 data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 656.3,
        bands: [[655.8, 656.8]],
        aoi: 0,
        polarization: 'avg',
        preview: [600, 720],
        layers: [
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 133.34 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
            { material: 'builtin:SiO2', thickness: 112.66 },
            { material: 'builtin:TiO2', thickness: 66.67 },
        ],
        spec: [
            { kind: 'T_AT', channel: 'T', lambda: 656.3, cmp: 'ge', target: 0.90, label: 'T at 656.3 nm ≥ 90%' },
            { kind: 'CENTRAL_LAMBDA', channel: 'T', direction: 'max', lambdaStart: 646, lambdaEnd: 666, cmp: 'eq', target: 656.3, tol: 0.3, label: 'peak at 656.3 nm ± 0.3 nm' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 640, lambdaEnd: 675, cmp: 'between', lo: 0.6, hi: 1.2, label: 'FWHM 0.6-1.2 nm' },
        ],
    },
    {
        id: 'bp-850-nb2o5-sio2-13l',
        name: 'Bandpass at 850 nm, 15 nm wide, Nb2O5/SiO2, 13 layers',
        type: 'bandpass',
        tags: ['nir', 'narrowband', 'imaging', 'fabry-perot', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'fused-silica'],
        use: 'Use this in front of a machine-vision camera lit by an 850 nm LED array, so the sensor sees the illuminator and not the room. Fifteen nanometres is wide enough to take the spread of an LED and its drift with temperature.',
        limitations: 'Blocking holds only over the reflectance zone of the mirror stacks, roughly 760-960 nm; the filter passes again outside that, so a sensor with visible response needs a separate blocker. The passband moves to shorter wavelengths off axis, which matters behind a wide-angle lens.',
        source: 'The all-dielectric single-cavity filter of Macleod, Thin-Film Optical Filters, 5th ed., section 8.2.2, in the form (HL)^3 2H (LH)^3. Exact quarter waves at 850 nm on the built-in Nb2O5 and SiO2 data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 850,
        bands: [[843, 857]],
        aoi: 0,
        polarization: 'avg',
        preview: [700, 1000],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 93.46 },
            { material: 'builtin:SiO2', thickness: 146.30 },
            { material: 'builtin:Nb2O5', thickness: 93.46 },
            { material: 'builtin:SiO2', thickness: 146.30 },
            { material: 'builtin:Nb2O5', thickness: 93.46 },
            { material: 'builtin:SiO2', thickness: 146.30 },
            { material: 'builtin:Nb2O5', thickness: 186.92 },
            { material: 'builtin:SiO2', thickness: 146.30 },
            { material: 'builtin:Nb2O5', thickness: 93.46 },
            { material: 'builtin:SiO2', thickness: 146.30 },
            { material: 'builtin:Nb2O5', thickness: 93.46 },
            { material: 'builtin:SiO2', thickness: 146.30 },
            { material: 'builtin:Nb2O5', thickness: 93.46 },
        ],
        spec: [
            { kind: 'T_AT', channel: 'T', lambda: 850, cmp: 'ge', target: 0.90, label: 'T at 850 nm ≥ 90%' },
            { kind: 'CENTRAL_LAMBDA', channel: 'T', direction: 'max', lambdaStart: 820, lambdaEnd: 880, cmp: 'eq', target: 850, tol: 1, label: 'peak at 850 nm ± 1 nm' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 800, lambdaEnd: 900, cmp: 'between', lo: 12, hi: 18, label: 'FWHM 12-18 nm' },
        ],
    },
    {
        id: 'bp-905-nb2o5-sio2-17l',
        name: 'Bandpass at 905 nm, 7 nm wide, Nb2O5/SiO2, 17 layers',
        type: 'bandpass',
        tags: ['nir', 'narrowband', 'lidar', 'fabry-perot', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'fused-silica'],
        use: 'Use this in front of a 905 nm lidar or time-of-flight receiver to cut daylight while passing the returned pulse. Seven nanometres covers the laser line and its drift with temperature without letting much sky through.',
        limitations: 'Blocking holds only over the reflectance zone of the mirror stacks, roughly 815-1023 nm; a silicon detector still sees the visible and needs a separate blocker. The passband walks to shorter wavelengths with angle, so a fast receiving lens widens the passband the detector actually sees.',
        source: 'The all-dielectric single-cavity filter of Macleod, Thin-Film Optical Filters, 5th ed., section 8.2.2, in the form (HL)^4 2H (LH)^4. Exact quarter waves at 905 nm on the built-in Nb2O5 and SiO2 data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 905,
        bands: [[902, 908]],
        aoi: 0,
        polarization: 'avg',
        preview: [755, 1055],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 99.80 },
            { material: 'builtin:SiO2', thickness: 155.85 },
            { material: 'builtin:Nb2O5', thickness: 99.80 },
            { material: 'builtin:SiO2', thickness: 155.85 },
            { material: 'builtin:Nb2O5', thickness: 99.80 },
            { material: 'builtin:SiO2', thickness: 155.85 },
            { material: 'builtin:Nb2O5', thickness: 99.80 },
            { material: 'builtin:SiO2', thickness: 155.85 },
            { material: 'builtin:Nb2O5', thickness: 199.60 },
            { material: 'builtin:SiO2', thickness: 155.85 },
            { material: 'builtin:Nb2O5', thickness: 99.80 },
            { material: 'builtin:SiO2', thickness: 155.85 },
            { material: 'builtin:Nb2O5', thickness: 99.80 },
            { material: 'builtin:SiO2', thickness: 155.85 },
            { material: 'builtin:Nb2O5', thickness: 99.80 },
            { material: 'builtin:SiO2', thickness: 155.85 },
            { material: 'builtin:Nb2O5', thickness: 99.80 },
        ],
        spec: [
            { kind: 'T_AT', channel: 'T', lambda: 905, cmp: 'ge', target: 0.90, label: 'T at 905 nm ≥ 90%' },
            { kind: 'CENTRAL_LAMBDA', channel: 'T', direction: 'max', lambdaStart: 880, lambdaEnd: 930, cmp: 'eq', target: 905, tol: 1, label: 'peak at 905 nm ± 1 nm' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 855, lambdaEnd: 955, cmp: 'between', lo: 5, hi: 9, label: 'FWHM 5-9 nm' },
        ],
    },
    {
        id: 'bp-940-nb2o5-sio2-17l',
        name: 'Bandpass at 940 nm, 7 nm wide, Nb2O5/SiO2, 17 layers',
        type: 'bandpass',
        tags: ['nir', 'narrowband', 'lidar', 'fabry-perot', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'fused-silica'],
        use: 'Use this in front of a 940 nm lidar or time-of-flight receiver to cut daylight while passing the returned pulse. Seven nanometres covers the laser line and its drift with temperature without letting much sky through.',
        limitations: 'Blocking holds only over the reflectance zone of the mirror stacks, roughly 846-1062 nm; a silicon detector still sees the visible and needs a separate blocker. The passband walks to shorter wavelengths with angle, so a fast receiving lens widens the passband the detector actually sees.',
        source: 'The all-dielectric single-cavity filter of Macleod, Thin-Film Optical Filters, 5th ed., section 8.2.2, in the form (HL)^4 2H (LH)^4. Exact quarter waves at 940 nm on the built-in Nb2O5 and SiO2 data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 940,
        bands: [[937, 943]],
        aoi: 0,
        polarization: 'avg',
        preview: [790, 1090],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 103.82 },
            { material: 'builtin:SiO2', thickness: 161.94 },
            { material: 'builtin:Nb2O5', thickness: 103.82 },
            { material: 'builtin:SiO2', thickness: 161.94 },
            { material: 'builtin:Nb2O5', thickness: 103.82 },
            { material: 'builtin:SiO2', thickness: 161.94 },
            { material: 'builtin:Nb2O5', thickness: 103.82 },
            { material: 'builtin:SiO2', thickness: 161.94 },
            { material: 'builtin:Nb2O5', thickness: 207.65 },
            { material: 'builtin:SiO2', thickness: 161.94 },
            { material: 'builtin:Nb2O5', thickness: 103.82 },
            { material: 'builtin:SiO2', thickness: 161.94 },
            { material: 'builtin:Nb2O5', thickness: 103.82 },
            { material: 'builtin:SiO2', thickness: 161.94 },
            { material: 'builtin:Nb2O5', thickness: 103.82 },
            { material: 'builtin:SiO2', thickness: 161.94 },
            { material: 'builtin:Nb2O5', thickness: 103.82 },
        ],
        spec: [
            { kind: 'T_AT', channel: 'T', lambda: 940, cmp: 'ge', target: 0.90, label: 'T at 940 nm ≥ 90%' },
            { kind: 'CENTRAL_LAMBDA', channel: 'T', direction: 'max', lambdaStart: 915, lambdaEnd: 965, cmp: 'eq', target: 940, tol: 1, label: 'peak at 940 nm ± 1 nm' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 890, lambdaEnd: 990, cmp: 'between', lo: 5, hi: 9, label: 'FWHM 5-9 nm' },
        ],
    },
    {
        id: 'bp-cwdm-1311-nb2o5-sio2-65l',
        name: 'CWDM channel filter at 1311 nm, Nb2O5/SiO2, 65 layers',
        type: 'bandpass',
        tags: ['nir', 'narrowband', 'telecom', 'cwdm', 'multi-cavity', 'nb2o5-sio2', 'all-dielectric', 'fused-silica'],
        use: 'Use this to add or drop the 1311 nm channel of an ITU-T G.694.2 coarse wavelength grid. Three coupled cavities give the flat top and steep skirts a channel filter needs: the whole 13 nm channel passes at over 99% and the neighbouring channels at 1291 and 1331 nm are down by more than 30 dB.',
        limitations: 'Written for normal incidence in a collimated beam. Tilting the filter, which is how these are trimmed in a multiplexer, moves the passband to shorter wavelengths and is not covered by the claims here. Blocking is claimed only over the two neighbouring channels; a working device needs wideband blocking outside that.',
        source: 'A three-cavity narrowband filter, Macleod, Thin-Film Optical Filters, 5th ed., section 8.3 Multiple-Cavity Filters: three (HL)^5 2H (LH)^5 units coupled by quarter-wave low-index layers. Every thickness was then refined in TFStudio for a flat channel passband and deep neighbouring-channel rejection against the specification below. Channel wavelength from ITU-T G.694.2. The built-in Nb2O5 data stops at 1000 nm, so the two film materials are carried with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1311,
        bands: [[1271, 1291], [1304.5, 1317.5], [1331, 1351]],
        aoi: 0,
        polarization: 'avg',
        preview: [1250, 1380],
        layers: [
            { material: 'rii:Nb2O5-Lemarchand', thickness: 81.42 },
            { material: 'rii:SiO2-Lemarchand', thickness: 139.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 68.50 },
            { material: 'rii:SiO2-Lemarchand', thickness: 213.80 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 151.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 227.81 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 147.74 },
            { material: 'rii:SiO2-Lemarchand', thickness: 224.92 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 147.83 },
            { material: 'rii:SiO2-Lemarchand', thickness: 229.45 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 314.24 },
            { material: 'rii:SiO2-Lemarchand', thickness: 217.78 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 117.36 },
            { material: 'rii:SiO2-Lemarchand', thickness: 206.08 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 124.86 },
            { material: 'rii:SiO2-Lemarchand', thickness: 216.45 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 141.38 },
            { material: 'rii:SiO2-Lemarchand', thickness: 222.75 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 145.55 },
            { material: 'rii:SiO2-Lemarchand', thickness: 222.46 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 144.05 },
            { material: 'rii:SiO2-Lemarchand', thickness: 223.37 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 154.22 },
            { material: 'rii:SiO2-Lemarchand', thickness: 241.10 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 202.45 },
            { material: 'rii:SiO2-Lemarchand', thickness: 271.47 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 219.85 },
            { material: 'rii:SiO2-Lemarchand', thickness: 251.80 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 162.62 },
            { material: 'rii:SiO2-Lemarchand', thickness: 216.57 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 109.94 },
            { material: 'rii:SiO2-Lemarchand', thickness: 192.59 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 231.31 },
            { material: 'rii:SiO2-Lemarchand', thickness: 194.02 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 111.25 },
            { material: 'rii:SiO2-Lemarchand', thickness: 211.30 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 135.61 },
            { material: 'rii:SiO2-Lemarchand', thickness: 222.39 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 151.63 },
            { material: 'rii:SiO2-Lemarchand', thickness: 231.51 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 171.08 },
            { material: 'rii:SiO2-Lemarchand', thickness: 251.11 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 211.48 },
            { material: 'rii:SiO2-Lemarchand', thickness: 265.71 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 200.15 },
            { material: 'rii:SiO2-Lemarchand', thickness: 244.44 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 163.94 },
            { material: 'rii:SiO2-Lemarchand', thickness: 227.29 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 142.79 },
            { material: 'rii:SiO2-Lemarchand', thickness: 218.10 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 128.64 },
            { material: 'rii:SiO2-Lemarchand', thickness: 207.74 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 105.23 },
            { material: 'rii:SiO2-Lemarchand', thickness: 191.99 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 233.68 },
            { material: 'rii:SiO2-Lemarchand', thickness: 197.31 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 132.38 },
            { material: 'rii:SiO2-Lemarchand', thickness: 242.11 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 217.65 },
            { material: 'rii:SiO2-Lemarchand', thickness: 272.69 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 210.87 },
            { material: 'rii:SiO2-Lemarchand', thickness: 247.56 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 157.69 },
            { material: 'rii:SiO2-Lemarchand', thickness: 218.66 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 123.67 },
        ],
        materials: embedded('rii:Nb2O5-Lemarchand', 'rii:SiO2-Lemarchand'),
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min in channel ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.005, label: 'T max over 1271-1291 nm ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 2, target: 0.005, label: 'T max over 1331-1351 nm ≤ 0.5%' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 1260, lambdaEnd: 1360, cmp: 'between', lo: 15, hi: 21, label: 'FWHM 15-21 nm' },
        ],
    },
    {
        id: 'bp-dwdm-1550-nb2o5-sio2-89l',
        name: 'DWDM channel filter at 1550.12 nm, Nb2O5/SiO2, 89 layers',
        type: 'bandpass',
        tags: ['nir', 'narrowband', 'telecom', 'dwdm', 'multi-cavity', 'nb2o5-sio2', 'all-dielectric', 'fused-silica'],
        use: 'Use this as the starting design for a 100 GHz dense wavelength grid channel filter on the ITU-T G.694.1 grid, at 1550.12 nm (193.4 THz). Three coupled cavities give a flat 0.45 nm top at over 99% and skirts that fall two orders of magnitude within a nanometre.',
        limitations: 'The passband is 0.83 nm wide, so the neighbouring 100 GHz channels at 1549.32 and 1550.92 nm sit on the skirt and are only about 20 dB down; a production 100 GHz filter uses more cavities than this and is trimmed by tilt. Nothing is claimed off normal incidence. Twenty micrometres of coating on one side will bow a thin substrate.',
        source: 'A three-cavity narrowband filter, Macleod, Thin-Film Optical Filters, 5th ed., section 8.3 Multiple-Cavity Filters: three (HL)^7 2H (LH)^7 units coupled by quarter-wave low-index layers. Every thickness was then refined in TFStudio for a flat channel passband and steep skirts against the specification below. Channel wavelength from ITU-T G.694.1. The built-in Nb2O5 data stops at 1000 nm, so the two film materials are carried with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1550.12,
        bands: [[1547.5, 1549.3], [1549.9, 1550.35], [1550.95, 1552.7]],
        aoi: 0,
        polarization: 'avg',
        preview: [1546, 1554],
        layers: [
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.42 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.37 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.51 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.72 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.70 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 174.00 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.00 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 171.19 },
            { material: 'rii:SiO2-Lemarchand', thickness: 258.50 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 156.53 },
            { material: 'rii:SiO2-Lemarchand', thickness: 243.89 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 135.70 },
            { material: 'rii:SiO2-Lemarchand', thickness: 249.83 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 377.08 },
            { material: 'rii:SiO2-Lemarchand', thickness: 268.73 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.57 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.16 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.28 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.35 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.34 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.39 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.33 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.39 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.33 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.38 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.33 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.34 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.36 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.27 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.48 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.19 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 348.51 },
            { material: 'rii:SiO2-Lemarchand', thickness: 262.59 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 171.76 },
            { material: 'rii:SiO2-Lemarchand', thickness: 263.34 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 172.70 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.02 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.11 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.27 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.26 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.35 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.30 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.39 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.40 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.39 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.34 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.41 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.40 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.16 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 171.48 },
            { material: 'rii:SiO2-Lemarchand', thickness: 256.24 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 310.07 },
            { material: 'rii:SiO2-Lemarchand', thickness: 273.22 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 214.88 },
            { material: 'rii:SiO2-Lemarchand', thickness: 291.94 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 206.27 },
            { material: 'rii:SiO2-Lemarchand', thickness: 278.32 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 184.32 },
            { material: 'rii:SiO2-Lemarchand', thickness: 268.12 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 175.27 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.86 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.26 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.32 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.20 },
            { material: 'rii:SiO2-Lemarchand', thickness: 264.37 },
            { material: 'rii:Nb2O5-Lemarchand', thickness: 173.31 },
        ],
        materials: embedded('rii:Nb2O5-Lemarchand', 'rii:SiO2-Lemarchand'),
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min in channel ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.015, label: 'T max over 1547.5-1549.3 nm ≤ 1.5%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 2, target: 0.015, label: 'T max over 1550.95-1552.7 nm ≤ 1.5%' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 1545, lambdaEnd: 1555, cmp: 'between', lo: 0.6, hi: 1.1, label: 'FWHM 0.6-1.1 nm' },
        ],
    },
    {
        id: 'bp-532-tio2-sio2-26l',
        name: 'Narrowband filter at 532 nm, 20 nm wide, TiO2/SiO2, 26 layers',
        type: 'bandpass',
        tags: ['visible', 'narrowband', 'laser', 'fluorescence', 'multi-cavity', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'fused-silica', 'textbook'],
        use: 'Use this to pass the 532 nm line and reject everything either side of it: the excitation arm of a fluorescence path, a clean-up filter after a doubled Nd:YAG, or the wavelength-setting filter of a detector. Three coupled cavities give the pass band a flat top, with the half-power points 10 nm either side of the line.',
        limitations: 'Blocking holds over the reflectance zone of the mirror stacks, roughly 470 to 610 nm, and only to about 0.3%, which is optical density 2.5. Outside that zone the filter opens again, so anything that needs deep out-of-band rejection wants a coloured glass or a second blocker behind it. The pass band moves to shorter wavelengths as the filter is tilted, and the flat top means the peak wanders inside the band from unit to unit.',
        source: 'OptiLayer sample design "NBPF" from the LEC13R4 example (OptiLayer GmbH): a 26-layer three-cavity narrow band-pass filter at 532 nm, quarter waves with half-wave and full-wave spacers and a two-layer match on top, produced on a Leybold SYRUSpro 1100 with ion assistance and used there as the subject of a reverse-engineering exercise. Re-optimized in TFStudio against the built-in TiO2 and SiO2 data on a fused silica substrate, against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 532,
        bands: [[480, 508], [527, 537], [560, 600]],
        aoi: 0,
        polarization: 'avg',
        preview: [470, 620],
        layers: [
            { material: 'builtin:TiO2', thickness: 54.34 },
            { material: 'builtin:SiO2', thickness: 90.07 },
            { material: 'builtin:TiO2', thickness: 53.42 },
            { material: 'builtin:SiO2', thickness: 179.66 },
            { material: 'builtin:TiO2', thickness: 53.41 },
            { material: 'builtin:SiO2', thickness: 90.03 },
            { material: 'builtin:TiO2', thickness: 54.17 },
            { material: 'builtin:SiO2', thickness: 90.24 },
            { material: 'builtin:TiO2', thickness: 54.25 },
            { material: 'builtin:SiO2', thickness: 90.14 },
            { material: 'builtin:TiO2', thickness: 53.76 },
            { material: 'builtin:SiO2', thickness: 360.92 },
            { material: 'builtin:TiO2', thickness: 53.76 },
            { material: 'builtin:SiO2', thickness: 90.14 },
            { material: 'builtin:TiO2', thickness: 54.27 },
            { material: 'builtin:SiO2', thickness: 90.26 },
            { material: 'builtin:TiO2', thickness: 54.22 },
            { material: 'builtin:SiO2', thickness: 90.09 },
            { material: 'builtin:TiO2', thickness: 53.58 },
            { material: 'builtin:SiO2', thickness: 179.84 },
            { material: 'builtin:TiO2', thickness: 53.60 },
            { material: 'builtin:SiO2', thickness: 90.13 },
            { material: 'builtin:TiO2', thickness: 54.38 },
            { material: 'builtin:SiO2', thickness: 90.45 },
            { material: 'builtin:TiO2', thickness: 15.10 },
            { material: 'builtin:SiO2', thickness: 124.07 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.98, label: 'T min 527-537 nm ≥ 98%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.005, label: 'T max 480-508 nm ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 2, target: 0.005, label: 'T max 560-600 nm ≤ 0.5%' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 505, lambdaEnd: 560, cmp: 'between', lo: 17, hi: 22, label: 'FWHM 17-22 nm' },
        ],
    },
    {
        id: 'bp-3cavity-1550-ta2o5-sio2-104l',
        name: 'Three-cavity narrowband filter at 1550 nm, Ta2O5/SiO2, 104 layers',
        type: 'bandpass',
        tags: ['nir', 'narrowband', 'telecom', 'dwdm', 'multi-cavity', 'ta2o5-sio2', 'all-dielectric', 'fused-silica', 'textbook'],
        use: 'Use this when a single wavelength has to be picked out of a fibre band and everything within a nanometre of it thrown away. Three coupled cavities give a half-nanometre pass band whose skirts are three orders of magnitude down one nanometre off centre, narrower than a 200 GHz channel filter.',
        limitations: 'The two outer cavities are high index and the middle one is low index and of higher order, which flattens the pass band at normal incidence but makes the filter unsuitable at any appreciable angle: the low-index cavity shifts faster with angle than the high-index ones and the three stop tracking each other. The coating is 25 um of material on one side. Nothing is claimed off normal incidence.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Three Cavity Narrowband Filter": the formula (HL)^8 HH (LH)^8 L (HL)^8 H 6L H(LH)^8 L(HL)^8 HH (LH)^8 L in Ta2O5 and SiO2 at a reference wavelength of 1550 nm, 104 layers, with the two outer cavity layers of high index and the inner one of low index and sixth order to cut the pass band ripple. The collection notes this arrangement is not appropriate for a filter used at an appreciable angle of incidence. Re-optimized in TFStudio against the specification below. The built-in Ta2O5 data carries enough extinction at 1550 nm to cost several percent of the peak through 25 um of coating, so the entry carries the sputtered Ta2O5 of Gao, Lemarchand and Lequime from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1550,
        bands: [[1547, 1549], [1549.85, 1550.15], [1551, 1553]],
        aoi: 0,
        polarization: 'avg',
        preview: [1545, 1555],
        layers: [
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 217.05 },
            { material: 'builtin:SiO2', thickness: 278.95 },
            { material: 'rii:Ta2O5-Gao', thickness: 188.19 },
            { material: 'builtin:SiO2', thickness: 269.66 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.19 },
            { material: 'builtin:SiO2', thickness: 268.62 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.91 },
            { material: 'builtin:SiO2', thickness: 268.44 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.84 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.82 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.81 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.81 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 371.61 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.81 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.81 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.82 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.84 },
            { material: 'builtin:SiO2', thickness: 268.42 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.87 },
            { material: 'builtin:SiO2', thickness: 268.47 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.88 },
            { material: 'builtin:SiO2', thickness: 268.33 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.34 },
            { material: 'builtin:SiO2', thickness: 265.16 },
            { material: 'rii:Ta2O5-Gao', thickness: 177.07 },
            { material: 'builtin:SiO2', thickness: 233.80 },
            { material: 'rii:Ta2O5-Gao', thickness: 159.49 },
            { material: 'builtin:SiO2', thickness: 253.92 },
            { material: 'rii:Ta2O5-Gao', thickness: 183.39 },
            { material: 'builtin:SiO2', thickness: 267.99 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.07 },
            { material: 'builtin:SiO2', thickness: 268.82 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.07 },
            { material: 'builtin:SiO2', thickness: 268.64 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.95 },
            { material: 'builtin:SiO2', thickness: 268.49 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.87 },
            { material: 'builtin:SiO2', thickness: 268.42 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.84 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.82 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.81 },
            { material: 'builtin:SiO2', thickness: 1610.09 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.81 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.82 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.84 },
            { material: 'builtin:SiO2', thickness: 268.42 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.87 },
            { material: 'builtin:SiO2', thickness: 268.49 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.94 },
            { material: 'builtin:SiO2', thickness: 268.60 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.02 },
            { material: 'builtin:SiO2', thickness: 268.70 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.02 },
            { material: 'builtin:SiO2', thickness: 268.50 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.84 },
            { material: 'rii:Ta2O5-Gao', thickness: 187.87 },
            { material: 'builtin:SiO2', thickness: 271.88 },
            { material: 'rii:Ta2O5-Gao', thickness: 187.24 },
            { material: 'builtin:SiO2', thickness: 269.65 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.39 },
            { material: 'builtin:SiO2', thickness: 268.92 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.07 },
            { material: 'builtin:SiO2', thickness: 268.62 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.93 },
            { material: 'builtin:SiO2', thickness: 268.48 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.86 },
            { material: 'builtin:SiO2', thickness: 268.41 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.83 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.82 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.81 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 371.61 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.81 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.82 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.83 },
            { material: 'builtin:SiO2', thickness: 268.41 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.86 },
            { material: 'builtin:SiO2', thickness: 268.46 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.90 },
            { material: 'builtin:SiO2', thickness: 268.49 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 267.66 },
            { material: 'rii:Ta2O5-Gao', thickness: 183.63 },
            { material: 'builtin:SiO2', thickness: 257.12 },
            { material: 'rii:Ta2O5-Gao', thickness: 160.53 },
        ],
        materials: embedded('rii:Ta2O5-Gao'),
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min in pass band ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.001, label: 'T max 1547-1549 nm ≤ 0.1%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 2, target: 0.001, label: 'T max 1551-1553 nm ≤ 0.1%' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 1546, lambdaEnd: 1554, cmp: 'between', lo: 0.3, hi: 0.7, label: 'FWHM 0.3-0.7 nm' },
            { kind: 'T_AT', channel: 'T', lambda: 1550, cmp: 'ge', target: 0.95, label: 'T at 1550 nm ≥ 95%' },
        ],
    },
    {
        id: 'bp-dwdm-200ghz-1550-ta2o5-sio2-150l',
        name: 'DWDM channel filter at 1550 nm with a flat top, 200 GHz grid, Ta2O5/SiO2, 150 layers',
        type: 'bandpass',
        tags: ['nir', 'narrowband', 'telecom', 'dwdm', 'multi-cavity', 'ta2o5-sio2', 'all-dielectric', 'fused-silica', 'textbook'],
        use: 'Use this when a 200 GHz channel has to come through flat rather than rounded, so that a laser drifting a few tenths of a nanometre off centre loses almost nothing. Raising the cavity order towards the middle of the stack is what buys the flat top; it costs 150 layers.',
        limitations: 'The coating is 38 um of material in 150 layers, which is a very long deposition run and enough stress to bow a thin substrate. Nothing is claimed off normal incidence. The flat top is 0.8 nm wide and the skirts take about half a nanometre to fall, so the channel spacing this filter can work on is set by the skirts, not by the width of the top.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Advanced DWDM design": a 200 GHz channel filter that raises the cavity order towards the centre of the stack to flatten the pass band, from H. A. Macleod, Challenges in the design and production of narrow band filters for optical fiber telecommunications, Proc. SPIE 4094, 46-57 (2000). The stack is 150 layers of Ta2O5 and SiO2 at a reference wavelength of 1550 nm. Re-optimized in TFStudio against the specification below. The built-in Ta2O5 data carries enough extinction at 1550 nm to cost several percent of the channel peak through 38 um of coating, so the entry carries the sputtered Ta2O5 of Gao, Lemarchand and Lequime from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1550,
        bands: [[1546.4, 1548.4], [1549.6, 1550.4], [1551.6, 1553.6]],
        aoi: 0,
        polarization: 'avg',
        preview: [1545, 1555],
        layers: [
            { material: 'rii:Ta2O5-Gao', thickness: 182.00 },
            { material: 'builtin:SiO2', thickness: 278.56 },
            { material: 'rii:Ta2O5-Gao', thickness: 198.52 },
            { material: 'builtin:SiO2', thickness: 287.90 },
            { material: 'rii:Ta2O5-Gao', thickness: 197.24 },
            { material: 'builtin:SiO2', thickness: 279.74 },
            { material: 'rii:Ta2O5-Gao', thickness: 190.41 },
            { material: 'builtin:SiO2', thickness: 271.50 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.47 },
            { material: 'builtin:SiO2', thickness: 268.22 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.40 },
            { material: 'builtin:SiO2', thickness: 267.70 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.41 },
            { material: 'builtin:SiO2', thickness: 267.90 },
            { material: 'rii:Ta2O5-Gao', thickness: 371.37 },
            { material: 'builtin:SiO2', thickness: 267.91 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.44 },
            { material: 'builtin:SiO2', thickness: 267.82 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.52 },
            { material: 'builtin:SiO2', thickness: 268.17 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.78 },
            { material: 'builtin:SiO2', thickness: 268.33 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.34 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.64 },
            { material: 'builtin:SiO2', thickness: 269.57 },
            { material: 'rii:Ta2O5-Gao', thickness: 187.22 },
            { material: 'builtin:SiO2', thickness: 259.95 },
            { material: 'rii:Ta2O5-Gao', thickness: 174.06 },
            { material: 'builtin:SiO2', thickness: 254.12 },
            { material: 'rii:Ta2O5-Gao', thickness: 180.90 },
            { material: 'builtin:SiO2', thickness: 267.32 },
            { material: 'rii:Ta2O5-Gao', thickness: 187.10 },
            { material: 'builtin:SiO2', thickness: 271.00 },
            { material: 'rii:Ta2O5-Gao', thickness: 1116.41 },
            { material: 'builtin:SiO2', thickness: 270.15 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.33 },
            { material: 'builtin:SiO2', thickness: 268.41 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.76 },
            { material: 'builtin:SiO2', thickness: 268.37 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.37 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 1858.00 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.37 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.37 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.76 },
            { material: 'builtin:SiO2', thickness: 268.43 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.38 },
            { material: 'builtin:SiO2', thickness: 270.24 },
            { material: 'rii:Ta2O5-Gao', thickness: 1116.48 },
            { material: 'builtin:SiO2', thickness: 271.12 },
            { material: 'rii:Ta2O5-Gao', thickness: 187.18 },
            { material: 'builtin:SiO2', thickness: 267.39 },
            { material: 'rii:Ta2O5-Gao', thickness: 180.85 },
            { material: 'builtin:SiO2', thickness: 253.67 },
            { material: 'rii:Ta2O5-Gao', thickness: 173.24 },
            { material: 'builtin:SiO2', thickness: 258.44 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.99 },
            { material: 'builtin:SiO2', thickness: 269.77 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.62 },
            { material: 'builtin:SiO2', thickness: 268.39 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.36 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.34 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.31 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.76 },
            { material: 'builtin:SiO2', thickness: 268.38 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.06 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.36 },
            { material: 'builtin:SiO2', thickness: 267.56 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.27 },
            { material: 'builtin:SiO2', thickness: 267.71 },
            { material: 'rii:Ta2O5-Gao', thickness: 371.27 },
            { material: 'builtin:SiO2', thickness: 267.69 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.22 },
            { material: 'builtin:SiO2', thickness: 267.37 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.15 },
            { material: 'builtin:SiO2', thickness: 267.87 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.31 },
            { material: 'builtin:SiO2', thickness: 271.50 },
            { material: 'rii:Ta2O5-Gao', thickness: 190.73 },
            { material: 'builtin:SiO2', thickness: 281.18 },
            { material: 'rii:Ta2O5-Gao', thickness: 199.89 },
            { material: 'builtin:SiO2', thickness: 297.51 },
            { material: 'rii:Ta2O5-Gao', thickness: 214.57 },
            { material: 'builtin:SiO2', thickness: 324.81 },
            { material: 'rii:Ta2O5-Gao', thickness: 534.14 },
            { material: 'builtin:SiO2', thickness: 20.00 },
        ],
        materials: embedded('rii:Ta2O5-Gao'),
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min in channel ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.0001, label: 'T max 1546.4-1548.4 nm ≤ 0.01%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 2, target: 0.0001, label: 'T max 1551.6-1553.6 nm ≤ 0.01%' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 1545, lambdaEnd: 1555, cmp: 'between', lo: 1.1, hi: 1.5, label: 'FWHM 1.1-1.5 nm' },
            { kind: 'T_AT', channel: 'T', lambda: 1550, cmp: 'ge', target: 0.95, label: 'T at 1550 nm ≥ 95%' },
        ],
    },
    {
        id: 'bp-dwdm-200ghz-1550-ta2o5-sio2-91l',
        name: 'DWDM channel filter at 1550 nm, 200 GHz grid, Ta2O5/SiO2, 91 layers',
        type: 'bandpass',
        tags: ['nir', 'narrowband', 'telecom', 'dwdm', 'multi-cavity', 'ta2o5-sio2', 'all-dielectric', 'fused-silica', 'textbook'],
        use: 'Use this as the starting design for a 200 GHz channel filter on the dense wavelength grid. Three identical third-order cavities give a one-nanometre channel with the neighbouring channels three orders of magnitude down, and a V-coat matching structure on the outside keeps the pass band from rippling.',
        limitations: 'The pass band is rounded rather than flat: half a nanometre off centre the transmittance has already fallen by a third, so a system that needs a flat top across the channel wants the 150-layer design with mixed cavity orders. The coating is 23 um of material on one side and will bow a thin substrate. Nothing is claimed off normal incidence, and in production a filter like this is tuned onto its channel by tilting it.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Simple DWDM design": a three-cavity filter in which every cavity is an identical third order, with ripple reduction by a simple V-coat matching structure at the outer surface, from H. A. Macleod, Challenges in the design and production of narrow band filters for optical fiber telecommunications, Proc. SPIE 4094, 46-57 (2000). The stack is 91 layers of Ta2O5 and SiO2 at a reference wavelength of 1550 nm. Re-optimized in TFStudio against the specification below. The built-in Ta2O5 data carries enough extinction at 1550 nm to cost several percent of the channel peak through 23 um of coating, so the entry carries the sputtered Ta2O5 of Gao, Lemarchand and Lequime from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1550,
        bands: [[1546.4, 1548.4], [1549.7, 1550.3], [1551.6, 1553.6]],
        aoi: 0,
        polarization: 'avg',
        preview: [1545, 1555],
        layers: [
            { material: 'rii:Ta2O5-Gao', thickness: 116.55 },
            { material: 'builtin:SiO2', thickness: 256.04 },
            { material: 'rii:Ta2O5-Gao', thickness: 184.36 },
            { material: 'builtin:SiO2', thickness: 268.28 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.03 },
            { material: 'builtin:SiO2', thickness: 268.68 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.99 },
            { material: 'builtin:SiO2', thickness: 268.54 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.90 },
            { material: 'builtin:SiO2', thickness: 268.44 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.85 },
            { material: 'builtin:SiO2', thickness: 268.39 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.82 },
            { material: 'builtin:SiO2', thickness: 268.37 },
            { material: 'rii:Ta2O5-Gao', thickness: 1114.82 },
            { material: 'builtin:SiO2', thickness: 268.37 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.82 },
            { material: 'builtin:SiO2', thickness: 268.39 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.85 },
            { material: 'builtin:SiO2', thickness: 268.45 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.90 },
            { material: 'builtin:SiO2', thickness: 268.55 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.01 },
            { material: 'builtin:SiO2', thickness: 268.77 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.22 },
            { material: 'builtin:SiO2', thickness: 269.19 },
            { material: 'rii:Ta2O5-Gao', thickness: 186.64 },
            { material: 'builtin:SiO2', thickness: 270.65 },
            { material: 'rii:Ta2O5-Gao', thickness: 188.17 },
            { material: 'builtin:SiO2', thickness: 268.98 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.76 },
            { material: 'builtin:SiO2', thickness: 268.21 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.72 },
            { material: 'builtin:SiO2', thickness: 268.26 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.76 },
            { material: 'builtin:SiO2', thickness: 268.30 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.78 },
            { material: 'builtin:SiO2', thickness: 268.33 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.34 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.34 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 1114.81 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.34 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.80 },
            { material: 'builtin:SiO2', thickness: 268.34 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.33 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.78 },
            { material: 'builtin:SiO2', thickness: 268.30 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.76 },
            { material: 'builtin:SiO2', thickness: 268.27 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.74 },
            { material: 'builtin:SiO2', thickness: 268.28 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.76 },
            { material: 'builtin:SiO2', thickness: 265.59 },
            { material: 'rii:Ta2O5-Gao', thickness: 188.26 },
            { material: 'builtin:SiO2', thickness: 277.82 },
            { material: 'rii:Ta2O5-Gao', thickness: 188.37 },
            { material: 'builtin:SiO2', thickness: 269.37 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.94 },
            { material: 'builtin:SiO2', thickness: 268.32 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.76 },
            { material: 'builtin:SiO2', thickness: 268.28 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.77 },
            { material: 'builtin:SiO2', thickness: 268.31 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.33 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.34 },
            { material: 'rii:Ta2O5-Gao', thickness: 1114.81 },
            { material: 'builtin:SiO2', thickness: 268.34 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.79 },
            { material: 'builtin:SiO2', thickness: 268.33 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.78 },
            { material: 'builtin:SiO2', thickness: 268.31 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.77 },
            { material: 'builtin:SiO2', thickness: 268.27 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.73 },
            { material: 'builtin:SiO2', thickness: 268.21 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.67 },
            { material: 'builtin:SiO2', thickness: 268.11 },
            { material: 'rii:Ta2O5-Gao', thickness: 185.58 },
            { material: 'builtin:SiO2', thickness: 267.74 },
            { material: 'rii:Ta2O5-Gao', thickness: 181.62 },
            { material: 'rii:Ta2O5-Gao', thickness: 65.96 },
            { material: 'builtin:SiO2', thickness: 304.82 },
        ],
        materials: embedded('rii:Ta2O5-Gao'),
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min in channel ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.002, label: 'T max 1546.4-1548.4 nm ≤ 0.2%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 2, target: 0.002, label: 'T max 1551.6-1553.6 nm ≤ 0.2%' },
            { kind: 'FWHM', channel: 'T', direction: 'max', level: 0.5, lambdaStart: 1545, lambdaEnd: 1555, cmp: 'between', lo: 0.9, hi: 1.2, label: 'FWHM 0.9-1.2 nm' },
            { kind: 'T_AT', channel: 'T', lambda: 1550, cmp: 'ge', target: 0.95, label: 'T at 1550 nm ≥ 95%' },
        ],
    },
];
