// Beamsplitters: neutral splitters and polarizing plates. Field reference: ../entryModel.js.
import { embedded } from './materials.js';

export const BEAMSPLITTERS_AND_POLARIZERS = [
    {
        id: 'bs-5050-532-45-tio2-sio2-3l',
        name: '50:50 beamsplitter at 532 nm, 45 degrees, TiO2/SiO2, 3 layers',
        type: 'beamsplitter',
        tags: ['visible', 'single-wavelength', 'laser', 'partial-reflector', 'all-dielectric', 'tio2-sio2', '45-degree', 'glass'],
        use: 'Use this to split a 532 nm beam into two roughly equal parts on a glass plate at 45 degrees, for example the sampling arm of an interferometer or a power monitor. Three layers, no metal, so nothing is lost to absorption.',
        limitations: 'The split is 50:50 only for unpolarized light. At 45 degrees the coating reflects about two thirds of the s component and one third of the p component, so a polarized beam does not split evenly and the two arms come out with different polarization states. Use a cube or a plate designed for non-polarizing operation if that matters.',
        source: 'The dielectric plate beamsplitter of Macleod, Thin-Film Optical Filters, 5th ed., section 5.2.2 Beam Splitters Using Dielectric Layers, where a high-index quarter wave sets the reflectance and the layers under it flatten and match it; thicknesses optimized in TFStudio on the built-in material data against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 532,
        band: [512, 552],
        aoi: 45,
        polarization: 'avg',
        preview: [450, 650],
        layers: [
            { material: 'builtin:TiO2', thickness: 18.26 },
            { material: 'builtin:SiO2', thickness: 89.77 },
            { material: 'builtin:TiO2', thickness: 64.83 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'between', lo: 0.45, hi: 0.55, label: 'R avg 45-55%' },
            { kind: 'R_AVG', channel: 'R', pol: 's', cmp: 'between', lo: 0.60, hi: 0.72, label: 'Rs avg 60-72%' },
            { kind: 'R_AVG', channel: 'R', pol: 'p', cmp: 'between', lo: 0.28, hi: 0.40, label: 'Rp avg 28-40%' },
            { kind: 'A_AVG', channel: 'A', cmp: 'le', target: 0.002, label: 'A avg ≤ 0.2%' },
        ],
    },
    {
        id: 'bs-5050-1064-45-hfo2-sio2-5l',
        name: '50:50 beamsplitter at 1064 nm, 45 degrees, HfO2/SiO2, 5 layers',
        type: 'beamsplitter',
        tags: ['nir', 'single-wavelength', 'laser', 'partial-reflector', 'all-dielectric', 'hfo2-sio2', '45-degree', 'fused-silica'],
        use: 'Use this to take an even sample off a 1064 nm beam, or to split it between two arms, on a fused silica plate at 45 degrees. HfO2 over SiO2 keeps the damage threshold up and the absorption near zero.',
        limitations: 'The split is 50:50 only for unpolarized light: about two thirds of the s component reflects and about one third of the p component. The coating is around 840 nm of material, so the plate needs a matching AR on its second surface if the transmitted beam must not carry a ghost.',
        source: 'The dielectric plate beamsplitter of Macleod, Thin-Film Optical Filters, 5th ed., section 5.2.2 Beam Splitters Using Dielectric Layers. Five HfO2/SiO2 layers seeded as quarter waves at 1064 nm, then refined in TFStudio at 45 degrees to an even split against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1064,
        band: [1044, 1084],
        aoi: 45,
        polarization: 'avg',
        preview: [900, 1250],
        layers: [
            { material: 'builtin:HfO2', thickness: 146.38 },
            { material: 'builtin:SiO2', thickness: 200.26 },
            { material: 'builtin:HfO2', thickness: 186.38 },
            { material: 'builtin:SiO2', thickness: 250.47 },
            { material: 'builtin:HfO2', thickness: 57.95 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'between', lo: 0.45, hi: 0.55, label: 'R avg 45-55%' },
            { kind: 'R_AVG', channel: 'R', pol: 's', cmp: 'between', lo: 0.62, hi: 0.73, label: 'Rs avg 62-73%' },
            { kind: 'R_AVG', channel: 'R', pol: 'p', cmp: 'between', lo: 0.27, hi: 0.38, label: 'Rp avg 27-38%' },
            { kind: 'A_AVG', channel: 'A', cmp: 'le', target: 0.001, label: 'A avg ≤ 0.1%' },
        ],
    },
    {
        id: 'polarizer-plate-532-56-ta2o5-sio2-21l',
        name: 'Polarizing beamsplitter plate at 532 nm, 56 degrees, Ta2O5/SiO2, 21 layers',
        type: 'polarizer',
        tags: ['visible', 'single-wavelength', 'laser', 'polarizing', 'quarter-wave', 'ta2o5-sio2', 'oblique', 'glass'],
        use: 'Use this to separate the two polarization states of a 532 nm beam on a tilted plate: the s component comes off as a clean reflected beam and the p component goes through. It is the cheap alternative to a polarizing cube when the beam can be tilted.',
        limitations: 'The plate has to sit at 56 degrees; a few degrees off and both the reflectance and the extinction change. The transmitted p beam still carries about 2% reflection loss and is displaced by the plate. Ta2O5 absorbs slightly at 532 nm on the built-in data, which is where the residual absorption in the headline numbers comes from.',
        source: 'The plate polarizer of Macleod, Thin-Film Optical Filters, 5th ed., section 9.4.1 Plate Polarizer: a quarter-wave stack used near the polarizing angle, where the s reflectance of the stack stays high while the p reflectance collapses. Ten Ta2O5/SiO2 pairs plus a final high-index layer, exact quarter waves at 532 nm on the built-in data, used at 56 degrees; the stack meets the specification below as designed and was not refined.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 532,
        band: [529, 535],
        aoi: 56,
        polarization: 's',
        preview: [480, 600],
        layers: [
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Ta2O5', thickness: 61.95 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', pol: 's', cmp: 'ge', target: 0.99, label: 'Rs avg ≥ 99%' },
            { kind: 'T_AVG', channel: 'T', pol: 'p', cmp: 'ge', target: 0.90, label: 'Tp avg ≥ 90%' },
            { kind: 'T_AVG', channel: 'T', pol: 's', cmp: 'le', target: 0.005, label: 'Ts avg ≤ 0.5%' },
        ],
    },
    {
        id: 'harmonic-separator-266-1064-45-zro2-sio2-29l',
        name: 'Nd:YAG harmonic separator, reflects 266 nm and passes 1064 nm at 45 degrees, ZrO2/SiO2, 29 layers',
        type: 'beamsplitter',
        tags: ['uv', 'nir', 'dual-band', 'laser', 'all-dielectric', '45-degree', 'oblique', 'fused-silica'],
        use: 'Use this to split the fourth harmonic of a Nd:YAG laser off the fundamental: the 266 nm beam turns through 90 degrees and the 1064 nm residue goes straight through to a dump. It is the standard way to clean a harmonic output without an absorbing filter.',
        limitations: 'Nothing is claimed between the two lines; the visible is a mess of ripple because the stack is far from a quarter wave there. The zirconia data reports no extinction at 266 nm where a real film absorbs a little, so the ultraviolet reflectance is an upper bound and a real separator will run a little lower. Written for 45 degrees.',
        source: 'A fourteen-pair ZrO2/SiO2 quarter-wave stack referenced to 296 nm so its reflectance zone lands on 266 nm at 45 degrees, with every thickness then refined in TFStudio for high reflectance at 266 nm and high transmittance at 1064 nm against the specification below. Both films travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 296,
        bands: [[261,271],[1044,1084]],
        aoi: 45,
        polarization: 'avg',
        preview: [240,1200],
        layers: [
            { material: 'rii:ZrO2-Synowicki', thickness: 39.18 },
            { material: 'rii:SiO2-Franta', thickness: 45.83 },
            { material: 'rii:ZrO2-Synowicki', thickness: 31.48 },
            { material: 'rii:SiO2-Franta', thickness: 53.58 },
            { material: 'rii:ZrO2-Synowicki', thickness: 25.33 },
            { material: 'rii:SiO2-Franta', thickness: 49.64 },
            { material: 'rii:ZrO2-Synowicki', thickness: 35.35 },
            { material: 'rii:SiO2-Franta', thickness: 42.56 },
            { material: 'rii:ZrO2-Synowicki', thickness: 35.91 },
            { material: 'rii:SiO2-Franta', thickness: 56.71 },
            { material: 'rii:ZrO2-Synowicki', thickness: 18.11 },
            { material: 'rii:SiO2-Franta', thickness: 59.76 },
            { material: 'rii:ZrO2-Synowicki', thickness: 26.79 },
            { material: 'rii:SiO2-Franta', thickness: 38.38 },
            { material: 'rii:ZrO2-Synowicki', thickness: 43.55 },
            { material: 'rii:SiO2-Franta', thickness: 33.47 },
            { material: 'rii:ZrO2-Synowicki', thickness: 30.68 },
            { material: 'rii:SiO2-Franta', thickness: 65.50 },
            { material: 'rii:ZrO2-Synowicki', thickness: 12.00 },
            { material: 'rii:SiO2-Franta', thickness: 67.86 },
            { material: 'rii:ZrO2-Synowicki', thickness: 28.11 },
            { material: 'rii:SiO2-Franta', thickness: 29.34 },
            { material: 'rii:ZrO2-Synowicki', thickness: 54.54 },
            { material: 'rii:SiO2-Franta', thickness: 22.40 },
            { material: 'rii:ZrO2-Synowicki', thickness: 32.27 },
            { material: 'rii:SiO2-Franta', thickness: 74.20 },
            { material: 'rii:ZrO2-Synowicki', thickness: 12.00 },
            { material: 'rii:SiO2-Franta', thickness: 78.02 },
            { material: 'rii:ZrO2-Synowicki', thickness: 28.45 },
        ],
        materials: embedded('rii:ZrO2-Synowicki', 'rii:SiO2-Franta'),
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', band: 0, target: 0.99, label: 'R min at 266 nm ≥ 99%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.98, label: 'T min at 1064 nm ≥ 98%' },
        ],
    },
    {
        id: 'polarizer-plate-1064-56-zro2-sio2-28l',
        name: 'Polarizing beamsplitter plate at 1064 nm, 55.6 degrees, ZrO2/SiO2, 28 layers',
        type: 'polarizer',
        tags: ['nir', 'single-wavelength', 'laser', 'laser-damage', 'polarizing', 'all-dielectric', 'oblique', 'glass', 'textbook'],
        use: 'Use this to split a 1064 nm Nd:YAG beam into its two polarization states on a tilted plate: the s component comes off as a clean reflected beam and the p component goes through with almost nothing lost. It is what goes in front of a Pockels cell, or wherever a cube would take too much energy.',
        limitations: 'The plate has to sit at 55.6 degrees. A degree or two off and the p transmittance drops and the extinction with it, so the mount matters as much as the coating. The stack is 4.7 um of material in 28 layers, thick enough that stress and thickness errors both count, and the transmitted beam is displaced sideways by the plate. Only the 1049-1079 nm window is specified; nothing is claimed outside it.',
        source: 'OptiLayer sample design "28-layer polarizer for 1064 nm" from the LEC25D21 example (OptiLayer GmbH): 28 ZrO2 and SiO2 layers on BK7, designed at 55.6 degrees against a target of zero s transmittance and full p transmittance over 1049-1079 nm. Re-optimized in TFStudio at the same angle against the built-in SiO2 and BK7 data and the embedded zirconia data, against the specification below. The zirconia film travels with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 1064,
        bands: [[1049, 1079]],
        aoi: 55.6,
        polarization: 's',
        layers: [
            { material: 'rii:ZrO2-Synowicki', thickness: 133.92 },
            { material: 'builtin:SiO2', thickness: 200.35 },
            { material: 'rii:ZrO2-Synowicki', thickness: 121.73 },
            { material: 'builtin:SiO2', thickness: 183.75 },
            { material: 'rii:ZrO2-Synowicki', thickness: 112.50 },
            { material: 'builtin:SiO2', thickness: 178.89 },
            { material: 'rii:ZrO2-Synowicki', thickness: 112.81 },
            { material: 'builtin:SiO2', thickness: 185.43 },
            { material: 'rii:ZrO2-Synowicki', thickness: 118.93 },
            { material: 'builtin:SiO2', thickness: 194.89 },
            { material: 'rii:ZrO2-Synowicki', thickness: 125.21 },
            { material: 'builtin:SiO2', thickness: 201.90 },
            { material: 'rii:ZrO2-Synowicki', thickness: 128.85 },
            { material: 'builtin:SiO2', thickness: 204.47 },
            { material: 'rii:ZrO2-Synowicki', thickness: 128.92 },
            { material: 'builtin:SiO2', thickness: 202.09 },
            { material: 'rii:ZrO2-Synowicki', thickness: 125.41 },
            { material: 'builtin:SiO2', thickness: 195.25 },
            { material: 'rii:ZrO2-Synowicki', thickness: 119.21 },
            { material: 'builtin:SiO2', thickness: 185.82 },
            { material: 'rii:ZrO2-Synowicki', thickness: 112.99 },
            { material: 'builtin:SiO2', thickness: 178.97 },
            { material: 'rii:ZrO2-Synowicki', thickness: 112.29 },
            { material: 'builtin:SiO2', thickness: 183.18 },
            { material: 'rii:ZrO2-Synowicki', thickness: 121.13 },
            { material: 'builtin:SiO2', thickness: 199.44 },
            { material: 'rii:ZrO2-Synowicki', thickness: 134.83 },
            { material: 'builtin:SiO2', thickness: 532.77 },
        ],
        materials: embedded('rii:ZrO2-Synowicki'),
        spec: [
            { kind: 'R_AVG', channel: 'R', pol: 's', cmp: 'ge', target: 0.995, label: 'Rs avg ≥ 99.5%' },
            { kind: 'T_AVG', channel: 'T', pol: 'p', cmp: 'ge', target: 0.99, label: 'Tp avg ≥ 99%' },
            { kind: 'T_AVG', channel: 'T', pol: 's', cmp: 'le', target: 0.0025, label: 'Ts avg ≤ 0.25%' },
        ],
    },
    {
        id: 'bs-9010-500-700-tio2-sio2-15l',
        name: '90:10 beamsplitter, 500-700 nm, TiO2/SiO2, 15 layers',
        type: 'beamsplitter',
        tags: ['visible', 'broadband', 'partial-reflector', 'output-coupler', 'neutral', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'fused-silica', 'textbook'],
        use: 'Use this where a beam has to be split nine to one and the split must not change with colour: a pick-off that takes a tenth of the power to a monitor, the output coupler of a broadband source, or the front face of a sampling plate. Reflectance stays within a couple of tenths of a percent of 90% from 500 to 700 nm.',
        limitations: 'Written for normal incidence. Tilt it and the split moves and s and p separate, so this is not the coating for a 45 degree pick-off. Fifteen layers are what hold the flatness, so a systematic thickness error shows up as ripple across the band rather than as one number moving. Outside the band the reflectance falls away quickly: at 480 nm it is already 83%.',
        source: 'OptiLayer sample design "Des" from the LEC03R3 example (OptiLayer GmbH): the theoretical 15-layer TiO2 / SiO2 design of a 90% beamsplitter for 500-700 nm at normal incidence, used in that example as the reference for a reverse-engineering exercise on in-situ broadband monitoring data. Its target is a flat 90% reflectance at every wavelength from 500 to 700 nm. Re-optimized in TFStudio against the built-in TiO2 and SiO2 data on the same target, against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 600,
        bands: [[500, 700]],
        aoi: 0,
        polarization: 'avg',
        layers: [
            { material: 'builtin:TiO2', thickness: 15.00 },
            { material: 'builtin:SiO2', thickness: 27.87 },
            { material: 'builtin:TiO2', thickness: 96.94 },
            { material: 'builtin:SiO2', thickness: 71.35 },
            { material: 'builtin:TiO2', thickness: 15.00 },
            { material: 'builtin:SiO2', thickness: 73.09 },
            { material: 'builtin:TiO2', thickness: 37.55 },
            { material: 'builtin:SiO2', thickness: 175.09 },
            { material: 'builtin:TiO2', thickness: 97.36 },
            { material: 'builtin:SiO2', thickness: 99.60 },
            { material: 'builtin:TiO2', thickness: 55.98 },
            { material: 'builtin:SiO2', thickness: 102.68 },
            { material: 'builtin:TiO2', thickness: 56.51 },
            { material: 'builtin:SiO2', thickness: 102.52 },
            { material: 'builtin:TiO2', thickness: 55.33 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'between', lo: 0.895, hi: 0.905, label: 'R avg 89.5-90.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.89, label: 'R min ≥ 89%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'max', cmp: 'le', target: 0.91, label: 'R max ≤ 91%' },
            { kind: 'A_AVG', channel: 'A', cmp: 'le', target: 0.001, label: 'A avg ≤ 0.1%' },
        ],
    },
    {
        id: 'bs-5050-500-600-45-tio2-al2o3-sio2-8l',
        name: '50:50 beamsplitter 500-600 nm at 45 degrees, TiO2/Al2O3/SiO2, 8 layers',
        type: 'beamsplitter',
        tags: ['visible', 'broadband', 'partial-reflector', 'all-dielectric', '45-degree', 'oblique', 'glass', 'textbook'],
        use: 'Use this to split a broad visible beam roughly in half on a glass plate at 45 degrees when the two polarizations must not come out wildly apart. Eight layers of three ordinary oxides, which is about as cheap as a low-polarization splitter gets.',
        limitations: 'The split is even for unpolarized light but not for each polarization on its own: s reflects about 52% and p about 46%, so the two arms carry different polarization states. A part that has to hold s and p together to a fraction of a percent needs the 39-layer design. Written for 45 degrees in air, and the balance drifts as the plate tilts. The plate needs an AR on its second surface if the transmitted beam must not carry a ghost.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Non-polarizing beam splitter in air": eight layers of SiO2, TiO2 and Al2O3 designed for roughly equal s and p reflectance over 500 to 600 nm at 45 degrees in air, with the collection\'s note that equal polarization performance at oblique incidence is reached far more often with three materials than with two. Original optical thicknesses at 510 nm run from 0.118 to 0.511 of a wave. Re-optimized in TFStudio at 45 degrees against the built-in SiO2, TiO2, Al2O3 and BK7 data and the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        bands: [[500, 600]],
        aoi: 45,
        polarization: 'avg',
        preview: [450, 700],
        layers: [
            { material: 'builtin:SiO2', thickness: 143.46 },
            { material: 'builtin:Al2O3', thickness: 69.44 },
            { material: 'builtin:TiO2', thickness: 55.59 },
            { material: 'builtin:Al2O3', thickness: 84.59 },
            { material: 'builtin:TiO2', thickness: 56.53 },
            { material: 'builtin:Al2O3', thickness: 85.40 },
            { material: 'builtin:TiO2', thickness: 56.44 },
            { material: 'builtin:SiO2', thickness: 107.48 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'between', lo: 0.48, hi: 0.52, label: 'R avg 48-52%' },
            { kind: 'R_AVG', channel: 'R', pol: 's', cmp: 'between', lo: 0.45, hi: 0.55, label: 'Rs avg 45-55%' },
            { kind: 'R_AVG', channel: 'R', pol: 'p', cmp: 'between', lo: 0.45, hi: 0.55, label: 'Rp avg 45-55%' },
            { kind: 'A_AVG', channel: 'A', cmp: 'le', target: 0.001, label: 'A avg ≤ 0.1%' },
        ],
    },
    {
        id: 'bs-5050-525-575-45-tio2-al2o3-mgf2-39l',
        name: 'Non-polarizing 50:50 beamsplitter 525-575 nm at 45 degrees, TiO2/Al2O3/MgF2, 39 layers',
        type: 'beamsplitter',
        tags: ['visible', 'narrowband', 'partial-reflector', 'non-polarizing', 'all-dielectric', '45-degree', 'oblique', 'glass', 'textbook'],
        use: 'Use this when a beam has to be split evenly at 45 degrees in air and the two polarizations have to stay together: an interferometer arm, a common-path imaging split, or any measurement that a polarization-dependent split would bias. Reflectance for s and p sits on 50% to within a tenth of a percentage point across the band.',
        limitations: 'The band is 50 nm wide and the coating is 3.7 um of material in 39 layers, so this is a long deposition run that needs good thickness control. Magnesium fluoride is soft and needs a hot substrate. Written for 45 degrees in air: the s and p curves separate again as the plate tilts away from that angle. Outside 525-575 nm nothing is claimed and the two polarizations diverge quickly.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Non Polarizing Beamsplitter 1": 39 layers of MgF2, Al2O3 and TiO2 giving 50% reflectance at 45 degrees in air for both p and s polarization over 525 to 575 nm. The collection explains the starting design as two ideas together, a high-index quarter wave followed by a low-index quarter wave on the substrate to cut the polarization splitting the glass itself causes, and a repeated symmetrical period above it. Re-optimized in TFStudio at 45 degrees against the built-in MgF2, Al2O3, TiO2 and BK7 data and the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        bands: [[525, 575]],
        aoi: 45,
        polarization: 'avg',
        preview: [460, 660],
        layers: [
            { material: 'builtin:MgF2', thickness: 482.93 },
            { material: 'builtin:TiO2', thickness: 120.97 },
            { material: 'builtin:MgF2', thickness: 129.80 },
            { material: 'builtin:Al2O3', thickness: 127.92 },
            { material: 'builtin:TiO2', thickness: 34.73 },
            { material: 'builtin:Al2O3', thickness: 73.44 },
            { material: 'builtin:MgF2', thickness: 149.90 },
            { material: 'builtin:Al2O3', thickness: 49.17 },
            { material: 'builtin:TiO2', thickness: 57.58 },
            { material: 'builtin:Al2O3', thickness: 39.62 },
            { material: 'builtin:MgF2', thickness: 144.57 },
            { material: 'builtin:Al2O3', thickness: 83.99 },
            { material: 'builtin:TiO2', thickness: 58.87 },
            { material: 'builtin:Al2O3', thickness: 62.94 },
            { material: 'builtin:MgF2', thickness: 143.41 },
            { material: 'builtin:Al2O3', thickness: 67.57 },
            { material: 'builtin:TiO2', thickness: 59.23 },
            { material: 'builtin:Al2O3', thickness: 74.96 },
            { material: 'builtin:MgF2', thickness: 160.39 },
            { material: 'builtin:Al2O3', thickness: 59.17 },
            { material: 'builtin:TiO2', thickness: 56.88 },
            { material: 'builtin:Al2O3', thickness: 182.82 },
            { material: 'builtin:MgF2', thickness: 30.63 },
            { material: 'builtin:Al2O3', thickness: 51.74 },
            { material: 'builtin:TiO2', thickness: 55.29 },
            { material: 'builtin:Al2O3', thickness: 113.36 },
            { material: 'builtin:MgF2', thickness: 56.57 },
            { material: 'builtin:Al2O3', thickness: 107.54 },
            { material: 'builtin:TiO2', thickness: 54.65 },
            { material: 'builtin:Al2O3', thickness: 101.98 },
            { material: 'builtin:MgF2', thickness: 68.12 },
            { material: 'builtin:Al2O3', thickness: 117.64 },
            { material: 'builtin:TiO2', thickness: 56.38 },
            { material: 'builtin:Al2O3', thickness: 81.09 },
            { material: 'builtin:MgF2', thickness: 65.00 },
            { material: 'builtin:Al2O3', thickness: 142.23 },
            { material: 'builtin:TiO2', thickness: 95.94 },
            { material: 'builtin:Al2O3', thickness: 27.59 },
            { material: 'builtin:MgF2', thickness: 55.59 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'between', lo: 0.49, hi: 0.51, label: 'R avg 49-51%' },
            { kind: 'R_AVG', channel: 'R', pol: 's', cmp: 'between', lo: 0.49, hi: 0.51, label: 'Rs avg 49-51%' },
            { kind: 'R_AVG', channel: 'R', pol: 'p', cmp: 'between', lo: 0.49, hi: 0.51, label: 'Rp avg 49-51%' },
            { kind: 'MIN_MAX', channel: 'R', pol: 's', direction: 'max', cmp: 'le', target: 0.52, label: 'Rs max ≤ 52%' },
            { kind: 'MIN_MAX', channel: 'R', pol: 's', direction: 'min', cmp: 'ge', target: 0.48, label: 'Rs min ≥ 48%' },
            { kind: 'MIN_MAX', channel: 'R', pol: 'p', direction: 'max', cmp: 'le', target: 0.52, label: 'Rp max ≤ 52%' },
            { kind: 'MIN_MAX', channel: 'R', pol: 'p', direction: 'min', cmp: 'ge', target: 0.48, label: 'Rp min ≥ 48%' },
        ],
    },
    {
        id: 'bs-5050-cube-525-575-tio2-al2o3-mgf2-37l',
        name: 'Non-polarizing 50:50 cube beamsplitter 525-575 nm, 45 degrees in glass, TiO2/Al2O3/MgF2, 37 layers',
        type: 'beamsplitter',
        tags: ['visible', 'narrowband', 'partial-reflector', 'non-polarizing', 'all-dielectric', '45-degree', 'oblique', 'glass', 'textbook'],
        use: 'Use this as the coating on the diagonal of a cemented glass beamsplitter cube, where the beam meets the coating at 45 degrees inside the glass rather than in air. A cube keeps the two arms square to each other and adds no beam displacement, which is why it is the usual choice for a mounted splitter.',
        limitations: 'The coating only works immersed: both sides of it must be the same glass, so this entry says nothing about the same stack on a plate in air. Eight of the 37 layers come out at the 25 nm floor the refinement was given, which says the structure carries more layers than it needs on this material data; a production version would drop them. Magnesium fluoride is soft, and the cement in a real cube limits the power the part can take.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Non Polarizing Cube Beamsplitter": 37 layers of MgF2, Al2O3 and TiO2 on the diagonal of a glass cube, 50% reflectance for both polarizations over 525 to 575 nm at 45 degrees in glass. The collection notes that three materials are usually much better than two at oblique incidence, and that an immersed coating converges far more easily than the same design at 45 degrees in air. Re-optimized in TFStudio at 45 degrees in glass against the built-in MgF2, Al2O3, TiO2 and BK7 data and the specification below.',
        incidentMedium: 'builtin:BK7',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        bands: [[525, 575]],
        aoi: 45,
        polarization: 'avg',
        preview: [460, 660],
        layers: [
            { material: 'builtin:MgF2', thickness: 37.02 },
            { material: 'builtin:TiO2', thickness: 116.23 },
            { material: 'builtin:Al2O3', thickness: 25.00 },
            { material: 'builtin:MgF2', thickness: 111.85 },
            { material: 'builtin:Al2O3', thickness: 57.61 },
            { material: 'builtin:MgF2', thickness: 25.00 },
            { material: 'builtin:Al2O3', thickness: 128.44 },
            { material: 'builtin:TiO2', thickness: 116.12 },
            { material: 'builtin:MgF2', thickness: 54.34 },
            { material: 'builtin:TiO2', thickness: 25.00 },
            { material: 'builtin:MgF2', thickness: 25.00 },
            { material: 'builtin:Al2O3', thickness: 89.75 },
            { material: 'builtin:TiO2', thickness: 25.00 },
            { material: 'builtin:MgF2', thickness: 25.00 },
            { material: 'builtin:TiO2', thickness: 67.64 },
            { material: 'builtin:Al2O3', thickness: 139.42 },
            { material: 'builtin:TiO2', thickness: 68.12 },
            { material: 'builtin:Al2O3', thickness: 46.97 },
            { material: 'builtin:MgF2', thickness: 263.83 },
            { material: 'builtin:Al2O3', thickness: 80.40 },
            { material: 'builtin:TiO2', thickness: 63.18 },
            { material: 'builtin:Al2O3', thickness: 90.43 },
            { material: 'builtin:MgF2', thickness: 189.81 },
            { material: 'builtin:Al2O3', thickness: 77.21 },
            { material: 'builtin:TiO2', thickness: 61.98 },
            { material: 'builtin:Al2O3', thickness: 108.34 },
            { material: 'builtin:MgF2', thickness: 176.41 },
            { material: 'builtin:Al2O3', thickness: 72.09 },
            { material: 'builtin:TiO2', thickness: 32.04 },
            { material: 'builtin:MgF2', thickness: 25.00 },
            { material: 'builtin:TiO2', thickness: 25.00 },
            { material: 'builtin:Al2O3', thickness: 88.24 },
            { material: 'builtin:TiO2', thickness: 58.09 },
            { material: 'builtin:Al2O3', thickness: 90.49 },
            { material: 'builtin:TiO2', thickness: 132.16 },
            { material: 'builtin:MgF2', thickness: 62.92 },
            { material: 'builtin:TiO2', thickness: 123.61 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'between', lo: 0.49, hi: 0.51, label: 'R avg 49-51%' },
            { kind: 'R_AVG', channel: 'R', pol: 's', cmp: 'between', lo: 0.49, hi: 0.51, label: 'Rs avg 49-51%' },
            { kind: 'R_AVG', channel: 'R', pol: 'p', cmp: 'between', lo: 0.49, hi: 0.51, label: 'Rp avg 49-51%' },
            { kind: 'MIN_MAX', channel: 'R', pol: 's', direction: 'max', cmp: 'le', target: 0.52, label: 'Rs max ≤ 52%' },
            { kind: 'MIN_MAX', channel: 'R', pol: 's', direction: 'min', cmp: 'ge', target: 0.48, label: 'Rs min ≥ 48%' },
            { kind: 'MIN_MAX', channel: 'R', pol: 'p', direction: 'max', cmp: 'le', target: 0.52, label: 'Rp max ≤ 52%' },
            { kind: 'MIN_MAX', channel: 'R', pol: 'p', direction: 'min', cmp: 'ge', target: 0.48, label: 'Rp min ≥ 48%' },
        ],
    },
    {
        id: 'polarizer-cube-macneille-400-700-hfo2-sio2-27l',
        name: 'MacNeille polarizing cube 400-700 nm, HfO2/SiO2 in F2 glass, 27 layers',
        type: 'polarizer',
        tags: ['visible', 'broadband', 'polarizing', 'all-dielectric', 'hfo2-sio2', '45-degree', 'oblique', 'glass', 'textbook'],
        use: 'Use this as the coating on the diagonal of a polarizing beamsplitter cube. The s component comes off the diagonal as a clean reflected beam and the p component goes straight through, and unlike a tilted plate it holds across the whole visible band rather than at one wavelength.',
        limitations: 'The cube glass has to be F2 or an index very close to it: the design only works while the p admittances of the two film materials match at 45 degrees inside that glass, so the same stack in BK7 is not a polarizer. The entry describes the coating on the diagonal alone; the four cube faces need their own antireflection coating and the cement sets the power the cube can take. Extinction is limited by the p reflectance, which does not fall to zero at the ends of the band.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Cube polarizer": 27 layers of HfO2 and SiO2 on the diagonal of an F2 glass cube at 45 degrees, built on the MacNeille Brewster-angle polarizer of S. M. MacNeille, Eastman Kodak Company, Beam splitter, US Patent 2,403,731 (1946). The MacNeille condition asks that the angle of incidence sit close to the Brewster angle between the high and low index materials, which is to say that their p admittances are equal at that angle. Original layer thicknesses are physical, 58 to 287 nm. Re-optimized in TFStudio at 45 degrees against the built-in HfO2 and SiO2 data and the specification below; the F2 glass travels with the entry as data from refractiveindex.info.',
        incidentMedium: 'rii:F2-Schott',
        substrate: 'rii:F2-Schott',
        referenceWavelength: 600,
        bands: [[400, 700]],
        aoi: 45,
        polarization: 's',
        preview: [400, 750],
        layers: [
            { material: 'builtin:SiO2', thickness: 111.47 },
            { material: 'builtin:HfO2', thickness: 99.04 },
            { material: 'builtin:SiO2', thickness: 234.87 },
            { material: 'builtin:HfO2', thickness: 102.91 },
            { material: 'builtin:SiO2', thickness: 218.57 },
            { material: 'builtin:HfO2', thickness: 117.60 },
            { material: 'builtin:SiO2', thickness: 182.39 },
            { material: 'builtin:HfO2', thickness: 121.84 },
            { material: 'builtin:SiO2', thickness: 176.88 },
            { material: 'builtin:HfO2', thickness: 73.26 },
            { material: 'builtin:SiO2', thickness: 278.87 },
            { material: 'builtin:HfO2', thickness: 58.42 },
            { material: 'builtin:SiO2', thickness: 112.53 },
            { material: 'builtin:HfO2', thickness: 57.90 },
            { material: 'builtin:SiO2', thickness: 286.02 },
            { material: 'builtin:HfO2', thickness: 72.34 },
            { material: 'builtin:SiO2', thickness: 148.60 },
            { material: 'builtin:HfO2', thickness: 75.54 },
            { material: 'builtin:SiO2', thickness: 148.01 },
            { material: 'builtin:HfO2', thickness: 72.54 },
            { material: 'builtin:SiO2', thickness: 142.29 },
            { material: 'builtin:HfO2', thickness: 62.91 },
            { material: 'builtin:SiO2', thickness: 131.17 },
            { material: 'builtin:HfO2', thickness: 64.74 },
            { material: 'builtin:SiO2', thickness: 144.77 },
            { material: 'builtin:HfO2', thickness: 70.09 },
            { material: 'builtin:SiO2', thickness: 147.28 },
        ],
        materials: embedded('rii:F2-Schott'),
        spec: [
            { kind: 'R_AVG', channel: 'R', pol: 's', cmp: 'ge', target: 0.99, label: 'Rs avg ≥ 99%' },
            { kind: 'T_AVG', channel: 'T', pol: 'p', cmp: 'ge', target: 0.95, label: 'Tp avg ≥ 95%' },
            { kind: 'T_AVG', channel: 'T', pol: 's', cmp: 'le', target: 0.01, label: 'Ts avg ≤ 1%' },
            { kind: 'MIN_MAX', channel: 'T', pol: 's', direction: 'max', cmp: 'le', target: 0.02, label: 'Ts max ≤ 2%' },
        ],
    },
];
