// Chirped and dispersive mirrors. Field reference: ../entryModel.js.
import { embedded } from './materials.js';

export const CHIRPED = [
    {
        id: 'chirped-mirror-750-900-tio2-sio2-27l',
        name: 'Chirped mirror 750-900 nm, TiO2/SiO2, 27 layers',
        type: 'chirped',
        tags: ['nir', 'broadband', 'laser', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this in a Ti:sapphire cavity or a compressor around 800 nm. The dispersion sits near -30 fs2 across the band and varies by about 7 fs2 end to end. The band is half as wide again as the 1000 nm design, which is what the extra seven layers buy.',
        limitations: 'The dispersion holds over 750 to 900 nm and nowhere else. A 150 nm band from a 27-layer stack leaves ripple on the group delay, about 7 fs2 peak to peak, which a compressor with several bounces will accumulate. The dispersion is not part of the checked specification below, which states reflectance only.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Chirped Reflector 2": a 27-layer TiO2/SiO2 mirror with high reflectance and a group-delay dispersion of -30 fs2 over 750 to 900 nm, synthesized in the collection the same way as its 950 to 1050 nm counterpart, from a starting design of two zero-thickness layers. Re-optimized in TFStudio for high reflectance and a flat -30 fs2 group-delay dispersion across the band, against the built-in SiO2 and BK7 data and the reflectance specification below. The built-in TiO2 data stops at 827 nm and cannot cover this band, so the entry carries the atomic-layer-deposited TiO2 of Siefke and co-workers from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 700,
        bands: [[750, 900]],
        aoi: 0,
        polarization: 'avg',
        preview: [700, 980],
        layers: [
            { material: 'rii:TiO2-Siefke', thickness: 113.15 },
            { material: 'builtin:SiO2', thickness: 147.34 },
            { material: 'rii:TiO2-Siefke', thickness: 89.65 },
            { material: 'builtin:SiO2', thickness: 177.73 },
            { material: 'rii:TiO2-Siefke', thickness: 103.29 },
            { material: 'builtin:SiO2', thickness: 146.04 },
            { material: 'rii:TiO2-Siefke', thickness: 87.38 },
            { material: 'builtin:SiO2', thickness: 133.29 },
            { material: 'rii:TiO2-Siefke', thickness: 104.04 },
            { material: 'builtin:SiO2', thickness: 138.37 },
            { material: 'rii:TiO2-Siefke', thickness: 79.13 },
            { material: 'builtin:SiO2', thickness: 128.52 },
            { material: 'rii:TiO2-Siefke', thickness: 76.56 },
            { material: 'builtin:SiO2', thickness: 130.04 },
            { material: 'rii:TiO2-Siefke', thickness: 77.35 },
            { material: 'builtin:SiO2', thickness: 131.33 },
            { material: 'rii:TiO2-Siefke', thickness: 101.54 },
            { material: 'builtin:SiO2', thickness: 133.48 },
            { material: 'rii:TiO2-Siefke', thickness: 81.28 },
            { material: 'builtin:SiO2', thickness: 137.42 },
            { material: 'rii:TiO2-Siefke', thickness: 63.54 },
            { material: 'builtin:SiO2', thickness: 93.25 },
            { material: 'rii:TiO2-Siefke', thickness: 66.56 },
            { material: 'builtin:SiO2', thickness: 99.00 },
            { material: 'rii:TiO2-Siefke', thickness: 89.67 },
            { material: 'builtin:SiO2', thickness: 115.39 },
            { material: 'rii:TiO2-Siefke', thickness: 13.83 },
        ],
        materials: embedded('rii:TiO2-Siefke'),
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.99, label: 'R min ≥ 99%' },
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.99, label: 'R avg ≥ 99%' },
        ],
    },
    {
        id: 'chirped-mirror-950-1050-tio2-sio2-20l',
        name: 'Chirped mirror 950-1050 nm, TiO2/SiO2, 20 layers',
        type: 'chirped',
        tags: ['nir', 'broadband', 'laser', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this inside a femtosecond oscillator or a pulse compressor working around 1000 nm, where every bounce has to add a set amount of negative group-delay dispersion as well as reflect. The dispersion sits near -30 fs2 across the band and varies by about 6 fs2 end to end. Twenty layers, so it is a short run compared with a broadband double-chirped mirror.',
        limitations: 'The dispersion holds over 950 to 1050 nm and nowhere else; outside that the layer thicknesses no longer chirp with wavelength and both the reflectance and the group delay fall apart. Reflectance is high but not a laser high reflector, so a cavity that needs 99.9% wants more pairs. The dispersion is not part of the checked specification below, which states reflectance only.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Chirped Reflector 1": a 20-layer TiO2/SiO2 mirror with high reflectance and a group-delay dispersion of -30 fs2 over 950 to 1050 nm, which the collection synthesized from a starting design of one pair of zero-thickness TiO2 and SiO2 layers. Re-optimized in TFStudio for high reflectance and a flat -30 fs2 group-delay dispersion across the band, against the built-in SiO2 and BK7 data and the reflectance specification below. The built-in TiO2 data stops at 827 nm and cannot cover this band, so the entry carries the atomic-layer-deposited TiO2 of Siefke and co-workers from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 1000,
        bands: [[950, 1050]],
        aoi: 0,
        polarization: 'avg',
        preview: [880, 1120],
        layers: [
            { material: 'builtin:SiO2', thickness: 177.00 },
            { material: 'rii:TiO2-Siefke', thickness: 110.91 },
            { material: 'builtin:SiO2', thickness: 176.94 },
            { material: 'rii:TiO2-Siefke', thickness: 110.68 },
            { material: 'builtin:SiO2', thickness: 174.34 },
            { material: 'rii:TiO2-Siefke', thickness: 113.63 },
            { material: 'builtin:SiO2', thickness: 171.31 },
            { material: 'rii:TiO2-Siefke', thickness: 115.37 },
            { material: 'builtin:SiO2', thickness: 168.38 },
            { material: 'rii:TiO2-Siefke', thickness: 97.67 },
            { material: 'builtin:SiO2', thickness: 152.00 },
            { material: 'rii:TiO2-Siefke', thickness: 102.82 },
            { material: 'builtin:SiO2', thickness: 158.85 },
            { material: 'rii:TiO2-Siefke', thickness: 91.74 },
            { material: 'builtin:SiO2', thickness: 145.41 },
            { material: 'rii:TiO2-Siefke', thickness: 99.33 },
            { material: 'builtin:SiO2', thickness: 174.23 },
            { material: 'rii:TiO2-Siefke', thickness: 113.94 },
            { material: 'builtin:SiO2', thickness: 97.23 },
            { material: 'rii:TiO2-Siefke', thickness: 36.28 },
        ],
        materials: embedded('rii:TiO2-Siefke'),
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.99, label: 'R min ≥ 99%' },
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.99, label: 'R avg ≥ 99%' },
        ],
    },
];
