// Cold mirrors and hot mirrors. Field reference: ../entryModel.js.
export const DICHROICS = [
    {
        id: 'hot-mirror-vis-pass-nir-reject-nb2o5-sio2-18l',
        name: 'Hot mirror, passes 420-680 nm and reflects 750-980 nm, Nb2O5/SiO2, 18 layers',
        type: 'dichroic',
        tags: ['visible', 'nir', 'imaging', 'hot-mirror', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'glass'],
        use: 'Use this in front of a sensor or a specimen that must receive the visible light of a lamp but none of its near infrared, for example the exit window of an illuminator or the cover glass of a colour camera that would otherwise see beyond 700 nm.',
        limitations: 'The rejection band is claimed over 750-980 nm only; the built-in Nb2O5 data stops at 1000 nm, so nothing is claimed deeper into the infrared and a real lamp filter would need a second stack there. Visible transmission dips to about 87% around 690 nm, at the foot of the reflectance band.',
        source: 'The symmetrical-period stack of Macleod, Thin-Film Optical Filters, 5th ed., section 7.2.4 Application to Edge Filters, Air | (0.5L H 0.5L)^9 | Glass, with its reference wavelength set to 860 nm so the reflectance zone covers the near infrared band. Every thickness was then refined in TFStudio for flat visible transmission and deep near-infrared rejection against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 860,
        bands: [[420, 680], [750, 980]],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 1000],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 100.86 },
            { material: 'builtin:SiO2', thickness: 158.96 },
            { material: 'builtin:Nb2O5', thickness: 88.28 },
            { material: 'builtin:SiO2', thickness: 150.94 },
            { material: 'builtin:Nb2O5', thickness: 88.21 },
            { material: 'builtin:SiO2', thickness: 150.27 },
            { material: 'builtin:Nb2O5', thickness: 89.74 },
            { material: 'builtin:SiO2', thickness: 150.84 },
            { material: 'builtin:Nb2O5', thickness: 90.90 },
            { material: 'builtin:SiO2', thickness: 150.40 },
            { material: 'builtin:Nb2O5', thickness: 90.40 },
            { material: 'builtin:SiO2', thickness: 149.20 },
            { material: 'builtin:Nb2O5', thickness: 89.35 },
            { material: 'builtin:SiO2', thickness: 149.34 },
            { material: 'builtin:Nb2O5', thickness: 89.71 },
            { material: 'builtin:SiO2', thickness: 154.23 },
            { material: 'builtin:Nb2O5', thickness: 89.25 },
            { material: 'builtin:SiO2', thickness: 75.49 },
        ],
        spec: [
            { kind: 'T_AVG', channel: 'T', cmp: 'ge', band: 0, target: 0.95, label: 'T avg 420-680 nm ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 0, target: 0.90, label: 'T min 420-680 nm ≥ 90%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'R min 750-980 nm ≥ 95%' },
        ],
    },
    {
        id: 'cold-mirror-vis-reflect-nir-pass-nb2o5-sio2-29l',
        name: 'Cold mirror, reflects 420-680 nm and passes 750-980 nm, Nb2O5/SiO2, 29 layers',
        type: 'dichroic',
        tags: ['visible', 'nir', 'imaging', 'cold-mirror', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'glass'],
        use: 'Use this as the reflector behind a lamp when the visible light must go forward and the heat must go out the back, or anywhere a beam has to be split into a visible arm and a near-infrared arm without a metal mirror in the path.',
        limitations: 'Written for normal incidence. At 45 degrees, the usual mounting for a lamp reflector, both bands shift to shorter wavelengths and the design has to be re-optimized at that angle. The transmission band is claimed to 980 nm because the built-in Nb2O5 data stops at 1000 nm.',
        source: 'Two quarter-wave stacks at different reference wavelengths, the extended-reflectance-zone construction of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2.1 (after Turner and Baumeister): seven Nb2O5/SiO2 pairs at 650 nm next to the substrate and seven at 465 nm above them. Every thickness was then refined in TFStudio for high visible reflectance and high near-infrared transmittance against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        bands: [[420, 680], [750, 980]],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 1000],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 50.92 },
            { material: 'builtin:SiO2', thickness: 64.72 },
            { material: 'builtin:Nb2O5', thickness: 72.41 },
            { material: 'builtin:SiO2', thickness: 125.43 },
            { material: 'builtin:Nb2O5', thickness: 52.38 },
            { material: 'builtin:SiO2', thickness: 99.31 },
            { material: 'builtin:Nb2O5', thickness: 67.01 },
            { material: 'builtin:SiO2', thickness: 116.33 },
            { material: 'builtin:Nb2O5', thickness: 64.02 },
            { material: 'builtin:SiO2', thickness: 99.65 },
            { material: 'builtin:Nb2O5', thickness: 61.71 },
            { material: 'builtin:SiO2', thickness: 110.82 },
            { material: 'builtin:Nb2O5', thickness: 68.17 },
            { material: 'builtin:SiO2', thickness: 98.29 },
            { material: 'builtin:Nb2O5', thickness: 53.93 },
            { material: 'builtin:SiO2', thickness: 89.93 },
            { material: 'builtin:Nb2O5', thickness: 49.52 },
            { material: 'builtin:SiO2', thickness: 54.62 },
            { material: 'builtin:Nb2O5', thickness: 45.18 },
            { material: 'builtin:SiO2', thickness: 93.09 },
            { material: 'builtin:Nb2O5', thickness: 53.70 },
            { material: 'builtin:SiO2', thickness: 83.32 },
            { material: 'builtin:Nb2O5', thickness: 49.33 },
            { material: 'builtin:SiO2', thickness: 86.47 },
            { material: 'builtin:Nb2O5', thickness: 36.20 },
            { material: 'builtin:SiO2', thickness: 68.08 },
            { material: 'builtin:Nb2O5', thickness: 59.84 },
            { material: 'builtin:SiO2', thickness: 119.92 },
            { material: 'builtin:Nb2O5', thickness: 15.40 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', band: 0, target: 0.95, label: 'R min 420-680 nm ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min 750-980 nm ≥ 95%' },
        ],
    },
    {
        id: 'dichroic-498-longpass-45-tio2-sio2-25l',
        name: 'Long-pass dichroic at 45 degrees, 498 nm edge, TiO2/SiO2, 25 layers',
        type: 'dichroic',
        tags: ['visible', 'fluorescence', 'long-pass', 'all-dielectric', 'tio2-sio2', '45-degree', 'oblique', 'glass'],
        use: 'Use this as the beam-splitting mirror of a fluorescence microscope or a two-colour imaging arm: it turns blue excitation light through 90 degrees and lets the longer-wavelength emission through to the detector.',
        limitations: 'At 45 degrees s and p behave differently, which widens the transition: the edge takes about 25 nm to go from reflection to transmission, so the excitation and emission bands must be kept clear of it. Transmission is claimed to 560 nm only; above about 580 nm the next reflectance zone of the stack closes the pass band again.',
        source: 'The symmetrical-period long-pass filter of Macleod, Thin-Film Optical Filters, 5th ed., section 7.2.4, tilted to 45 degrees as described in section 9.5.1 Edge Filters at Intermediate Angle of Incidence. Twelve TiO2/SiO2 periods at a reference wavelength of 520 nm, every thickness then refined in TFStudio at 45 degrees against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 520,
        bands: [[450, 480], [515, 560]],
        aoi: 45,
        polarization: 'avg',
        preview: [400, 650],
        layers: [
            { material: 'builtin:TiO2', thickness: 19.31 },
            { material: 'builtin:SiO2', thickness: 85.59 },
            { material: 'builtin:TiO2', thickness: 44.68 },
            { material: 'builtin:SiO2', thickness: 82.59 },
            { material: 'builtin:TiO2', thickness: 24.93 },
            { material: 'builtin:SiO2', thickness: 80.90 },
            { material: 'builtin:TiO2', thickness: 47.41 },
            { material: 'builtin:SiO2', thickness: 90.90 },
            { material: 'builtin:TiO2', thickness: 62.02 },
            { material: 'builtin:SiO2', thickness: 84.01 },
            { material: 'builtin:TiO2', thickness: 15.00 },
            { material: 'builtin:SiO2', thickness: 81.40 },
            { material: 'builtin:TiO2', thickness: 56.08 },
            { material: 'builtin:SiO2', thickness: 93.96 },
            { material: 'builtin:TiO2', thickness: 63.07 },
            { material: 'builtin:SiO2', thickness: 83.99 },
            { material: 'builtin:TiO2', thickness: 20.24 },
            { material: 'builtin:SiO2', thickness: 79.20 },
            { material: 'builtin:TiO2', thickness: 44.64 },
            { material: 'builtin:SiO2', thickness: 90.12 },
            { material: 'builtin:TiO2', thickness: 51.93 },
            { material: 'builtin:SiO2', thickness: 82.48 },
            { material: 'builtin:TiO2', thickness: 29.35 },
            { material: 'builtin:SiO2', thickness: 79.74 },
            { material: 'builtin:TiO2', thickness: 25.93 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', band: 0, target: 0.95, label: 'R min 450-480 nm ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.90, label: 'T min 515-560 nm ≥ 90%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 440, lambdaEnd: 600, cmp: 'between', lo: 490, hi: 510, label: '50% edge 490-510 nm' },
        ],
    },
];
