// Short-pass, long-pass and notch filters. Field reference: ../entryModel.js.
export const EDGE_AND_NOTCH_FILTERS = [
    {
        id: 'sp-640-tio2-sio2-21l',
        name: 'Short-pass, 640 nm edge, TiO2/SiO2, 21 layers',
        type: 'edge',
        tags: ['visible', 'short-pass', 'imaging', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass'],
        use: 'Use this to pass the blue and green part of the visible band and reject the red and the near infrared, for example in front of a sensor that must not see a red alignment beam or a heat source.',
        limitations: 'Blocking runs to about 810 nm and no further: the built-in TiO2 data stops at 827 nm, so nothing is claimed deeper into the infrared, and a real part would need a separate blocker there. The pass band also closes below about 445 nm, where the next reflectance zone of the stack begins.',
        source: 'The symmetrical-period short-pass filter of Macleod, Thin-Film Optical Filters, 5th ed., section 7.2.4 Application to Edge Filters, Figure 7.5: Air | (0.5L H 0.5L)^10 0.5L | Glass, with the extra half-thickness low-index layer at the substrate that also acts as a match. Adjacent half-thickness layers are merged into single layers, and every thickness was then refined in TFStudio for a flat pass band and a deep stop band against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 700,
        bands: [[450, 630], [705, 810]],
        aoi: 0,
        polarization: 'avg',
        preview: [400, 830],
        layers: [
            { material: 'builtin:SiO2', thickness: 175.43 },
            { material: 'builtin:TiO2', thickness: 95.40 },
            { material: 'builtin:SiO2', thickness: 125.20 },
            { material: 'builtin:TiO2', thickness: 92.44 },
            { material: 'builtin:SiO2', thickness: 95.55 },
            { material: 'builtin:TiO2', thickness: 98.27 },
            { material: 'builtin:SiO2', thickness: 85.95 },
            { material: 'builtin:TiO2', thickness: 90.06 },
            { material: 'builtin:SiO2', thickness: 125.04 },
            { material: 'builtin:TiO2', thickness: 71.86 },
            { material: 'builtin:SiO2', thickness: 155.41 },
            { material: 'builtin:TiO2', thickness: 47.69 },
            { material: 'builtin:SiO2', thickness: 165.73 },
            { material: 'builtin:TiO2', thickness: 57.32 },
            { material: 'builtin:SiO2', thickness: 152.19 },
            { material: 'builtin:TiO2', thickness: 68.84 },
            { material: 'builtin:SiO2', thickness: 143.42 },
            { material: 'builtin:TiO2', thickness: 75.04 },
            { material: 'builtin:SiO2', thickness: 146.76 },
            { material: 'builtin:TiO2', thickness: 80.60 },
            { material: 'builtin:SiO2', thickness: 75.39 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 0, target: 0.95, label: 'T min in pass band ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 1, target: 0.005, label: 'T max in stop band ≤ 0.5%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 500, lambdaEnd: 820, cmp: 'between', lo: 630, hi: 655, label: '50% edge 630-655 nm' },
        ],
    },
    {
        id: 'lp-605-tio2-sio2-21l',
        name: 'Long-pass, 605 nm edge, TiO2/SiO2, 21 layers',
        type: 'edge',
        tags: ['visible', 'long-pass', 'imaging', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass'],
        use: 'Use this to pass red and the near infrared while rejecting blue and green, for example to separate a red illumination band from ambient light, or as the emission side of a two-colour split.',
        limitations: 'Blocking is specified over 440-555 nm; it continues below 440 nm but is not claimed there, and the pass band is claimed only to 800 nm because the built-in TiO2 data stops at 827 nm. The transition is about 25 nm wide, which is a normal 21-layer edge and not a laser-line edge.',
        source: 'The symmetrical-period long-pass filter of Macleod, Thin-Film Optical Filters, 5th ed., section 7.2.4 Application to Edge Filters, Figure 7.4: Air | (0.5H L 0.5H)^10 | Glass, which the same section shows is the better-matched of the two symmetrical periods for a long-pass filter on glass. Adjacent half-thickness layers are merged into single layers, and every thickness was then refined in TFStudio against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 450,
        bands: [[440, 555], [640, 800]],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 820],
        layers: [
            { material: 'builtin:TiO2', thickness: 22.36 },
            { material: 'builtin:SiO2', thickness: 77.38 },
            { material: 'builtin:TiO2', thickness: 45.95 },
            { material: 'builtin:SiO2', thickness: 80.80 },
            { material: 'builtin:TiO2', thickness: 48.60 },
            { material: 'builtin:SiO2', thickness: 83.48 },
            { material: 'builtin:TiO2', thickness: 49.24 },
            { material: 'builtin:SiO2', thickness: 84.49 },
            { material: 'builtin:TiO2', thickness: 51.03 },
            { material: 'builtin:SiO2', thickness: 87.99 },
            { material: 'builtin:TiO2', thickness: 50.38 },
            { material: 'builtin:SiO2', thickness: 83.04 },
            { material: 'builtin:TiO2', thickness: 48.89 },
            { material: 'builtin:SiO2', thickness: 88.12 },
            { material: 'builtin:TiO2', thickness: 53.60 },
            { material: 'builtin:SiO2', thickness: 85.55 },
            { material: 'builtin:TiO2', thickness: 41.78 },
            { material: 'builtin:SiO2', thickness: 78.30 },
            { material: 'builtin:TiO2', thickness: 58.74 },
            { material: 'builtin:SiO2', thickness: 101.55 },
            { material: 'builtin:TiO2', thickness: 12.00 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.005, label: 'T max in stop band ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min in pass band ≥ 95%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 450, lambdaEnd: 800, cmp: 'between', lo: 592, hi: 618, label: '50% edge 592-618 nm' },
        ],
    },
    {
        id: 'lp-800-nb2o5-sio2-41l',
        name: 'Long-pass, 800 nm edge, Nb2O5/SiO2, 41 layers',
        type: 'edge',
        tags: ['nir', 'long-pass', 'raman', 'fluorescence', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'fused-silica'],
        use: 'Use this to cut everything below 790 nm and pass the near infrared above 805: the emission side of a 785 nm Raman or fluorescence path, or a filter that keeps a pump laser out of a near-infrared detector. The transition takes about 15 nm, which is steep for a two-material stack.',
        limitations: 'Blocking reaches about 0.02% average, roughly optical density 3.7, over 700-780 nm. A Raman instrument working within a few nanometres of the 785 nm line needs optical density 6 right up to the line; this filter is already at 0.6% at 785 nm and is not that part. The pass band is claimed to 1000 nm because the built-in Nb2O5 data stops there.',
        source: 'The symmetrical-period long-pass filter of Macleod, Thin-Film Optical Filters, 5th ed., section 7.2.4 Application to Edge Filters, Air | (0.5H L 0.5H)^20 | Glass at a reference wavelength of 840 nm, with adjacent half-thickness layers merged. Every thickness was then refined in TFStudio for a deep stop band and a flat pass band against the specification below. Wavelength choice follows the REX-Optics Coating Designer preset "Raman edge filter 785 nm (long-pass)" (designer.rex-optics.com, taken 2026-09-02), whose Ta2O5 was replaced by Nb2O5 because the built-in Ta2O5 data carries enough extinction here to cost several percent of the pass band.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 840,
        bands: [[700, 780], [805, 1000]],
        aoi: 0,
        polarization: 'avg',
        preview: [650, 1000],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 43.83 },
            { material: 'builtin:SiO2', thickness: 120.58 },
            { material: 'builtin:Nb2O5', thickness: 54.28 },
            { material: 'builtin:SiO2', thickness: 125.99 },
            { material: 'builtin:Nb2O5', thickness: 73.19 },
            { material: 'builtin:SiO2', thickness: 127.83 },
            { material: 'builtin:Nb2O5', thickness: 63.46 },
            { material: 'builtin:SiO2', thickness: 123.10 },
            { material: 'builtin:Nb2O5', thickness: 64.99 },
            { material: 'builtin:SiO2', thickness: 125.94 },
            { material: 'builtin:Nb2O5', thickness: 60.49 },
            { material: 'builtin:SiO2', thickness: 110.59 },
            { material: 'builtin:Nb2O5', thickness: 12.00 },
            { material: 'builtin:SiO2', thickness: 98.59 },
            { material: 'builtin:Nb2O5', thickness: 41.16 },
            { material: 'builtin:SiO2', thickness: 120.38 },
            { material: 'builtin:Nb2O5', thickness: 66.23 },
            { material: 'builtin:SiO2', thickness: 128.52 },
            { material: 'builtin:Nb2O5', thickness: 72.97 },
            { material: 'builtin:SiO2', thickness: 128.12 },
            { material: 'builtin:Nb2O5', thickness: 67.16 },
            { material: 'builtin:SiO2', thickness: 124.87 },
            { material: 'builtin:Nb2O5', thickness: 67.05 },
            { material: 'builtin:SiO2', thickness: 127.77 },
            { material: 'builtin:Nb2O5', thickness: 72.31 },
            { material: 'builtin:SiO2', thickness: 128.96 },
            { material: 'builtin:Nb2O5', thickness: 69.22 },
            { material: 'builtin:SiO2', thickness: 125.58 },
            { material: 'builtin:Nb2O5', thickness: 65.56 },
            { material: 'builtin:SiO2', thickness: 126.52 },
            { material: 'builtin:Nb2O5', thickness: 71.07 },
            { material: 'builtin:SiO2', thickness: 129.59 },
            { material: 'builtin:Nb2O5', thickness: 70.70 },
            { material: 'builtin:SiO2', thickness: 125.12 },
            { material: 'builtin:Nb2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 124.05 },
            { material: 'builtin:Nb2O5', thickness: 69.38 },
            { material: 'builtin:SiO2', thickness: 129.41 },
            { material: 'builtin:Nb2O5', thickness: 69.65 },
            { material: 'builtin:SiO2', thickness: 125.67 },
            { material: 'builtin:Nb2O5', thickness: 31.29 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.005, label: 'T max 700-780 nm ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min 805-1000 nm ≥ 95%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 720, lambdaEnd: 900, cmp: 'between', lo: 790, hi: 806, label: '50% edge 790-806 nm' },
        ],
    },
    {
        id: 'notch-532-al2o3-sio2-81l',
        name: 'Notch filter at 532 nm, Al2O3/SiO2, 81 layers',
        type: 'notch',
        tags: ['visible', 'narrowband', 'raman', 'fluorescence', 'all-dielectric', 'quarter-wave', 'normal-incidence', 'fused-silica'],
        use: 'Use this to take one laser line out of a beam while leaving the rest of the visible band alone: rejecting the 532 nm pump in a Raman or fluorescence path, or keeping a stray alignment beam off a detector. Aluminium oxide against silica is a deliberately low index contrast, which is what keeps the rejection band narrow.',
        limitations: 'The notch rejects to about 0.05% transmittance, roughly optical density 3. A Raman instrument that has to see a shift of a few wavenumbers off the laser line needs optical density 6, which this pair cannot reach at this layer count. The rejection band is around 40 nm wide at the half-transmittance points, wider than a holographic notch. Transmission closes again below 450 nm and above about 720 nm, where the next reflectance zones of the stack sit.',
        source: 'Macleod, Thin-Film Optical Filters, 5th ed., section 7.3 Notch Filters: a quarter-wave stack of two materials whose indices are close together, so the reflectance zone is narrow, with enough periods to make it deep. Forty Al2O3/SiO2 pairs plus a final high-index layer, quarter waves at 532 nm on the built-in data, then every thickness refined in TFStudio for a deep notch and flat transmission either side of it against the specification below. Wavelength and material choice follow the REX-Optics Coating Designer preset "Raman notch 532 nm (laser rejection)" (designer.rex-optics.com, taken 2026-09-02).',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 532,
        bands: [[460, 500], [527, 537], [565, 700]],
        aoi: 0,
        polarization: 'avg',
        preview: [430, 760],
        layers: [
            { material: 'builtin:Al2O3', thickness: 156.77 },
            { material: 'builtin:SiO2', thickness: 119.60 },
            { material: 'builtin:Al2O3', thickness: 58.34 },
            { material: 'builtin:SiO2', thickness: 10.00 },
            { material: 'builtin:Al2O3', thickness: 59.58 },
            { material: 'builtin:SiO2', thickness: 136.35 },
            { material: 'builtin:Al2O3', thickness: 149.05 },
            { material: 'builtin:SiO2', thickness: 96.61 },
            { material: 'builtin:Al2O3', thickness: 57.51 },
            { material: 'builtin:SiO2', thickness: 91.60 },
            { material: 'builtin:Al2O3', thickness: 37.99 },
            { material: 'builtin:SiO2', thickness: 48.35 },
            { material: 'builtin:Al2O3', thickness: 98.84 },
            { material: 'builtin:SiO2', thickness: 159.23 },
            { material: 'builtin:Al2O3', thickness: 96.24 },
            { material: 'builtin:SiO2', thickness: 70.06 },
            { material: 'builtin:Al2O3', thickness: 55.28 },
            { material: 'builtin:SiO2', thickness: 82.67 },
            { material: 'builtin:Al2O3', thickness: 54.42 },
            { material: 'builtin:SiO2', thickness: 78.17 },
            { material: 'builtin:Al2O3', thickness: 106.93 },
            { material: 'builtin:SiO2', thickness: 130.70 },
            { material: 'builtin:Al2O3', thickness: 68.50 },
            { material: 'builtin:SiO2', thickness: 58.90 },
            { material: 'builtin:Al2O3', thickness: 47.89 },
            { material: 'builtin:SiO2', thickness: 100.29 },
            { material: 'builtin:Al2O3', thickness: 100.59 },
            { material: 'builtin:SiO2', thickness: 103.48 },
            { material: 'builtin:Al2O3', thickness: 75.27 },
            { material: 'builtin:SiO2', thickness: 66.57 },
            { material: 'builtin:Al2O3', thickness: 55.64 },
            { material: 'builtin:SiO2', thickness: 96.67 },
            { material: 'builtin:Al2O3', thickness: 94.43 },
            { material: 'builtin:SiO2', thickness: 112.37 },
            { material: 'builtin:Al2O3', thickness: 63.50 },
            { material: 'builtin:SiO2', thickness: 54.01 },
            { material: 'builtin:Al2O3', thickness: 76.54 },
            { material: 'builtin:SiO2', thickness: 118.39 },
            { material: 'builtin:Al2O3', thickness: 92.18 },
            { material: 'builtin:SiO2', thickness: 75.95 },
            { material: 'builtin:Al2O3', thickness: 56.75 },
            { material: 'builtin:SiO2', thickness: 90.53 },
            { material: 'builtin:Al2O3', thickness: 73.68 },
            { material: 'builtin:SiO2', thickness: 99.73 },
            { material: 'builtin:Al2O3', thickness: 97.58 },
            { material: 'builtin:SiO2', thickness: 74.34 },
            { material: 'builtin:Al2O3', thickness: 45.88 },
            { material: 'builtin:SiO2', thickness: 94.90 },
            { material: 'builtin:Al2O3', thickness: 98.37 },
            { material: 'builtin:SiO2', thickness: 108.05 },
            { material: 'builtin:Al2O3', thickness: 69.65 },
            { material: 'builtin:SiO2', thickness: 68.95 },
            { material: 'builtin:Al2O3', thickness: 60.98 },
            { material: 'builtin:SiO2', thickness: 95.03 },
            { material: 'builtin:Al2O3', thickness: 94.10 },
            { material: 'builtin:SiO2', thickness: 100.17 },
            { material: 'builtin:Al2O3', thickness: 70.83 },
            { material: 'builtin:SiO2', thickness: 76.37 },
            { material: 'builtin:Al2O3', thickness: 44.36 },
            { material: 'builtin:SiO2', thickness: 104.80 },
            { material: 'builtin:Al2O3', thickness: 124.02 },
            { material: 'builtin:SiO2', thickness: 81.51 },
            { material: 'builtin:Al2O3', thickness: 51.89 },
            { material: 'builtin:SiO2', thickness: 91.95 },
            { material: 'builtin:Al2O3', thickness: 80.84 },
            { material: 'builtin:SiO2', thickness: 80.98 },
            { material: 'builtin:Al2O3', thickness: 48.47 },
            { material: 'builtin:SiO2', thickness: 91.87 },
            { material: 'builtin:Al2O3', thickness: 144.61 },
            { material: 'builtin:SiO2', thickness: 79.86 },
            { material: 'builtin:Al2O3', thickness: 23.87 },
            { material: 'builtin:SiO2', thickness: 103.15 },
            { material: 'builtin:Al2O3', thickness: 103.23 },
            { material: 'builtin:SiO2', thickness: 86.00 },
            { material: 'builtin:Al2O3', thickness: 30.47 },
            { material: 'builtin:SiO2', thickness: 71.80 },
            { material: 'builtin:Al2O3', thickness: 107.76 },
            { material: 'builtin:SiO2', thickness: 172.88 },
            { material: 'builtin:Al2O3', thickness: 64.91 },
            { material: 'builtin:SiO2', thickness: 92.41 },
            { material: 'builtin:Al2O3', thickness: 10.00 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 0, target: 0.95, label: 'T min 460-500 nm ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 1, target: 0.002, label: 'T max 527-537 nm ≤ 0.2%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 2, target: 0.95, label: 'T min 565-700 nm ≥ 95%' },
        ],
    },
];
