// Short-pass, long-pass and notch filters. Field reference: ../entryModel.js.
import { embedded } from './materials.js';

export const EDGE_AND_NOTCH_FILTERS = [
    {
        id: 'sp-640-tio2-sio2-21l',
        name: 'Short-pass, 640 nm edge, TiO2/SiO2, 21 layers',
        type: 'edge',
        tags: ['visible', 'short-pass', 'imaging', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass'],
        use: 'Use this to pass the blue and green part of the visible band and reject the red and the near infrared, for example in front of a sensor that must not see a red alignment beam or a heat source.',
        limitations: 'Blocking runs to about 810 nm and no further: the built-in TiO2 data stops at 827 nm, so nothing is claimed deeper into the infrared, and a real part would need a separate blocker there. The pass band also closes below about 445 nm, where the next reflectance zone of the stack begins.',
        source: 'The symmetrical-period short-pass filter of Macleod, Thin-Film Optical Filters, 5th ed., section 7.2.4 Application to Edge Filters, Figure 7.5: Air | (0.5L H 0.5L)^10 0.5L | Glass, with the extra half-thickness low-index layer at the substrate that also acts as a match. Adjacent half-thickness layers are merged into single layers, and every thickness was then refined in TFStudio for a flat pass band and a deep stop band against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 700,
        bands: [[450, 630], [705, 810]],
        aoi: 0,
        polarization: 'avg',
        preview: [400, 830],
        layers: [
            { material: 'builtin:SiO2', thickness: 175.43 },
            { material: 'builtin:TiO2', thickness: 95.40 },
            { material: 'builtin:SiO2', thickness: 125.20 },
            { material: 'builtin:TiO2', thickness: 92.44 },
            { material: 'builtin:SiO2', thickness: 95.55 },
            { material: 'builtin:TiO2', thickness: 98.27 },
            { material: 'builtin:SiO2', thickness: 85.95 },
            { material: 'builtin:TiO2', thickness: 90.06 },
            { material: 'builtin:SiO2', thickness: 125.04 },
            { material: 'builtin:TiO2', thickness: 71.86 },
            { material: 'builtin:SiO2', thickness: 155.41 },
            { material: 'builtin:TiO2', thickness: 47.69 },
            { material: 'builtin:SiO2', thickness: 165.73 },
            { material: 'builtin:TiO2', thickness: 57.32 },
            { material: 'builtin:SiO2', thickness: 152.19 },
            { material: 'builtin:TiO2', thickness: 68.84 },
            { material: 'builtin:SiO2', thickness: 143.42 },
            { material: 'builtin:TiO2', thickness: 75.04 },
            { material: 'builtin:SiO2', thickness: 146.76 },
            { material: 'builtin:TiO2', thickness: 80.60 },
            { material: 'builtin:SiO2', thickness: 75.39 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 0, target: 0.95, label: 'T min in pass band ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 1, target: 0.005, label: 'T max in stop band ≤ 0.5%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 500, lambdaEnd: 820, cmp: 'between', lo: 630, hi: 655, label: '50% edge 630-655 nm' },
        ],
    },
    {
        id: 'lp-605-tio2-sio2-21l',
        name: 'Long-pass, 605 nm edge, TiO2/SiO2, 21 layers',
        type: 'edge',
        tags: ['visible', 'long-pass', 'imaging', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass'],
        use: 'Use this to pass red and the near infrared while rejecting blue and green, for example to separate a red illumination band from ambient light, or as the emission side of a two-colour split.',
        limitations: 'Blocking is specified over 440-555 nm; it continues below 440 nm but is not claimed there, and the pass band is claimed only to 800 nm because the built-in TiO2 data stops at 827 nm. The transition is about 25 nm wide, which is a normal 21-layer edge and not a laser-line edge.',
        source: 'The symmetrical-period long-pass filter of Macleod, Thin-Film Optical Filters, 5th ed., section 7.2.4 Application to Edge Filters, Figure 7.4: Air | (0.5H L 0.5H)^10 | Glass, which the same section shows is the better-matched of the two symmetrical periods for a long-pass filter on glass. Adjacent half-thickness layers are merged into single layers, and every thickness was then refined in TFStudio against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 450,
        bands: [[440, 555], [640, 800]],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 820],
        layers: [
            { material: 'builtin:TiO2', thickness: 22.36 },
            { material: 'builtin:SiO2', thickness: 77.38 },
            { material: 'builtin:TiO2', thickness: 45.95 },
            { material: 'builtin:SiO2', thickness: 80.80 },
            { material: 'builtin:TiO2', thickness: 48.60 },
            { material: 'builtin:SiO2', thickness: 83.48 },
            { material: 'builtin:TiO2', thickness: 49.24 },
            { material: 'builtin:SiO2', thickness: 84.49 },
            { material: 'builtin:TiO2', thickness: 51.03 },
            { material: 'builtin:SiO2', thickness: 87.99 },
            { material: 'builtin:TiO2', thickness: 50.38 },
            { material: 'builtin:SiO2', thickness: 83.04 },
            { material: 'builtin:TiO2', thickness: 48.89 },
            { material: 'builtin:SiO2', thickness: 88.12 },
            { material: 'builtin:TiO2', thickness: 53.60 },
            { material: 'builtin:SiO2', thickness: 85.55 },
            { material: 'builtin:TiO2', thickness: 41.78 },
            { material: 'builtin:SiO2', thickness: 78.30 },
            { material: 'builtin:TiO2', thickness: 58.74 },
            { material: 'builtin:SiO2', thickness: 101.55 },
            { material: 'builtin:TiO2', thickness: 12.00 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.005, label: 'T max in stop band ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min in pass band ≥ 95%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 450, lambdaEnd: 800, cmp: 'between', lo: 592, hi: 618, label: '50% edge 592-618 nm' },
        ],
    },
    {
        id: 'lp-800-nb2o5-sio2-41l',
        name: 'Long-pass, 800 nm edge, Nb2O5/SiO2, 41 layers',
        type: 'edge',
        tags: ['nir', 'long-pass', 'raman', 'fluorescence', 'all-dielectric', 'nb2o5-sio2', 'normal-incidence', 'fused-silica'],
        use: 'Use this to cut everything below 790 nm and pass the near infrared above 805: the emission side of a 785 nm Raman or fluorescence path, or a filter that keeps a pump laser out of a near-infrared detector. The transition takes about 15 nm, which is steep for a two-material stack.',
        limitations: 'Blocking reaches about 0.02% average, roughly optical density 3.7, over 700-780 nm. A Raman instrument working within a few nanometres of the 785 nm line needs optical density 6 right up to the line; this filter is already at 0.6% at 785 nm and is not that part. The pass band is claimed to 1000 nm because the built-in Nb2O5 data stops there.',
        source: 'The symmetrical-period long-pass filter of Macleod, Thin-Film Optical Filters, 5th ed., section 7.2.4 Application to Edge Filters, Air | (0.5H L 0.5H)^20 | Glass at a reference wavelength of 840 nm, with adjacent half-thickness layers merged. Every thickness was then refined in TFStudio for a deep stop band and a flat pass band against the specification below. Nb2O5 rather than Ta2O5 as the high index because the built-in Ta2O5 data carries enough extinction here to cost several percent of the pass band.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 840,
        bands: [[700, 780], [805, 1000]],
        aoi: 0,
        polarization: 'avg',
        preview: [650, 1000],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 43.83 },
            { material: 'builtin:SiO2', thickness: 120.58 },
            { material: 'builtin:Nb2O5', thickness: 54.28 },
            { material: 'builtin:SiO2', thickness: 125.99 },
            { material: 'builtin:Nb2O5', thickness: 73.19 },
            { material: 'builtin:SiO2', thickness: 127.83 },
            { material: 'builtin:Nb2O5', thickness: 63.46 },
            { material: 'builtin:SiO2', thickness: 123.10 },
            { material: 'builtin:Nb2O5', thickness: 64.99 },
            { material: 'builtin:SiO2', thickness: 125.94 },
            { material: 'builtin:Nb2O5', thickness: 60.49 },
            { material: 'builtin:SiO2', thickness: 110.59 },
            { material: 'builtin:Nb2O5', thickness: 12.00 },
            { material: 'builtin:SiO2', thickness: 98.59 },
            { material: 'builtin:Nb2O5', thickness: 41.16 },
            { material: 'builtin:SiO2', thickness: 120.38 },
            { material: 'builtin:Nb2O5', thickness: 66.23 },
            { material: 'builtin:SiO2', thickness: 128.52 },
            { material: 'builtin:Nb2O5', thickness: 72.97 },
            { material: 'builtin:SiO2', thickness: 128.12 },
            { material: 'builtin:Nb2O5', thickness: 67.16 },
            { material: 'builtin:SiO2', thickness: 124.87 },
            { material: 'builtin:Nb2O5', thickness: 67.05 },
            { material: 'builtin:SiO2', thickness: 127.77 },
            { material: 'builtin:Nb2O5', thickness: 72.31 },
            { material: 'builtin:SiO2', thickness: 128.96 },
            { material: 'builtin:Nb2O5', thickness: 69.22 },
            { material: 'builtin:SiO2', thickness: 125.58 },
            { material: 'builtin:Nb2O5', thickness: 65.56 },
            { material: 'builtin:SiO2', thickness: 126.52 },
            { material: 'builtin:Nb2O5', thickness: 71.07 },
            { material: 'builtin:SiO2', thickness: 129.59 },
            { material: 'builtin:Nb2O5', thickness: 70.70 },
            { material: 'builtin:SiO2', thickness: 125.12 },
            { material: 'builtin:Nb2O5', thickness: 61.95 },
            { material: 'builtin:SiO2', thickness: 124.05 },
            { material: 'builtin:Nb2O5', thickness: 69.38 },
            { material: 'builtin:SiO2', thickness: 129.41 },
            { material: 'builtin:Nb2O5', thickness: 69.65 },
            { material: 'builtin:SiO2', thickness: 125.67 },
            { material: 'builtin:Nb2O5', thickness: 31.29 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.005, label: 'T max 700-780 nm ≤ 0.5%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.95, label: 'T min 805-1000 nm ≥ 95%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 720, lambdaEnd: 900, cmp: 'between', lo: 790, hi: 806, label: '50% edge 790-806 nm' },
        ],
    },
    {
        id: 'notch-532-al2o3-sio2-81l',
        name: 'Notch filter at 532 nm, Al2O3/SiO2, 81 layers',
        type: 'notch',
        tags: ['visible', 'narrowband', 'raman', 'fluorescence', 'all-dielectric', 'quarter-wave', 'normal-incidence', 'fused-silica'],
        use: 'Use this to take one laser line out of a beam while leaving the rest of the visible band alone: rejecting the 532 nm pump in a Raman or fluorescence path, or keeping a stray alignment beam off a detector. Aluminium oxide against silica is a deliberately low index contrast, which is what keeps the rejection band narrow.',
        limitations: 'The notch rejects to about 0.05% transmittance, roughly optical density 3. A Raman instrument that has to see a shift of a few wavenumbers off the laser line needs optical density 6, which this pair cannot reach at this layer count. The rejection band is around 40 nm wide at the half-transmittance points, wider than a holographic notch. Transmission closes again below 450 nm and above about 720 nm, where the next reflectance zones of the stack sit.',
        source: 'Macleod, Thin-Film Optical Filters, 5th ed., section 7.3 Notch Filters: a quarter-wave stack of two materials whose indices are close together, so the reflectance zone is narrow, with enough periods to make it deep. Forty Al2O3/SiO2 pairs plus a final high-index layer, quarter waves at 532 nm on the built-in data, then every thickness refined in TFStudio for a deep notch and flat transmission either side of it against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 532,
        bands: [[460, 500], [527, 537], [565, 700]],
        aoi: 0,
        polarization: 'avg',
        preview: [430, 760],
        layers: [
            { material: 'builtin:Al2O3', thickness: 156.77 },
            { material: 'builtin:SiO2', thickness: 119.60 },
            { material: 'builtin:Al2O3', thickness: 58.34 },
            { material: 'builtin:SiO2', thickness: 10.00 },
            { material: 'builtin:Al2O3', thickness: 59.58 },
            { material: 'builtin:SiO2', thickness: 136.35 },
            { material: 'builtin:Al2O3', thickness: 149.05 },
            { material: 'builtin:SiO2', thickness: 96.61 },
            { material: 'builtin:Al2O3', thickness: 57.51 },
            { material: 'builtin:SiO2', thickness: 91.60 },
            { material: 'builtin:Al2O3', thickness: 37.99 },
            { material: 'builtin:SiO2', thickness: 48.35 },
            { material: 'builtin:Al2O3', thickness: 98.84 },
            { material: 'builtin:SiO2', thickness: 159.23 },
            { material: 'builtin:Al2O3', thickness: 96.24 },
            { material: 'builtin:SiO2', thickness: 70.06 },
            { material: 'builtin:Al2O3', thickness: 55.28 },
            { material: 'builtin:SiO2', thickness: 82.67 },
            { material: 'builtin:Al2O3', thickness: 54.42 },
            { material: 'builtin:SiO2', thickness: 78.17 },
            { material: 'builtin:Al2O3', thickness: 106.93 },
            { material: 'builtin:SiO2', thickness: 130.70 },
            { material: 'builtin:Al2O3', thickness: 68.50 },
            { material: 'builtin:SiO2', thickness: 58.90 },
            { material: 'builtin:Al2O3', thickness: 47.89 },
            { material: 'builtin:SiO2', thickness: 100.29 },
            { material: 'builtin:Al2O3', thickness: 100.59 },
            { material: 'builtin:SiO2', thickness: 103.48 },
            { material: 'builtin:Al2O3', thickness: 75.27 },
            { material: 'builtin:SiO2', thickness: 66.57 },
            { material: 'builtin:Al2O3', thickness: 55.64 },
            { material: 'builtin:SiO2', thickness: 96.67 },
            { material: 'builtin:Al2O3', thickness: 94.43 },
            { material: 'builtin:SiO2', thickness: 112.37 },
            { material: 'builtin:Al2O3', thickness: 63.50 },
            { material: 'builtin:SiO2', thickness: 54.01 },
            { material: 'builtin:Al2O3', thickness: 76.54 },
            { material: 'builtin:SiO2', thickness: 118.39 },
            { material: 'builtin:Al2O3', thickness: 92.18 },
            { material: 'builtin:SiO2', thickness: 75.95 },
            { material: 'builtin:Al2O3', thickness: 56.75 },
            { material: 'builtin:SiO2', thickness: 90.53 },
            { material: 'builtin:Al2O3', thickness: 73.68 },
            { material: 'builtin:SiO2', thickness: 99.73 },
            { material: 'builtin:Al2O3', thickness: 97.58 },
            { material: 'builtin:SiO2', thickness: 74.34 },
            { material: 'builtin:Al2O3', thickness: 45.88 },
            { material: 'builtin:SiO2', thickness: 94.90 },
            { material: 'builtin:Al2O3', thickness: 98.37 },
            { material: 'builtin:SiO2', thickness: 108.05 },
            { material: 'builtin:Al2O3', thickness: 69.65 },
            { material: 'builtin:SiO2', thickness: 68.95 },
            { material: 'builtin:Al2O3', thickness: 60.98 },
            { material: 'builtin:SiO2', thickness: 95.03 },
            { material: 'builtin:Al2O3', thickness: 94.10 },
            { material: 'builtin:SiO2', thickness: 100.17 },
            { material: 'builtin:Al2O3', thickness: 70.83 },
            { material: 'builtin:SiO2', thickness: 76.37 },
            { material: 'builtin:Al2O3', thickness: 44.36 },
            { material: 'builtin:SiO2', thickness: 104.80 },
            { material: 'builtin:Al2O3', thickness: 124.02 },
            { material: 'builtin:SiO2', thickness: 81.51 },
            { material: 'builtin:Al2O3', thickness: 51.89 },
            { material: 'builtin:SiO2', thickness: 91.95 },
            { material: 'builtin:Al2O3', thickness: 80.84 },
            { material: 'builtin:SiO2', thickness: 80.98 },
            { material: 'builtin:Al2O3', thickness: 48.47 },
            { material: 'builtin:SiO2', thickness: 91.87 },
            { material: 'builtin:Al2O3', thickness: 144.61 },
            { material: 'builtin:SiO2', thickness: 79.86 },
            { material: 'builtin:Al2O3', thickness: 23.87 },
            { material: 'builtin:SiO2', thickness: 103.15 },
            { material: 'builtin:Al2O3', thickness: 103.23 },
            { material: 'builtin:SiO2', thickness: 86.00 },
            { material: 'builtin:Al2O3', thickness: 30.47 },
            { material: 'builtin:SiO2', thickness: 71.80 },
            { material: 'builtin:Al2O3', thickness: 107.76 },
            { material: 'builtin:SiO2', thickness: 172.88 },
            { material: 'builtin:Al2O3', thickness: 64.91 },
            { material: 'builtin:SiO2', thickness: 92.41 },
            { material: 'builtin:Al2O3', thickness: 10.00 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 0, target: 0.95, label: 'T min 460-500 nm ≥ 95%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 1, target: 0.002, label: 'T max 527-537 nm ≤ 0.2%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 2, target: 0.95, label: 'T min 565-700 nm ≥ 95%' },
        ],
    },
    {
        id: 'sp-650-tio2-sio2-36l',
        name: 'Short-pass, 650 nm edge, TiO2/SiO2, 36 layers',
        type: 'edge',
        tags: ['visible', 'nir', 'short-pass', 'imaging', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this to pass the whole visible band up to about 640 nm and reject the deep red and near infrared behind it: in front of a colour sensor that must not see a red alignment beam or a lamp filament, or as the short-pass half of a two-colour split. The transition takes about 20 nm, steep enough to put a pass band and a stop band close together.',
        limitations: 'Blocking is claimed to 800 nm and no further, because the built-in TiO2 data stops at 827 nm; past its reflectance zone the stack opens again and a real part needs a second blocker there. The pass band closes below about 390 nm. Thirty-six layers and 3.7 um of material make this sensitive to a systematic rate error: the edge moves in proportion to the thickness scale, so one percent long puts it at 659 nm instead of 652.',
        source: 'OptiLayer sample design "SWP-36" from the LEC25D27-1 example (OptiLayer GmbH): a 36-layer short-pass filter designed against a cut-off target of full transmittance over 400-640 nm and zero transmittance over 680-800 nm, with a Cauchy fit to a titania film as the high index and measured silica data as the low index. The same example holds two monitoring-strategy variants of this design; this is the design itself. Re-optimized in TFStudio against the built-in TiO2 and SiO2 data over the same two bands, against the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 425,
        bands: [[400, 640], [680, 800]],
        aoi: 0,
        polarization: 'avg',
        layers: [
            { material: 'builtin:TiO2', thickness: 12.01 },
            { material: 'builtin:SiO2', thickness: 33.37 },
            { material: 'builtin:TiO2', thickness: 99.69 },
            { material: 'builtin:SiO2', thickness: 156.93 },
            { material: 'builtin:TiO2', thickness: 81.21 },
            { material: 'builtin:SiO2', thickness: 142.93 },
            { material: 'builtin:TiO2', thickness: 76.56 },
            { material: 'builtin:SiO2', thickness: 139.62 },
            { material: 'builtin:TiO2', thickness: 74.97 },
            { material: 'builtin:SiO2', thickness: 137.90 },
            { material: 'builtin:TiO2', thickness: 74.24 },
            { material: 'builtin:SiO2', thickness: 137.54 },
            { material: 'builtin:TiO2', thickness: 73.46 },
            { material: 'builtin:SiO2', thickness: 137.63 },
            { material: 'builtin:TiO2', thickness: 73.25 },
            { material: 'builtin:SiO2', thickness: 137.30 },
            { material: 'builtin:TiO2', thickness: 73.29 },
            { material: 'builtin:SiO2', thickness: 137.41 },
            { material: 'builtin:TiO2', thickness: 73.05 },
            { material: 'builtin:SiO2', thickness: 137.84 },
            { material: 'builtin:TiO2', thickness: 73.09 },
            { material: 'builtin:SiO2', thickness: 137.71 },
            { material: 'builtin:TiO2', thickness: 73.41 },
            { material: 'builtin:SiO2', thickness: 137.88 },
            { material: 'builtin:TiO2', thickness: 73.39 },
            { material: 'builtin:SiO2', thickness: 138.65 },
            { material: 'builtin:TiO2', thickness: 73.72 },
            { material: 'builtin:SiO2', thickness: 138.83 },
            { material: 'builtin:TiO2', thickness: 74.68 },
            { material: 'builtin:SiO2', thickness: 139.72 },
            { material: 'builtin:TiO2', thickness: 75.73 },
            { material: 'builtin:SiO2', thickness: 142.34 },
            { material: 'builtin:TiO2', thickness: 78.35 },
            { material: 'builtin:SiO2', thickness: 148.70 },
            { material: 'builtin:TiO2', thickness: 83.14 },
            { material: 'builtin:SiO2', thickness: 75.96 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 0, target: 0.99, label: 'T min 400-640 nm ≥ 99%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 1, target: 0.001, label: 'T max 680-800 nm ≤ 0.1%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 500, lambdaEnd: 820, cmp: 'between', lo: 645, hi: 660, label: '50% edge 645-660 nm' },
        ],
    },
    {
        id: 'lp-710-tio2-sio2-49l',
        name: 'Long-pass, 710 nm edge, TiO2/SiO2, 49 layers',
        type: 'edge',
        tags: ['visible', 'nir', 'long-pass', 'imaging', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass', 'textbook'],
        use: 'Use this to cut the visible and pass the red and the near infrared with a flat pass band: separating a 785 or 850 nm channel from visible light, or keeping a lamp\'s visible output off a near-infrared detector. The matching sections at both ends of the stack are what hold the pass band flat, which a plain symmetrical-period stack does not.',
        limitations: 'The stop band runs from about 515 to 700 nm and no further; below 515 nm the filter transmits again in a rippled band, so a part that also has to block the blue needs a second stack. The pass band is claimed to 1000 nm, and 49 layers is a long deposition run in which a systematic thickness error moves the edge bodily.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "49 Layer Longwave Pass Filter": a starting design of (0.5H L 0.5H)^24 in TiO2 and SiO2 at a reference wavelength of 600 nm, 49 layers once the adjacent half-thickness layers are combined, with eight layers at each end of the stack opened as a matching system while the rest stayed at quarter waves. The collection notes a small residual dip next to the edge and that more matching layers would reduce it. Re-optimized in TFStudio for a deep stop band and a flat pass band against the specification below. The built-in TiO2 data stops at 827 nm and cannot cover the pass band, so the entry carries the atomic-layer-deposited TiO2 of Siefke and co-workers from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 600,
        bands: [[520, 690], [720, 1000]],
        aoi: 0,
        polarization: 'avg',
        preview: [420, 1100],
        layers: [
            { material: 'rii:TiO2-Siefke', thickness: 24.03 },
            { material: 'builtin:SiO2', thickness: 87.68 },
            { material: 'rii:TiO2-Siefke', thickness: 61.73 },
            { material: 'builtin:SiO2', thickness: 85.13 },
            { material: 'rii:TiO2-Siefke', thickness: 55.24 },
            { material: 'builtin:SiO2', thickness: 109.19 },
            { material: 'rii:TiO2-Siefke', thickness: 60.57 },
            { material: 'builtin:SiO2', thickness: 94.53 },
            { material: 'rii:TiO2-Siefke', thickness: 61.30 },
            { material: 'builtin:SiO2', thickness: 105.86 },
            { material: 'rii:TiO2-Siefke', thickness: 61.30 },
            { material: 'builtin:SiO2', thickness: 102.17 },
            { material: 'rii:TiO2-Siefke', thickness: 59.79 },
            { material: 'builtin:SiO2', thickness: 105.56 },
            { material: 'rii:TiO2-Siefke', thickness: 61.99 },
            { material: 'builtin:SiO2', thickness: 104.83 },
            { material: 'rii:TiO2-Siefke', thickness: 59.85 },
            { material: 'builtin:SiO2', thickness: 104.04 },
            { material: 'rii:TiO2-Siefke', thickness: 61.66 },
            { material: 'builtin:SiO2', thickness: 106.47 },
            { material: 'rii:TiO2-Siefke', thickness: 60.69 },
            { material: 'builtin:SiO2', thickness: 103.26 },
            { material: 'rii:TiO2-Siefke', thickness: 60.58 },
            { material: 'builtin:SiO2', thickness: 106.37 },
            { material: 'rii:TiO2-Siefke', thickness: 61.86 },
            { material: 'builtin:SiO2', thickness: 104.17 },
            { material: 'rii:TiO2-Siefke', thickness: 59.74 },
            { material: 'builtin:SiO2', thickness: 104.64 },
            { material: 'rii:TiO2-Siefke', thickness: 62.07 },
            { material: 'builtin:SiO2', thickness: 106.66 },
            { material: 'rii:TiO2-Siefke', thickness: 60.15 },
            { material: 'builtin:SiO2', thickness: 102.41 },
            { material: 'rii:TiO2-Siefke', thickness: 60.90 },
            { material: 'builtin:SiO2', thickness: 107.81 },
            { material: 'rii:TiO2-Siefke', thickness: 62.20 },
            { material: 'builtin:SiO2', thickness: 102.11 },
            { material: 'rii:TiO2-Siefke', thickness: 58.40 },
            { material: 'builtin:SiO2', thickness: 105.73 },
            { material: 'rii:TiO2-Siefke', thickness: 64.20 },
            { material: 'builtin:SiO2', thickness: 105.50 },
            { material: 'rii:TiO2-Siefke', thickness: 56.24 },
            { material: 'builtin:SiO2', thickness: 96.21 },
            { material: 'rii:TiO2-Siefke', thickness: 64.91 },
            { material: 'builtin:SiO2', thickness: 119.44 },
            { material: 'rii:TiO2-Siefke', thickness: 46.28 },
            { material: 'builtin:SiO2', thickness: 78.01 },
            { material: 'rii:TiO2-Siefke', thickness: 81.76 },
            { material: 'builtin:SiO2', thickness: 128.17 },
            { material: 'rii:TiO2-Siefke', thickness: 10.00 },
        ],
        materials: embedded('rii:TiO2-Siefke'),
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 0, target: 0.002, label: 'T max 520-690 nm ≤ 0.2%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 1, target: 0.99, label: 'T min 720-1000 nm ≥ 99%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', level: 0.5, lambdaStart: 600, lambdaEnd: 800, cmp: 'between', lo: 700, hi: 720, label: '50% edge 700-720 nm' },
        ],
    },
    {
        id: 'sp-700-45deg-tio2-sio2-121l',
        name: 'Non-polarizing short-pass at 45 degrees, 700 nm edge, TiO2/SiO2, 121 layers',
        type: 'edge',
        tags: ['visible', 'nir', 'short-pass', 'non-polarizing', 'all-dielectric', 'tio2-sio2', '45-degree', 'oblique', 'glass', 'textbook'],
        use: 'Use this when a short-pass edge has to sit at the same wavelength for both polarizations on a mirror mounted at 45 degrees. An ordinary edge filter tilted to 45 degrees splits into two edges tens of nanometres apart; this one is built so that they land within about four nanometres of each other, which is what a colour-splitting or beam-folding filter needs when the source is unpolarized.',
        limitations: 'The polarizations only coincide at 45 degrees, and the rejection band is narrow: blocking is claimed over 720 to 780 nm and the filter transmits again beyond about 800 nm, so a real part needs a conventional edge filter behind it. 121 layers is a very long deposition run and the whole edge moves with any systematic thickness error.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Non Polarizing Short Wave Pass Filter": a 121-layer TiO2/SiO2 stack built from the repeated symmetrical period (0.35X 0.6262Y 0.3136X 0.6262Y 0.35X)^30 laid out with the Essential Macleod edge filter tool, so that when the filter is tilted to 45 degrees its p and s edges both fall at 700 nm. The collection warns that the non-polarizing condition holds at one angle only and that the high-reflectance region is narrow, so the filter usually needs a conventional edge filter behind it. Re-optimized in TFStudio at 45 degrees against the built-in SiO2 and BK7 data and the specification below. The built-in TiO2 data stops at 827 nm, so the entry carries the atomic-layer-deposited TiO2 of Siefke and co-workers from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 700,
        bands: [[500, 690], [720, 780]],
        aoi: 45,
        polarization: 'avg',
        preview: [450, 860],
        layers: [
            { material: 'rii:TiO2-Siefke', thickness: 12.00 },
            { material: 'builtin:SiO2', thickness: 248.13 },
            { material: 'rii:TiO2-Siefke', thickness: 25.81 },
            { material: 'builtin:SiO2', thickness: 15.14 },
            { material: 'rii:TiO2-Siefke', thickness: 59.08 },
            { material: 'builtin:SiO2', thickness: 87.10 },
            { material: 'rii:TiO2-Siefke', thickness: 12.05 },
            { material: 'builtin:SiO2', thickness: 75.06 },
            { material: 'rii:TiO2-Siefke', thickness: 80.61 },
            { material: 'builtin:SiO2', thickness: 64.13 },
            { material: 'rii:TiO2-Siefke', thickness: 21.78 },
            { material: 'builtin:SiO2', thickness: 74.79 },
            { material: 'rii:TiO2-Siefke', thickness: 59.08 },
            { material: 'builtin:SiO2', thickness: 77.08 },
            { material: 'rii:TiO2-Siefke', thickness: 21.73 },
            { material: 'builtin:SiO2', thickness: 75.40 },
            { material: 'rii:TiO2-Siefke', thickness: 58.09 },
            { material: 'builtin:SiO2', thickness: 74.91 },
            { material: 'rii:TiO2-Siefke', thickness: 21.78 },
            { material: 'builtin:SiO2', thickness: 77.50 },
            { material: 'rii:TiO2-Siefke', thickness: 57.87 },
            { material: 'builtin:SiO2', thickness: 77.11 },
            { material: 'rii:TiO2-Siefke', thickness: 22.05 },
            { material: 'builtin:SiO2', thickness: 76.45 },
            { material: 'rii:TiO2-Siefke', thickness: 59.70 },
            { material: 'builtin:SiO2', thickness: 76.93 },
            { material: 'rii:TiO2-Siefke', thickness: 21.92 },
            { material: 'builtin:SiO2', thickness: 75.82 },
            { material: 'rii:TiO2-Siefke', thickness: 60.75 },
            { material: 'builtin:SiO2', thickness: 76.49 },
            { material: 'rii:TiO2-Siefke', thickness: 21.72 },
            { material: 'builtin:SiO2', thickness: 76.52 },
            { material: 'rii:TiO2-Siefke', thickness: 60.61 },
            { material: 'builtin:SiO2', thickness: 76.37 },
            { material: 'rii:TiO2-Siefke', thickness: 21.52 },
            { material: 'builtin:SiO2', thickness: 77.44 },
            { material: 'rii:TiO2-Siefke', thickness: 60.89 },
            { material: 'builtin:SiO2', thickness: 75.71 },
            { material: 'rii:TiO2-Siefke', thickness: 22.02 },
            { material: 'builtin:SiO2', thickness: 76.81 },
            { material: 'rii:TiO2-Siefke', thickness: 60.42 },
            { material: 'builtin:SiO2', thickness: 76.52 },
            { material: 'rii:TiO2-Siefke', thickness: 21.69 },
            { material: 'builtin:SiO2', thickness: 76.34 },
            { material: 'rii:TiO2-Siefke', thickness: 59.56 },
            { material: 'builtin:SiO2', thickness: 75.45 },
            { material: 'rii:TiO2-Siefke', thickness: 21.59 },
            { material: 'builtin:SiO2', thickness: 75.90 },
            { material: 'rii:TiO2-Siefke', thickness: 58.96 },
            { material: 'builtin:SiO2', thickness: 75.13 },
            { material: 'rii:TiO2-Siefke', thickness: 21.77 },
            { material: 'builtin:SiO2', thickness: 75.69 },
            { material: 'rii:TiO2-Siefke', thickness: 59.81 },
            { material: 'builtin:SiO2', thickness: 75.45 },
            { material: 'rii:TiO2-Siefke', thickness: 22.03 },
            { material: 'builtin:SiO2', thickness: 75.79 },
            { material: 'rii:TiO2-Siefke', thickness: 57.13 },
            { material: 'builtin:SiO2', thickness: 75.84 },
            { material: 'rii:TiO2-Siefke', thickness: 22.21 },
            { material: 'builtin:SiO2', thickness: 75.05 },
            { material: 'rii:TiO2-Siefke', thickness: 53.72 },
            { material: 'builtin:SiO2', thickness: 75.89 },
            { material: 'rii:TiO2-Siefke', thickness: 22.51 },
            { material: 'builtin:SiO2', thickness: 74.98 },
            { material: 'rii:TiO2-Siefke', thickness: 55.05 },
            { material: 'builtin:SiO2', thickness: 76.08 },
            { material: 'rii:TiO2-Siefke', thickness: 22.87 },
            { material: 'builtin:SiO2', thickness: 76.03 },
            { material: 'rii:TiO2-Siefke', thickness: 52.56 },
            { material: 'builtin:SiO2', thickness: 75.59 },
            { material: 'rii:TiO2-Siefke', thickness: 23.17 },
            { material: 'builtin:SiO2', thickness: 74.81 },
            { material: 'rii:TiO2-Siefke', thickness: 51.32 },
            { material: 'builtin:SiO2', thickness: 75.69 },
            { material: 'rii:TiO2-Siefke', thickness: 23.60 },
            { material: 'builtin:SiO2', thickness: 75.70 },
            { material: 'rii:TiO2-Siefke', thickness: 51.63 },
            { material: 'builtin:SiO2', thickness: 76.18 },
            { material: 'rii:TiO2-Siefke', thickness: 24.15 },
            { material: 'builtin:SiO2', thickness: 75.62 },
            { material: 'rii:TiO2-Siefke', thickness: 49.80 },
            { material: 'builtin:SiO2', thickness: 76.44 },
            { material: 'rii:TiO2-Siefke', thickness: 24.50 },
            { material: 'builtin:SiO2', thickness: 75.34 },
            { material: 'rii:TiO2-Siefke', thickness: 48.20 },
            { material: 'builtin:SiO2', thickness: 76.24 },
            { material: 'rii:TiO2-Siefke', thickness: 25.07 },
            { material: 'builtin:SiO2', thickness: 76.49 },
            { material: 'rii:TiO2-Siefke', thickness: 47.20 },
            { material: 'builtin:SiO2', thickness: 76.63 },
            { material: 'rii:TiO2-Siefke', thickness: 25.53 },
            { material: 'builtin:SiO2', thickness: 75.75 },
            { material: 'rii:TiO2-Siefke', thickness: 45.47 },
            { material: 'builtin:SiO2', thickness: 74.98 },
            { material: 'rii:TiO2-Siefke', thickness: 25.63 },
            { material: 'builtin:SiO2', thickness: 76.03 },
            { material: 'rii:TiO2-Siefke', thickness: 44.29 },
            { material: 'builtin:SiO2', thickness: 76.03 },
            { material: 'rii:TiO2-Siefke', thickness: 26.45 },
            { material: 'builtin:SiO2', thickness: 76.17 },
            { material: 'rii:TiO2-Siefke', thickness: 43.86 },
            { material: 'builtin:SiO2', thickness: 74.89 },
            { material: 'rii:TiO2-Siefke', thickness: 26.01 },
            { material: 'builtin:SiO2', thickness: 75.12 },
            { material: 'rii:TiO2-Siefke', thickness: 40.74 },
            { material: 'builtin:SiO2', thickness: 74.04 },
            { material: 'rii:TiO2-Siefke', thickness: 25.93 },
            { material: 'builtin:SiO2', thickness: 76.45 },
            { material: 'rii:TiO2-Siefke', thickness: 44.11 },
            { material: 'builtin:SiO2', thickness: 74.10 },
            { material: 'rii:TiO2-Siefke', thickness: 24.70 },
            { material: 'builtin:SiO2', thickness: 56.61 },
            { material: 'rii:TiO2-Siefke', thickness: 76.79 },
            { material: 'builtin:SiO2', thickness: 39.44 },
            { material: 'rii:TiO2-Siefke', thickness: 13.15 },
            { material: 'builtin:SiO2', thickness: 126.51 },
            { material: 'rii:TiO2-Siefke', thickness: 131.94 },
            { material: 'builtin:SiO2', thickness: 60.57 },
            { material: 'rii:TiO2-Siefke', thickness: 35.58 },
            { material: 'builtin:SiO2', thickness: 99.14 },
            { material: 'rii:TiO2-Siefke', thickness: 12.00 },
        ],
        materials: embedded('rii:TiO2-Siefke'),
        spec: [
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', band: 0, target: 0.9, label: 'T min 500-690 nm ≥ 90%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'max', cmp: 'le', band: 1, target: 0.01, label: 'T max 720-780 nm ≤ 1%' },
            { kind: 'EDGE_LAMBDA', channel: 'T', pol: 's', level: 0.5, lambdaStart: 620, lambdaEnd: 780, cmp: 'between', lo: 690, hi: 715, label: 's edge 690-715 nm' },
            { kind: 'EDGE_LAMBDA', channel: 'T', pol: 'p', level: 0.5, lambdaStart: 620, lambdaEnd: 780, cmp: 'between', lo: 690, hi: 715, label: 'p edge 690-715 nm' },
        ],
    },
];
