// High reflectors: quarter-wave dielectric stacks, laser mirrors and
// metal mirrors with dielectric enhancement. Field reference: ../entryModel.js.
import { embedded } from './materials.js';

export const MIRRORS = [
    {
        id: 'hr-1064-hfo2-sio2-25l',
        name: 'HR at 1064 nm, HfO2/SiO2 quarter-wave stack, 25 layers',
        type: 'mirror',
        tags: ['nir', 'laser', 'high-reflector', 'quarter-wave', 'hfo2-sio2', 'normal-incidence', 'fused-silica', 'laser-damage'],
        use: 'Use this as the cavity or turning mirror of a 1064 nm Nd:YAG or Yb fibre laser at normal incidence. Twelve HfO2/SiO2 pairs plus a final high-index layer, all quarter waves at 1064 nm, so it can be run on optical monitoring with one turning point per layer.',
        limitations: 'HfO2 is the choice here for laser damage threshold, not for the highest reflectance per layer: its index contrast against SiO2 is lower than that of TiO2 or Ta2O5, so a HfO2 stack needs more layers for the same reflectance and the high-reflectance zone is narrower. Reflectance falls away outside roughly 960-1170 nm. At 45 degrees the zone shifts to shorter wavelengths and the design no longer holds.',
        source: 'The quarter-wave stack of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2 Multilayer Dielectric Coatings, with high index next to the substrate and outermost. The same section names hafnium oxide as the high-index material used where a high laser damage threshold is required. Thicknesses are exact quarter waves at 1064 nm on the built-in HfO2 and SiO2 data; no refinement was needed to meet the specification below.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1064,
        band: [1040, 1090],
        aoi: 0,
        polarization: 'avg',
        preview: [900, 1300],
        layers: [
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
            { material: 'builtin:SiO2', thickness: 183.49 },
            { material: 'builtin:HfO2', thickness: 135.17 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.998, label: 'R min ≥ 99.8%' },
        ],
    },
    {
        id: 'hr-532-nb2o5-sio2-17l',
        name: 'HR at 532 nm, Nb2O5/SiO2 quarter-wave stack, 17 layers',
        type: 'mirror',
        tags: ['visible', 'laser', 'high-reflector', 'quarter-wave', 'nb2o5-sio2', 'normal-incidence', 'glass', 'low-loss'],
        use: 'Use this as a turning or cavity mirror for a 532 nm beam on a glass substrate. Eight Nb2O5/SiO2 pairs plus a final high-index layer reach the reflectance of a metal mirror without the absorption.',
        limitations: 'The high-reflectance zone runs roughly 470-610 nm and the coating is transparent outside it, so it does not block stray light elsewhere in the visible. The built-in Nb2O5 data stops at 1000 nm, so nothing is claimed in the near infrared.',
        source: 'The quarter-wave stack of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2 Multilayer Dielectric Coatings, with high index next to the substrate and outermost. Thicknesses are exact quarter waves at 532 nm on the built-in Nb2O5 and SiO2 data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 532,
        band: [515, 550],
        aoi: 0,
        polarization: 'avg',
        preview: [420, 700],
        layers: [
            { material: 'builtin:Nb2O5', thickness: 56.07 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Nb2O5', thickness: 56.07 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Nb2O5', thickness: 56.07 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Nb2O5', thickness: 56.07 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Nb2O5', thickness: 56.07 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Nb2O5', thickness: 56.07 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Nb2O5', thickness: 56.07 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Nb2O5', thickness: 56.07 },
            { material: 'builtin:SiO2', thickness: 91.05 },
            { material: 'builtin:Nb2O5', thickness: 56.07 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.998, label: 'R min ≥ 99.8%' },
        ],
    },
    {
        id: 'hr-633-tio2-sio2-15l',
        name: 'HR at 633 nm, TiO2/SiO2 quarter-wave stack, 15 layers',
        type: 'mirror',
        tags: ['visible', 'laser', 'high-reflector', 'quarter-wave', 'tio2-sio2', 'all-dielectric', 'normal-incidence', 'glass'],
        use: 'Use this as a HeNe or 633 nm diode turning mirror. The TiO2/SiO2 index contrast is high enough that seven pairs plus a final high-index layer already give a wide, deep reflectance zone.',
        limitations: 'The high-reflectance zone runs roughly 540-750 nm and the coating is transparent outside it. The built-in TiO2 data covers 370-827 nm, so nothing is claimed beyond that.',
        source: 'The quarter-wave stack of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2 Multilayer Dielectric Coatings, with high index next to the substrate and outermost. Thicknesses are exact quarter waves at 633 nm on the built-in TiO2 and SiO2 data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 633,
        band: [610, 660],
        aoi: 0,
        polarization: 'avg',
        preview: [450, 820],
        layers: [
            { material: 'builtin:TiO2', thickness: 64.06 },
            { material: 'builtin:SiO2', thickness: 108.61 },
            { material: 'builtin:TiO2', thickness: 64.06 },
            { material: 'builtin:SiO2', thickness: 108.61 },
            { material: 'builtin:TiO2', thickness: 64.06 },
            { material: 'builtin:SiO2', thickness: 108.61 },
            { material: 'builtin:TiO2', thickness: 64.06 },
            { material: 'builtin:SiO2', thickness: 108.61 },
            { material: 'builtin:TiO2', thickness: 64.06 },
            { material: 'builtin:SiO2', thickness: 108.61 },
            { material: 'builtin:TiO2', thickness: 64.06 },
            { material: 'builtin:SiO2', thickness: 108.61 },
            { material: 'builtin:TiO2', thickness: 64.06 },
            { material: 'builtin:SiO2', thickness: 108.61 },
            { material: 'builtin:TiO2', thickness: 64.06 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.998, label: 'R min ≥ 99.8%' },
        ],
    },
    {
        id: 'hr-broadband-450-700-tio2-sio2-29l',
        name: 'Broadband HR 450-700 nm, TiO2/SiO2, 29 layers',
        type: 'mirror',
        tags: ['visible', 'broadband', 'imaging', 'high-reflector', 'all-dielectric', 'tio2-sio2', 'normal-incidence', 'glass'],
        use: 'Use this where a dielectric mirror has to hold across the whole visible band rather than at one laser line, for example a fold mirror in a white-light or multi-line instrument that must not tint the beam.',
        limitations: 'Reflectance collapses below 440 nm and above 710 nm, and the layer thicknesses run from 38 to 119 nm with no repeating period, so this coating needs thickness monitoring rather than turning-point monitoring. Twenty-nine layers of TiO2 build up stress; expect to control substrate temperature.',
        source: 'Two quarter-wave stacks at different reference wavelengths on one substrate, the construction of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2.1 All-Dielectric Multilayers with Extended High-Reflectance Zones (after Turner and Baumeister). Seven pairs at 670 nm next to the substrate and seven at 485 nm above them, then every thickness refined in TFStudio against zero transmittance over 450-700 nm.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        band: [450, 700],
        aoi: 0,
        polarization: 'avg',
        preview: [400, 800],
        layers: [
            { material: 'builtin:TiO2', thickness: 65.29 },
            { material: 'builtin:SiO2', thickness: 118.65 },
            { material: 'builtin:TiO2', thickness: 68.90 },
            { material: 'builtin:SiO2', thickness: 106.92 },
            { material: 'builtin:TiO2', thickness: 61.76 },
            { material: 'builtin:SiO2', thickness: 111.26 },
            { material: 'builtin:TiO2', thickness: 69.23 },
            { material: 'builtin:SiO2', thickness: 108.19 },
            { material: 'builtin:TiO2', thickness: 59.84 },
            { material: 'builtin:SiO2', thickness: 104.27 },
            { material: 'builtin:TiO2', thickness: 64.32 },
            { material: 'builtin:SiO2', thickness: 114.00 },
            { material: 'builtin:TiO2', thickness: 61.24 },
            { material: 'builtin:SiO2', thickness: 100.36 },
            { material: 'builtin:TiO2', thickness: 55.14 },
            { material: 'builtin:SiO2', thickness: 96.39 },
            { material: 'builtin:TiO2', thickness: 53.01 },
            { material: 'builtin:SiO2', thickness: 90.30 },
            { material: 'builtin:TiO2', thickness: 45.73 },
            { material: 'builtin:SiO2', thickness: 68.62 },
            { material: 'builtin:TiO2', thickness: 43.49 },
            { material: 'builtin:SiO2', thickness: 86.77 },
            { material: 'builtin:TiO2', thickness: 51.45 },
            { material: 'builtin:SiO2', thickness: 91.17 },
            { material: 'builtin:TiO2', thickness: 50.21 },
            { material: 'builtin:SiO2', thickness: 78.73 },
            { material: 'builtin:TiO2', thickness: 38.48 },
            { material: 'builtin:SiO2', thickness: 70.67 },
            { material: 'builtin:TiO2', thickness: 47.85 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.995, label: 'R min ≥ 99.5%' },
        ],
    },
    {
        id: 'mirror-protected-silver-sio2',
        name: 'Protected silver mirror, quarter-wave SiO2 overcoat',
        type: 'mirror',
        tags: ['visible', 'broadband', 'imaging', 'high-reflector', 'protected-metal', 'silver', 'normal-incidence', 'glass'],
        use: 'Use this where a mirror has to be broadband and flat rather than very high in reflectance, and where the part will be handled or cleaned. Two layers, one metal run and one oxide run.',
        limitations: 'Reflectance sits near 97%, below any dielectric stack, and silver absorbs the rest. A single quarter-wave oxide slows tarnishing but does not stop it: production silver mirrors add adhesion and barrier layers that are not in this design. Silver reflectance collapses below about 400 nm.',
        source: 'Macleod, Thin-Film Optical Filters, 5th ed., section 5.1.2 Protection of Metal Films, which shows that a low-index protecting layer costs least reflectance, and chapter 10, which states that silver is usually overcoated with a quarter-wave protective layer. The silver is 100 nm, thick enough to be opaque; the overcoat is an exact quarter wave of SiO2 at 550 nm on the built-in data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 550,
        band: [450, 700],
        aoi: 0,
        polarization: 'avg',
        preview: [380, 900],
        layers: [
            { material: 'builtin:Ag', thickness: 100.00 },
            { material: 'builtin:SiO2', thickness: 94.18 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.97, label: 'R avg ≥ 97%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.96, label: 'R min ≥ 96%' },
        ],
    },
    {
        id: 'hr-532-45deg-tio2-sio2-17l',
        name: 'HR at 532 nm for 45 degrees, TiO2/SiO2 quarter-wave stack, 17 layers',
        type: 'mirror',
        tags: ['visible', 'laser', 'high-reflector', 'quarter-wave', 'tio2-sio2', '45-degree', 'oblique', 'glass'],
        use: 'Use this as the fold mirror that turns a 532 nm beam through 90 degrees on a breadboard or inside a laser head. It is the same quarter-wave stack as a normal-incidence mirror, but referenced to 600 nm so the reflectance zone lands on 532 nm once the mirror is tilted.',
        limitations: 'Written for 45 degrees. At normal incidence the reflectance zone sits around 600 nm and 532 nm falls near its edge, so this mirror is not interchangeable with the normal-incidence one. At 45 degrees s and p reflect differently on the shoulders of the zone; the claim here is the average.',
        source: 'The quarter-wave stack of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2, with the tilt shift of section 9.2 Tilted Thicknesses applied by moving the reference wavelength from 532 to 600 nm. Eight TiO2/SiO2 pairs plus a final high-index layer, exact quarter waves at 600 nm on the built-in data; the stack meets the specification below as designed.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 600,
        band: [522, 542],
        aoi: 45,
        polarization: 'avg',
        preview: [450, 750],
        layers: [
            { material: 'builtin:TiO2', thickness: 60.35 },
            { material: 'builtin:SiO2', thickness: 102.88 },
            { material: 'builtin:TiO2', thickness: 60.35 },
            { material: 'builtin:SiO2', thickness: 102.88 },
            { material: 'builtin:TiO2', thickness: 60.35 },
            { material: 'builtin:SiO2', thickness: 102.88 },
            { material: 'builtin:TiO2', thickness: 60.35 },
            { material: 'builtin:SiO2', thickness: 102.88 },
            { material: 'builtin:TiO2', thickness: 60.35 },
            { material: 'builtin:SiO2', thickness: 102.88 },
            { material: 'builtin:TiO2', thickness: 60.35 },
            { material: 'builtin:SiO2', thickness: 102.88 },
            { material: 'builtin:TiO2', thickness: 60.35 },
            { material: 'builtin:SiO2', thickness: 102.88 },
            { material: 'builtin:TiO2', thickness: 60.35 },
            { material: 'builtin:SiO2', thickness: 102.88 },
            { material: 'builtin:TiO2', thickness: 60.35 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.995, label: 'R min ≥ 99.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', pol: 's', target: 0.995, label: 'Rs min ≥ 99.5%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', pol: 'p', target: 0.99, label: 'Rp min ≥ 99%' },
        ],
    },
    {
        id: 'hr-1550-hfo2-sio2-25l',
        name: 'HR at 1550 nm, HfO2/SiO2 quarter-wave stack, 25 layers',
        type: 'mirror',
        tags: ['nir', 'telecom', 'laser', 'high-reflector', 'quarter-wave', 'hfo2-sio2', 'normal-incidence', 'fused-silica'],
        use: 'Use this as a cavity or fold mirror for an erbium fibre laser, a 1550 nm lidar transmitter, or a free-space telecom bench. Twelve HfO2/SiO2 pairs plus a final high-index layer at normal incidence.',
        limitations: 'The high-reflectance zone runs roughly 1400-1700 nm and the coating is transparent outside it. HfO2 was chosen over Ta2O5 because the built-in Ta2O5 data carries enough extinction at 1550 nm to hold a stack of this depth below 99.2% reflectance; the residual absorption here is that of the built-in HfO2 data.',
        source: 'The quarter-wave stack of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2 Multilayer Dielectric Coatings, with high index next to the substrate and outermost. Exact quarter waves at 1550 nm on the built-in HfO2 and SiO2 data; HfO2 rather than Ta2O5 because the built-in Ta2O5 carries measurable extinction at 1550 nm.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1550,
        band: [1520, 1580],
        aoi: 0,
        polarization: 'avg',
        preview: [1300, 1850],
        layers: [
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
            { material: 'builtin:SiO2', thickness: 268.35 },
            { material: 'builtin:HfO2', thickness: 198.07 },
        ],
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.998, label: 'R min ≥ 99.8%' },
            { kind: 'A_AVG', channel: 'A', cmp: 'le', target: 0.001, label: 'A avg ≤ 0.1%' },
        ],
    },
    {
        id: 'mirror-gold-nir-cr-au',
        name: 'Gold mirror for 1000-1900 nm, chromium adhesion layer',
        type: 'mirror',
        tags: ['nir', 'swir', 'broadband', 'high-reflector', 'metal', 'gold', 'normal-incidence', 'glass'],
        use: 'Use this where a mirror has to be flat and broad across the near and short-wave infrared and no dielectric stack is wide enough: Fourier-transform spectrometer optics, a broadband beam path, or a fold mirror shared by several infrared sources.',
        limitations: 'The gold is bare and scratches if wiped; a real part needs a dielectric overcoat, which changes the reflectance a little. The chromium is an adhesion layer buried under opaque gold and does nothing optically. Gold reflectance collapses below about 550 nm, and the claim stops at 1900 nm because the built-in gold data ends at 1937 nm.',
        source: 'Macleod, Thin-Film Optical Filters, 5th ed., section 5.1.1 Metallic Layers, where Figure 5.1 shows the reflectance of freshly deposited gold rising above 96% beyond 700 nm and staying there through the infrared. The gold is 120 nm, thick enough to be opaque, over a 3 nm chromium adhesion layer, on a glass substrate so the whole band stays inside the built-in material data.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 1450,
        band: [1000, 1900],
        aoi: 0,
        polarization: 'avg',
        preview: [600, 1900],
        layers: [
            { material: 'builtin:Cr', thickness: 3.00 },
            { material: 'builtin:Au', thickness: 120.00 },
        ],
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.97, label: 'R avg ≥ 97%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.97, label: 'R min ≥ 97%' },
        ],
    },
    {
        id: 'hr-248-45deg-hfo2-sio2-caf2-33l',
        name: 'HR at 248 nm for 45 degrees, HfO2/SiO2 on CaF2, 33 layers',
        type: 'mirror',
        tags: ['uv', 'uv-grade', 'laser', 'high-reflector', 'quarter-wave', 'hfo2-sio2', '45-degree', 'oblique'],
        use: 'Use this as the fold mirror of a KrF excimer beam line at 248 nm. Calcium fluoride is the substrate because it stays transparent and stays clean this far into the ultraviolet, and the stack is referenced to 270 nm so the reflectance zone lands on 248 nm once the mirror is tilted.',
        limitations: 'The hafnia data used here is a deep-ultraviolet film measurement that reports no extinction at 248 nm. A real ALD or e-beam hafnia film does absorb a little there, so the reflectance shown is an upper bound and a real mirror will run a few tenths of a percent lower. Calcium fluoride cleaves and is hygroscopic in humid air. Written for 45 degrees only.',
        source: 'Sixteen HfO2/SiO2 quarter-wave pairs plus a final high-index layer at a reference wavelength of 270 nm on calcium fluoride, the tilted quarter-wave stack of Macleod, Thin-Film Optical Filters, 5th ed., sections 6.2 and 9.2. HfO2 rather than Al2O3 as the high index nearly doubles the index contrast at 248 nm and keeps the stack to 33 layers; it meets the specification below as designed. The CaF2 substrate and both films travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:CaF2-Li',
        referenceWavelength: 270,
        bands: [[243,253]],
        aoi: 45,
        polarization: 'avg',
        preview: [210,350],
        layers: [
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
            { material: 'rii:SiO2-Franta', thickness: 45.02 },
            { material: 'rii:HfO2-Siefke', thickness: 32.28 },
        ],
        materials: embedded('rii:CaF2-Li', 'rii:HfO2-Siefke', 'rii:SiO2-Franta'),
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.995, label: 'R min ≥ 99.5%' },
        ],
    },
    {
        id: 'hr-355-45deg-zro2-sio2-25l',
        name: 'HR at 355 nm for 45 degrees, ZrO2/SiO2, 25 layers',
        type: 'mirror',
        tags: ['uv', 'uv-grade', 'laser', 'high-reflector', 'quarter-wave', 'all-dielectric', '45-degree', 'fused-silica'],
        use: 'Use this as the fold mirror for the third harmonic of a Nd:YAG laser at 355 nm. Zirconia against silica keeps a useful index contrast this far into the ultraviolet, where the oxides used in the visible either stop transmitting or lose their contrast.',
        limitations: 'The zirconia data used here reports no extinction at 355 nm; a real film absorbs a little, so the reflectance shown is an upper bound. Written for 45 degrees: at normal incidence the reflectance zone sits near 395 nm and 355 nm falls off its edge.',
        source: 'Twelve ZrO2/SiO2 quarter-wave pairs plus a final high-index layer at a reference wavelength of 395 nm, the tilted quarter-wave stack of Macleod, Thin-Film Optical Filters, 5th ed., sections 6.2 and 9.2. ZrO2 rather than HfO2 because the built-in hafnia data begins at 385 nm and the refractiveindex.info hafnia sets that reach 355 nm carry extinction there; it meets the specification below as designed. Both films travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 395,
        bands: [[350,360]],
        aoi: 45,
        polarization: 'avg',
        preview: [300,500],
        layers: [
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
            { material: 'rii:SiO2-Franta', thickness: 67.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.58 },
        ],
        materials: embedded('rii:ZrO2-Synowicki', 'rii:SiO2-Franta'),
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.995, label: 'R min ≥ 99.5%' },
        ],
    },
    {
        id: 'hr-1064-tio2-sio2-21l',
        name: 'HR at 1064 nm, TiO2/SiO2 quarter-wave stack, 21 layers',
        type: 'mirror',
        tags: ['nir', 'laser', 'high-reflector', 'quarter-wave', 'tio2-sio2', 'all-dielectric', 'normal-incidence', 'glass'],
        use: 'Use this as a 1064 nm mirror when the coating shop runs TiO2 and SiO2 rather than hafnia. The higher index contrast reaches the same reflectance as the hafnia stack in twenty-one layers instead of twenty-five, and the high-reflectance zone is wider.',
        limitations: 'Titania has a much lower laser damage threshold than hafnia, so this is the mirror for a low-power or continuous-wave 1064 nm beam, not for a Q-switched one. Use the HfO2/SiO2 stack where damage threshold decides. The titania data is carried with the entry because the built-in TiO2 stops at 827 nm.',
        source: 'Ten TiO2/SiO2 quarter-wave pairs plus a final high-index layer, exact quarter waves at 1064 nm, the quarter-wave stack of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2; it meets the specification below as designed. Both films travel with the entry as measured data from refractiveindex.info because the built-in TiO2 data ends at 827 nm.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 1064,
        bands: [[1044,1084]],
        aoi: 0,
        polarization: 'avg',
        preview: [900,1300],
        layers: [
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
            { material: 'rii:SiO2-Franta', thickness: 183.46 },
            { material: 'rii:TiO2-Franta', thickness: 119.25 },
        ],
        materials: embedded('rii:TiO2-Franta', 'rii:SiO2-Franta'),
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.998, label: 'R min ≥ 99.8%' },
        ],
    },
    {
        id: 'hr-multiline-355-532-1064-45deg-zro2-sio2-67l',
        name: 'Multi-line Nd:YAG mirror 355, 532 and 1064 nm at 45 degrees, ZrO2/SiO2, 67 layers',
        type: 'mirror',
        tags: ['uv', 'visible', 'nir', 'multi-band', 'laser', 'high-reflector', 'all-dielectric', '45-degree'],
        use: 'Use this as the fold mirror of a Nd:YAG harmonic bench that has to turn the fundamental and both harmonics on one optic, so the three beams stay aligned to each other through the same mount.',
        limitations: 'Three stacked quarter-wave stacks make a coating almost seven micrometres deep, with stress and run time to match, and every layer needs thickness monitoring rather than turning-point monitoring. The zirconia data reports no extinction at 355 nm where a real film absorbs a little, so the ultraviolet reflectance is an upper bound. Nothing is claimed between the three bands.',
        source: 'Three ZrO2/SiO2 quarter-wave stacks on one substrate, referenced to 1183, 592 and 395 nm so each lands on its line at 45 degrees, in the manner of Macleod, Thin-Film Optical Filters, 5th ed., section 6.2.1; every thickness was then refined in TFStudio against the specification below. Both films travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 592,
        bands: [[350,360],[522,542],[1044,1084]],
        aoi: 45,
        polarization: 'avg',
        preview: [300,1250],
        layers: [
            { material: 'rii:ZrO2-Synowicki', thickness: 139.02 },
            { material: 'rii:SiO2-Franta', thickness: 206.39 },
            { material: 'rii:ZrO2-Synowicki', thickness: 139.15 },
            { material: 'rii:SiO2-Franta', thickness: 206.99 },
            { material: 'rii:ZrO2-Synowicki', thickness: 138.32 },
            { material: 'rii:SiO2-Franta', thickness: 207.63 },
            { material: 'rii:ZrO2-Synowicki', thickness: 138.93 },
            { material: 'rii:SiO2-Franta', thickness: 208.40 },
            { material: 'rii:ZrO2-Synowicki', thickness: 139.04 },
            { material: 'rii:SiO2-Franta', thickness: 208.17 },
            { material: 'rii:ZrO2-Synowicki', thickness: 137.43 },
            { material: 'rii:SiO2-Franta', thickness: 207.29 },
            { material: 'rii:ZrO2-Synowicki', thickness: 136.70 },
            { material: 'rii:SiO2-Franta', thickness: 207.19 },
            { material: 'rii:ZrO2-Synowicki', thickness: 138.96 },
            { material: 'rii:SiO2-Franta', thickness: 207.80 },
            { material: 'rii:ZrO2-Synowicki', thickness: 142.03 },
            { material: 'rii:SiO2-Franta', thickness: 206.94 },
            { material: 'rii:ZrO2-Synowicki', thickness: 141.33 },
            { material: 'rii:SiO2-Franta', thickness: 204.29 },
            { material: 'rii:ZrO2-Synowicki', thickness: 138.78 },
            { material: 'rii:SiO2-Franta', thickness: 202.48 },
            { material: 'rii:ZrO2-Synowicki', thickness: 68.19 },
            { material: 'rii:SiO2-Franta', thickness: 98.56 },
            { material: 'rii:ZrO2-Synowicki', thickness: 64.38 },
            { material: 'rii:SiO2-Franta', thickness: 103.29 },
            { material: 'rii:ZrO2-Synowicki', thickness: 71.54 },
            { material: 'rii:SiO2-Franta', thickness: 99.76 },
            { material: 'rii:ZrO2-Synowicki', thickness: 64.47 },
            { material: 'rii:SiO2-Franta', thickness: 103.52 },
            { material: 'rii:ZrO2-Synowicki', thickness: 72.74 },
            { material: 'rii:SiO2-Franta', thickness: 99.32 },
            { material: 'rii:ZrO2-Synowicki', thickness: 62.74 },
            { material: 'rii:SiO2-Franta', thickness: 103.58 },
            { material: 'rii:ZrO2-Synowicki', thickness: 73.03 },
            { material: 'rii:SiO2-Franta', thickness: 98.16 },
            { material: 'rii:ZrO2-Synowicki', thickness: 61.71 },
            { material: 'rii:SiO2-Franta', thickness: 104.14 },
            { material: 'rii:ZrO2-Synowicki', thickness: 72.55 },
            { material: 'rii:SiO2-Franta', thickness: 97.22 },
            { material: 'rii:ZrO2-Synowicki', thickness: 62.81 },
            { material: 'rii:SiO2-Franta', thickness: 105.69 },
            { material: 'rii:ZrO2-Synowicki', thickness: 72.95 },
            { material: 'rii:SiO2-Franta', thickness: 98.76 },
            { material: 'rii:ZrO2-Synowicki', thickness: 46.09 },
            { material: 'rii:SiO2-Franta', thickness: 69.15 },
            { material: 'rii:ZrO2-Synowicki', thickness: 31.50 },
            { material: 'rii:SiO2-Franta', thickness: 61.02 },
            { material: 'rii:ZrO2-Synowicki', thickness: 45.56 },
            { material: 'rii:SiO2-Franta', thickness: 67.86 },
            { material: 'rii:ZrO2-Synowicki', thickness: 51.22 },
            { material: 'rii:SiO2-Franta', thickness: 69.75 },
            { material: 'rii:ZrO2-Synowicki', thickness: 32.37 },
            { material: 'rii:SiO2-Franta', thickness: 63.06 },
            { material: 'rii:ZrO2-Synowicki', thickness: 45.78 },
            { material: 'rii:SiO2-Franta', thickness: 67.89 },
            { material: 'rii:ZrO2-Synowicki', thickness: 51.91 },
            { material: 'rii:SiO2-Franta', thickness: 68.57 },
            { material: 'rii:ZrO2-Synowicki', thickness: 32.59 },
            { material: 'rii:SiO2-Franta', thickness: 64.45 },
            { material: 'rii:ZrO2-Synowicki', thickness: 44.86 },
            { material: 'rii:SiO2-Franta', thickness: 67.52 },
            { material: 'rii:ZrO2-Synowicki', thickness: 51.28 },
            { material: 'rii:SiO2-Franta', thickness: 66.69 },
            { material: 'rii:ZrO2-Synowicki', thickness: 33.39 },
            { material: 'rii:SiO2-Franta', thickness: 65.71 },
            { material: 'rii:ZrO2-Synowicki', thickness: 43.38 },
        ],
        materials: embedded('rii:ZrO2-Synowicki', 'rii:SiO2-Franta'),
        spec: [
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', band: 0, target: 0.99, label: 'R min at 355 nm ≥ 99%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', band: 1, target: 0.99, label: 'R min at 532 nm ≥ 99%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', band: 2, target: 0.99, label: 'R min at 1064 nm ≥ 99%' },
        ],
    },
    {
        id: 'mirror-protected-aluminium-mgf2',
        name: 'Protected aluminium mirror, half-wave MgF2 overcoat',
        type: 'mirror',
        tags: ['visible', 'broadband', 'imaging', 'astronomy', 'protected-metal', 'aluminium', 'normal-incidence', 'fused-silica'],
        use: 'Use this as the general-purpose front-surface mirror: telescope optics, a fold mirror in a white-light instrument, anything that has to reflect the whole visible band and be cleanable. Aluminium is the cheapest broadband reflector and the only one that keeps working into the ultraviolet.',
        limitations: 'Aluminium reflects about 91% in the visible against 98% for silver, and the protective layer costs another point, so this mirror is for breadth and durability rather than throughput. A half wave was chosen over a quarter wave because a quarter wave puts a deeper dip in the middle of the visible.',
        source: 'Opaque aluminium, 100 nm, under an exact half wave of MgF2 at 550 nm; Macleod, Thin-Film Optical Filters, 5th ed., chapter 10, states that aluminium is overcoated with a half wave where luminous reflectance is what matters, and section 5.1.2 shows why a low-index protecting layer costs least. The aluminium travels with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 550,
        bands: [[400,700]],
        aoi: 0,
        polarization: 'avg',
        preview: [350,900],
        layers: [
            { material: 'rii:Al-McPeak', thickness: 100.00 },
            { material: 'builtin:MgF2', thickness: 199.49 },
        ],
        materials: embedded('rii:Al-McPeak'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.88, label: 'R avg ≥ 88%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.85, label: 'R min ≥ 85%' },
        ],
    },
    {
        id: 'mirror-gold-1-20um-silicon',
        name: 'Gold mirror for 1-20 um on silicon, chromium adhesion layer',
        type: 'mirror',
        tags: ['nir', 'swir', 'mwir', 'lwir', 'broadband', 'high-reflector', 'metal', 'gold'],
        use: 'Use this as the workhorse fold or collimating mirror of an infrared bench: a Fourier-transform spectrometer, a thermal-imaging test rig, or any path that has to stay flat from the near infrared out to twenty micrometres. A silicon substrate keeps the figure stable and conducts heat away.',
        limitations: 'The gold is bare and scratches if wiped; a real part needs a dielectric overcoat, which is the next entry. The chromium is an adhesion layer buried under opaque gold and does nothing optically. Gold reflectance collapses below about 550 nm, so this is not a visible mirror.',
        source: 'Opaque gold, 150 nm, over a 3 nm chromium adhesion layer on silicon; Macleod, Thin-Film Optical Filters, 5th ed., section 5.1.1, Figure 5.1, shows gold reflectance staying above 96% through the infrared. The silicon substrate, the chromium and the gold all travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:Si-Franta',
        referenceWavelength: 10000,
        bands: [[1000,20000]],
        aoi: 0,
        polarization: 'avg',
        preview: [1000,20000],
        layers: [
            { material: 'rii:Cr-Rakic', thickness: 3.00 },
            { material: 'rii:Au-Ordal', thickness: 150.00 },
        ],
        materials: embedded('rii:Si-Franta', 'rii:Cr-Rakic', 'rii:Au-Ordal'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.98, label: 'R avg ≥ 98%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.97, label: 'R min ≥ 97%' },
        ],
    },
    {
        id: 'mirror-protected-gold-zns-1-12um-silicon',
        name: 'Protected gold mirror for 1-12 um on silicon, ZnS overcoat',
        type: 'mirror',
        tags: ['nir', 'swir', 'mwir', 'lwir', 'broadband', 'high-reflector', 'protected-metal', 'gold'],
        use: 'Use this where a gold infrared mirror has to be handled or cleaned: a scanner mirror, a field instrument, or anything mounted where a cloth will eventually touch it. Two hundred nanometres of zinc sulphide is hard enough to protect the gold and thin enough to leave most of its reflectance.',
        limitations: 'The overcoat costs about a point of reflectance on average and puts interference dips in the band, the deepest reaching about 94%. The band stops at 12 um because that is where the zinc sulphide data ends; bare gold goes further, and the previous entry covers it.',
        source: 'Opaque gold on a chromium adhesion layer with a 200 nm zinc sulphide overcoat, about a quarter wave at 1.8 um; the single dielectric layer on a metal of Macleod, Thin-Film Optical Filters, 5th ed., section 5.1.2. The silicon substrate, chromium, gold and ZnS all travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:Si-Franta',
        referenceWavelength: 6500,
        bands: [[1000,12000]],
        aoi: 0,
        polarization: 'avg',
        preview: [1000,13000],
        layers: [
            { material: 'rii:Cr-Rakic', thickness: 3.00 },
            { material: 'rii:Au-Ordal', thickness: 150.00 },
            { material: 'rii:ZnS-Amotchkina', thickness: 200.00 },
        ],
        materials: embedded('rii:Si-Franta', 'rii:Cr-Rakic', 'rii:Au-Ordal', 'rii:ZnS-Amotchkina'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.97, label: 'R avg ≥ 97%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.93, label: 'R min ≥ 93%' },
        ],
    },
    {
        id: 'mirror-protected-silver-swir-al2o3',
        name: 'Protected silver mirror for 0.8-5 um, quarter-wave Al2O3 overcoat',
        type: 'mirror',
        tags: ['nir', 'swir', 'mwir', 'broadband', 'high-reflector', 'protected-metal', 'silver', 'fused-silica'],
        use: 'Use this where an infrared mirror has to beat gold on reflectance and still cover the near and short-wave infrared: a spectrometer fold mirror, a beam-expander secondary, or the collection optics of a short-wave camera.',
        limitations: 'Silver tarnishes and the single alumina overcoat only slows it; production silver mirrors add adhesion and barrier layers that this design does not include. The band stops at 5 um because that is where the silver data ends. Silver reflectance collapses below about 400 nm.',
        source: 'Opaque silver under an exact quarter wave of alumina at 1.5 um, the arrangement Macleod, Thin-Film Optical Filters, 5th ed., chapter 10, gives for protecting silver; the band is 0.8-5 um to stay inside the silver dataset. The silver and alumina films travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1500,
        bands: [[800,5000]],
        aoi: 0,
        polarization: 'avg',
        preview: [700,5100],
        layers: [
            { material: 'rii:Ag-Yang', thickness: 120.00 },
            { material: 'rii:Al2O3-Boidin', thickness: 225.99 },
        ],
        materials: embedded('rii:Ag-Yang', 'rii:Al2O3-Boidin'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.98, label: 'R avg ≥ 98%' },
            { kind: 'MIN_MAX', channel: 'R', direction: 'min', cmp: 'ge', target: 0.97, label: 'R min ≥ 97%' },
        ],
    },
    {
        id: 'mirror-co2-gold-silicon',
        name: 'CO2 laser mirror at 10.6 um, gold on silicon',
        type: 'mirror',
        tags: ['lwir', 'single-wavelength', 'laser', 'high-reflector', 'metal', 'gold', 'normal-incidence'],
        use: 'Use this as the beam-delivery or cavity fold mirror of a CO2 laser. Gold on a silicon blank is what a cutting head runs: silicon carries the heat away and gold reflects better than any other metal at 10.6 um.',
        limitations: 'About one percent of the beam is absorbed, which at kilowatt powers means the mirror has to be water cooled. The gold is bare and cannot be wiped. A dielectric enhancing stack would push reflectance above 99.5% and is what a high-power head actually uses.',
        source: 'Opaque gold on a chromium adhesion layer on silicon; Macleod, Thin-Film Optical Filters, 5th ed., section 5.1.1. The silicon substrate, chromium and gold travel with the entry as measured data from refractiveindex.info.',
        incidentMedium: 'builtin:Air',
        substrate: 'rii:Si-Franta',
        referenceWavelength: 10600,
        bands: [[10500,10700]],
        aoi: 0,
        polarization: 'avg',
        preview: [9000,12000],
        layers: [
            { material: 'rii:Cr-Rakic', thickness: 3.00 },
            { material: 'rii:Au-Ordal', thickness: 150.00 },
        ],
        materials: embedded('rii:Si-Franta', 'rii:Cr-Rakic', 'rii:Au-Ordal'),
        spec: [
            { kind: 'R_AVG', channel: 'R', cmp: 'ge', target: 0.985, label: 'R avg ≥ 98.5%' },
            { kind: 'A_AVG', channel: 'A', cmp: 'le', target: 0.015, label: 'A avg ≤ 1.5%' },
        ],
    },
];
