// Coatings outside the other families: transparent conductors, thermochromic
// and similar single-purpose films. Field reference: ../entryModel.js.
import { embedded } from './materials.js';

export const OTHER = [
    {
        id: 'ito-transparent-conductive-glass',
        name: 'ITO transparent conductive coating on glass, 150 nm',
        type: 'other',
        tags: ['visible', 'nir', 'display', 'solar', 'single-layer', 'normal-incidence', 'glass'],
        use: 'Use this as the starting point for a transparent electrode or an antistatic window: a touch panel, a heated viewport, or an electrode on a display cover glass. Indium tin oxide is the only material in the library that conducts and still passes the visible band.',
        limitations: 'This is a conductor, not a heat mirror. The free-carrier reflection edge that makes ITO useful for solar control sits beyond the 1.7 um limit of the dataset, so nothing is claimed there; inside 0.8 to 1.2 um the film absorbs rather than reflects, and that absorption is what the headline numbers show. A bare 150 nm layer also adds visible reflectance, which a real touch panel cancels with an index-matching stack under it.',
        source: 'A 150 nm ITO film on the built-in BK7 substrate, a typical transparent-conductor thickness. The ITO film travels with the entry as measured data from refractiveindex.info because the built-in ITO stops at 1000 nm.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:BK7',
        referenceWavelength: 1000,
        bands: [[420,700],[800,1200]],
        aoi: 0,
        polarization: 'avg',
        preview: [400,1600],
        layers: [
            { material: 'rii:ITO-Minenkov', thickness: 150.00 },
        ],
        materials: embedded('rii:ITO-Minenkov'),
        spec: [
            { kind: 'T_AVG', channel: 'T', cmp: 'ge', band: 0, target: 0.85, label: 'T avg visible ≥ 85%' },
            { kind: 'T_AVG', channel: 'T', cmp: 'ge', band: 1, target: 0.80, label: 'T avg 800-1200 nm ≥ 80%' },
        ],
    },
    {
        id: 'vo2-thermochromic-sapphire',
        name: 'VO2 thermochromic film on sapphire, 80 nm, cold state',
        type: 'other',
        tags: ['nir', 'swir', 'mwir', 'solar', 'glazing', 'single-layer', 'normal-incidence', 'sapphire'],
        use: 'Use this as the starting point for a thermochromic window or a passive thermal switch. Vanadium dioxide changes from a semiconductor to a metal near 68 degrees C, so the same film passes the infrared when it is cold and blocks it when it is hot.',
        limitations: 'An entry carries one set of optical constants, so this one describes the cold semiconducting film only. Swapping the layer to the 100 degree C dataset of the same measurement drops average transmittance over 1.5 to 5 um from about 66% to about 7%, which is the switch this coating is for; build that as a second design to see both states. A bare 80 nm film also reflects and absorbs a good deal even when cold, which is why the cold transmittance is far from a clear window.',
        source: 'An 80 nm vanadium dioxide film on the built-in sapphire substrate. The film travels with the entry as measured data from refractiveindex.info, from the 25 degree C measurement of the same study that supplies the 100 degree C metallic state.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:Al2O3',
        referenceWavelength: 3000,
        bands: [[1500,5000]],
        aoi: 0,
        polarization: 'avg',
        preview: [1000,5400],
        layers: [
            { material: 'rii:VO2-25C', thickness: 80.00 },
        ],
        materials: embedded('rii:VO2-25C'),
        spec: [
            { kind: 'T_AVG', channel: 'T', cmp: 'ge', target: 0.55, label: 'T avg 1.5-5 um ≥ 55%' },
            { kind: 'MIN_MAX', channel: 'T', direction: 'min', cmp: 'ge', target: 0.40, label: 'T min 1.5-5 um ≥ 40%' },
        ],
    },
    {
        id: 'gff-edfa-1525-1560-ta2o5-sio2-9l',
        name: 'EDFA gain flattening filter 1525-1560 nm, Ta2O5/SiO2, 9 layers',
        type: 'other',
        tags: ['nir', 'broadband', 'telecom', 'all-dielectric', 'ta2o5-sio2', 'normal-incidence', 'fused-silica', 'textbook'],
        use: 'Use this in front of an erbium-doped fibre amplifier to take the shape out of its gain. The filter transmits least where the amplifier gains most, so the two multiply out to a flat channel-to-channel power across the C band. Nine layers, but very thick ones.',
        limitations: 'The transmittance curve is the inverse of one published amplifier gain shape, so it only flattens an amplifier with that gain. The coating is 55 um of material and its thickest single layer is over 10 um, which is a very long run with a lot of stress and no turning point to monitor on. The filter costs about 40% of the light on average, which is the price of levelling the gain.',
        source: 'The Macleod Master Collection shipped with the Essential Macleod (Thin Film Center), design "Gain Flattening Filter": a nine-layer Ta2O5/SiO2 filter synthesized against a specification derived from the erbium-doped fibre amplifier gain curve published in C. K. Madsen and J. H. Zhao, Optical Filter Design and Analysis, Wiley (1999). The collection ships the target curve alongside the design. Re-optimized in TFStudio against that same target curve, which it now follows to under one percentage point in transmittance root mean square; the specification below states the shape at five wavelengths. The built-in Ta2O5 data carries enough extinction at 1550 nm to matter through 55 um of coating, so the entry carries the sputtered Ta2O5 of Gao, Lemarchand and Lequime from refractiveindex.info instead.',
        incidentMedium: 'builtin:Air',
        substrate: 'builtin:SiO2',
        referenceWavelength: 1550,
        bands: [[1525, 1560]],
        aoi: 0,
        polarization: 'avg',
        preview: [1500, 1600],
        layers: [
            { material: 'rii:Ta2O5-Gao', thickness: 3069.63 },
            { material: 'builtin:SiO2', thickness: 5674.14 },
            { material: 'rii:Ta2O5-Gao', thickness: 5994.91 },
            { material: 'builtin:SiO2', thickness: 10724.29 },
            { material: 'rii:Ta2O5-Gao', thickness: 9474.68 },
            { material: 'builtin:SiO2', thickness: 8722.62 },
            { material: 'rii:Ta2O5-Gao', thickness: 3224.90 },
            { material: 'builtin:SiO2', thickness: 110.16 },
            { material: 'rii:Ta2O5-Gao', thickness: 7876.31 },
        ],
        materials: embedded('rii:Ta2O5-Gao'),
        spec: [
            { kind: 'T_AT', channel: 'T', lambda: 1530, cmp: 'eq', target: 0.19, tol: 0.02, label: 'T at 1530 nm = 19% ± 2%' },
            { kind: 'T_AT', channel: 'T', lambda: 1540, cmp: 'eq', target: 0.92, tol: 0.02, label: 'T at 1540 nm = 92% ± 2%' },
            { kind: 'T_AT', channel: 'T', lambda: 1545, cmp: 'eq', target: 0.6, tol: 0.02, label: 'T at 1545 nm = 60% ± 2%' },
            { kind: 'T_AT', channel: 'T', lambda: 1550, cmp: 'eq', target: 0.74, tol: 0.02, label: 'T at 1550 nm = 74% ± 2%' },
            { kind: 'T_AT', channel: 'T', lambda: 1555, cmp: 'eq', target: 0.72, tol: 0.02, label: 'T at 1555 nm = 72% ± 2%' },
        ],
    },
];
